// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &activityAlertDataSource{}
	_ datasource.DataSourceWithConfigure = &activityAlertDataSource{}
)

type activityAlertDataSource struct{ client *clients.Client }

// NewActivityAlertDataSource looks up a ActivityAlert object (Get-ActivityAlert).
func NewActivityAlertDataSource() datasource.DataSource { return &activityAlertDataSource{} }

func (d *activityAlertDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_activity_alert"
}

func (d *activityAlertDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing ActivityAlert object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":            schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":      schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"category":      schema.StringAttribute{Computed: true, Description: "Maps to the -Category parameter."},
			"condition":     schema.StringAttribute{Computed: true, Description: "Maps to the -Condition parameter."},
			"description":   schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"disabled":      schema.BoolAttribute{Computed: true, Description: "Maps to the -Disabled parameter."},
			"email_culture": schema.StringAttribute{Computed: true, Description: "Maps to the -EmailCulture parameter."},
			"multiplier":    schema.StringAttribute{Computed: true, Description: "Maps to the -Multiplier parameter."},
			"name":          schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"notify_user":   schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUser parameter."},
			"operation":     schema.StringAttribute{Computed: true, Description: "Maps to the -Operation parameter."},
			"record_type":   schema.StringAttribute{Computed: true, Description: "Maps to the -RecordType parameter."},
			"scope_level":   schema.StringAttribute{Computed: true, Description: "Maps to the -ScopeLevel parameter."},
			"severity":      schema.StringAttribute{Computed: true, Description: "Maps to the -Severity parameter."},
			"type":          schema.StringAttribute{Computed: true, Description: "Maps to the -Type parameter."},
			"user_id":       schema.StringAttribute{Computed: true, Description: "Maps to the -UserId parameter."},
		},
	}
}

func (d *activityAlertDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *activityAlertDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data activityAlertModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetActivityAlert(ctx, purview.GetActivityAlertParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-ActivityAlert failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("ActivityAlert not found", "no ActivityAlert object for identity "+identity)
		return
	}
	readActivityAlert(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
