// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &adaptiveScopeListDataSource{}
	_ datasource.DataSourceWithConfigure = &adaptiveScopeListDataSource{}
)

type adaptiveScopeListDataSource struct{ client *clients.Client }

// NewAdaptiveScopeListDataSource lists every AdaptiveScope object (Get-AdaptiveScope).
func NewAdaptiveScopeListDataSource() datasource.DataSource { return &adaptiveScopeListDataSource{} }

type adaptiveScopeListModel struct {
	Items []adaptiveScopeModel `tfsdk:"adaptive_scopes"`
}

func (d *adaptiveScopeListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_adaptive_scopes"
}

func (d *adaptiveScopeListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every AdaptiveScope object (Get-AdaptiveScope).",
		Attributes: map[string]schema.Attribute{
			"adaptive_scopes": schema.ListNestedAttribute{Computed: true, Description: "All AdaptiveScope objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                              schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                        schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"administrative_unit":             schema.StringAttribute{Computed: true, Description: "Maps to the -AdministrativeUnit parameter."},
				"comment":                         schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"enabled_states":                  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -EnabledStates parameter."},
				"filter_conditions":               schema.StringAttribute{Computed: true, Description: "Maps to the -FilterConditions parameter."},
				"linked_recipient_enabled_states": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -LinkedRecipientEnabledStates parameter."},
				"location_type":                   schema.StringAttribute{Computed: true, Description: "Maps to the -LocationType parameter."},
				"name":                            schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"raw_query":                       schema.StringAttribute{Computed: true, Description: "Maps to the -RawQuery parameter."},
				"use_kql":                         schema.StringAttribute{Computed: true, Description: "Maps to the -UseKql parameter."},
			}}},
		},
	}
}

func (d *adaptiveScopeListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *adaptiveScopeListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetAdaptiveScope(ctx, purview.GetAdaptiveScopeParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-AdaptiveScope failed", err.Error())
		return
	}
	var data adaptiveScopeListModel
	for _, obj := range res.Value {
		var e adaptiveScopeModel
		readAdaptiveScope(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
