// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &appRetentionCompliancePolicyResource{}
	_ resource.ResourceWithConfigure   = &appRetentionCompliancePolicyResource{}
	_ resource.ResourceWithImportState = &appRetentionCompliancePolicyResource{}
)

type appRetentionCompliancePolicyResource struct{ client *clients.Client }

// NewAppRetentionCompliancePolicyResource manages the AppRetentionCompliancePolicy object (New-AppRetentionCompliancePolicy / Get-AppRetentionCompliancePolicy / Set-AppRetentionCompliancePolicy / Remove-AppRetentionCompliancePolicy).
func NewAppRetentionCompliancePolicyResource() resource.Resource {
	return &appRetentionCompliancePolicyResource{}
}

type appRetentionCompliancePolicyModel struct {
	ID                                 types.String `tfsdk:"id"`
	Identity                           types.String `tfsdk:"identity"`
	AdaptiveScopeLocation              types.String `tfsdk:"adaptive_scope_location"`
	AddAdaptiveScopeLocation           types.String `tfsdk:"add_adaptive_scope_location"`
	AddExchangeLocation                types.String `tfsdk:"add_exchange_location"`
	AddExchangeLocationException       types.String `tfsdk:"add_exchange_location_exception"`
	AddModernGroupLocation             types.String `tfsdk:"add_modern_group_location"`
	AddModernGroupLocationException    types.String `tfsdk:"add_modern_group_location_exception"`
	Applications                       types.Set    `tfsdk:"applications"`
	Comment                            types.String `tfsdk:"comment"`
	DeletedResources                   types.String `tfsdk:"deleted_resources"`
	Enabled                            types.Bool   `tfsdk:"enabled"`
	ExchangeLocation                   types.String `tfsdk:"exchange_location"`
	ExchangeLocationException          types.String `tfsdk:"exchange_location_exception"`
	Locations                          types.String `tfsdk:"locations"`
	ModernGroupLocation                types.String `tfsdk:"modern_group_location"`
	ModernGroupLocationException       types.String `tfsdk:"modern_group_location_exception"`
	Name                               types.String `tfsdk:"name"`
	PolicyRBACScopes                   types.String `tfsdk:"policy_rbac_scopes"`
	RemoveAdaptiveScopeLocation        types.String `tfsdk:"remove_adaptive_scope_location"`
	RemoveExchangeLocation             types.String `tfsdk:"remove_exchange_location"`
	RemoveExchangeLocationException    types.String `tfsdk:"remove_exchange_location_exception"`
	RemoveModernGroupLocation          types.String `tfsdk:"remove_modern_group_location"`
	RemoveModernGroupLocationException types.String `tfsdk:"remove_modern_group_location_exception"`
	RestrictiveRetention               types.Bool   `tfsdk:"restrictive_retention"`
	RetryDistribution                  types.Bool   `tfsdk:"retry_distribution"`
}

func (r *appRetentionCompliancePolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_app_retention_compliance_policy"
}

func (r *appRetentionCompliancePolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the AppRetentionCompliancePolicy object via New-AppRetentionCompliancePolicy / Get-AppRetentionCompliancePolicy / Set-AppRetentionCompliancePolicy / Remove-AppRetentionCompliancePolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                               schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"adaptive_scope_location":                schema.StringAttribute{Required: true, Description: "Maps to the -AdaptiveScopeLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"add_adaptive_scope_location":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AddAdaptiveScopeLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"add_exchange_location":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AddExchangeLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"add_exchange_location_exception":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AddExchangeLocationException parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"add_modern_group_location":              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AddModernGroupLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"add_modern_group_location_exception":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AddModernGroupLocationException parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"applications":                           schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -Applications parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"comment":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deleted_resources":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DeletedResources parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":                                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"exchange_location":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExchangeLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"exchange_location_exception":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExchangeLocationException parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"locations":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Locations parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"modern_group_location":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ModernGroupLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"modern_group_location_exception":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ModernGroupLocationException parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"name":                                   schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"policy_rbac_scopes":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PolicyRBACScopes parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"remove_adaptive_scope_location":         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveAdaptiveScopeLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"remove_exchange_location":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveExchangeLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"remove_exchange_location_exception":     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveExchangeLocationException parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"remove_modern_group_location":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveModernGroupLocation parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"remove_modern_group_location_exception": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveModernGroupLocationException parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"restrictive_retention":                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RestrictiveRetention parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"retry_distribution":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RetryDistribution parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *appRetentionCompliancePolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *appRetentionCompliancePolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan appRetentionCompliancePolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewAppRetentionCompliancePolicyParams{
		Applications:         toStringSlice(ctx, plan.Applications, &resp.Diagnostics),
		Comment:              plan.Comment.ValueString(),
		Enabled:              plan.Enabled.ValueBool(),
		Locations:            plan.Locations.ValueString(),
		Name:                 plan.Name.ValueString(),
		RestrictiveRetention: plan.RestrictiveRetention.ValueBool(),
	}
	if v := plan.AdaptiveScopeLocation.ValueString(); v != "" {
		p.AdaptiveScopeLocation = v
	}
	if v := plan.ExchangeLocation.ValueString(); v != "" {
		p.ExchangeLocation = v
	}
	if v := plan.ExchangeLocationException.ValueString(); v != "" {
		p.ExchangeLocationException = v
	}
	if v := plan.ModernGroupLocation.ValueString(); v != "" {
		p.ModernGroupLocation = v
	}
	if v := plan.ModernGroupLocationException.ValueString(); v != "" {
		p.ModernGroupLocationException = v
	}
	if v := plan.PolicyRBACScopes.ValueString(); v != "" {
		p.PolicyRBACScopes = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewAppRetentionCompliancePolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-AppRetentionCompliancePolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-AppRetentionCompliancePolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readAppRetentionCompliancePolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *appRetentionCompliancePolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state appRetentionCompliancePolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *appRetentionCompliancePolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state appRetentionCompliancePolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetAppRetentionCompliancePolicyParams{}
	sp.Identity = id
	if v := plan.AddAdaptiveScopeLocation.ValueString(); v != "" {
		sp.AddAdaptiveScopeLocation = v
	}
	if v := plan.AddExchangeLocation.ValueString(); v != "" {
		sp.AddExchangeLocation = v
	}
	if v := plan.AddExchangeLocationException.ValueString(); v != "" {
		sp.AddExchangeLocationException = v
	}
	if v := plan.AddModernGroupLocation.ValueString(); v != "" {
		sp.AddModernGroupLocation = v
	}
	if v := plan.AddModernGroupLocationException.ValueString(); v != "" {
		sp.AddModernGroupLocationException = v
	}
	sp.Applications = toStringSlice(ctx, plan.Applications, &resp.Diagnostics)
	sp.Comment = plan.Comment.ValueString()
	sp.DeletedResources = plan.DeletedResources.ValueString()
	sp.Enabled = plan.Enabled.ValueBool()
	if v := plan.PolicyRBACScopes.ValueString(); v != "" {
		sp.PolicyRBACScopes = v
	}
	if v := plan.RemoveAdaptiveScopeLocation.ValueString(); v != "" {
		sp.RemoveAdaptiveScopeLocation = v
	}
	if v := plan.RemoveExchangeLocation.ValueString(); v != "" {
		sp.RemoveExchangeLocation = v
	}
	if v := plan.RemoveExchangeLocationException.ValueString(); v != "" {
		sp.RemoveExchangeLocationException = v
	}
	if v := plan.RemoveModernGroupLocation.ValueString(); v != "" {
		sp.RemoveModernGroupLocation = v
	}
	if v := plan.RemoveModernGroupLocationException.ValueString(); v != "" {
		sp.RemoveModernGroupLocationException = v
	}
	sp.RestrictiveRetention = plan.RestrictiveRetention.ValueBool()
	sp.RetryDistribution = plan.RetryDistribution.ValueBool()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetAppRetentionCompliancePolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AppRetentionCompliancePolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AddAdaptiveScopeLocation":           cfg.AddAdaptiveScopeLocation,
		"AddExchangeLocation":                cfg.AddExchangeLocation,
		"AddExchangeLocationException":       cfg.AddExchangeLocationException,
		"AddModernGroupLocation":             cfg.AddModernGroupLocation,
		"AddModernGroupLocationException":    cfg.AddModernGroupLocationException,
		"Comment":                            cfg.Comment,
		"DeletedResources":                   cfg.DeletedResources,
		"PolicyRBACScopes":                   cfg.PolicyRBACScopes,
		"RemoveAdaptiveScopeLocation":        cfg.RemoveAdaptiveScopeLocation,
		"RemoveExchangeLocation":             cfg.RemoveExchangeLocation,
		"RemoveExchangeLocationException":    cfg.RemoveExchangeLocationException,
		"RemoveModernGroupLocation":          cfg.RemoveModernGroupLocation,
		"RemoveModernGroupLocationException": cfg.RemoveModernGroupLocationException,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *appRetentionCompliancePolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state appRetentionCompliancePolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveAppRetentionCompliancePolicy(ctx, purview.RemoveAppRetentionCompliancePolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-AppRetentionCompliancePolicy failed", err.Error())
		}
	}
}

func (r *appRetentionCompliancePolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *appRetentionCompliancePolicyResource) identityOf(m appRetentionCompliancePolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *appRetentionCompliancePolicyResource) refresh(ctx context.Context, identity string, m *appRetentionCompliancePolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetAppRetentionCompliancePolicy(ctx, purview.GetAppRetentionCompliancePolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-AppRetentionCompliancePolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readAppRetentionCompliancePolicy(ctx, obj, m)
	return true
}

func readAppRetentionCompliancePolicy(ctx context.Context, obj map[string]any, m *appRetentionCompliancePolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AdaptiveScopeLocation = types.StringValue(getString(obj, "AdaptiveScopeLocation"))
	m.AddAdaptiveScopeLocation = types.StringValue(getString(obj, "AddAdaptiveScopeLocation"))
	m.AddExchangeLocation = types.StringValue(getString(obj, "AddExchangeLocation"))
	m.AddExchangeLocationException = types.StringValue(getString(obj, "AddExchangeLocationException"))
	m.AddModernGroupLocation = types.StringValue(getString(obj, "AddModernGroupLocation"))
	m.AddModernGroupLocationException = types.StringValue(getString(obj, "AddModernGroupLocationException"))
	m.Applications = stringSetValue(ctx, getStringSlice(obj, "Applications"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.DeletedResources = types.StringValue(getString(obj, "DeletedResources"))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.ExchangeLocation = types.StringValue(getString(obj, "ExchangeLocation"))
	m.ExchangeLocationException = types.StringValue(getString(obj, "ExchangeLocationException"))
	m.Locations = types.StringValue(getString(obj, "Locations"))
	m.ModernGroupLocation = types.StringValue(getString(obj, "ModernGroupLocation"))
	m.ModernGroupLocationException = types.StringValue(getString(obj, "ModernGroupLocationException"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.PolicyRBACScopes = types.StringValue(getString(obj, "PolicyRBACScopes"))
	m.RemoveAdaptiveScopeLocation = types.StringValue(getString(obj, "RemoveAdaptiveScopeLocation"))
	m.RemoveExchangeLocation = types.StringValue(getString(obj, "RemoveExchangeLocation"))
	m.RemoveExchangeLocationException = types.StringValue(getString(obj, "RemoveExchangeLocationException"))
	m.RemoveModernGroupLocation = types.StringValue(getString(obj, "RemoveModernGroupLocation"))
	m.RemoveModernGroupLocationException = types.StringValue(getString(obj, "RemoveModernGroupLocationException"))
	m.RestrictiveRetention = types.BoolValue(getBool(obj, "RestrictiveRetention"))
	m.RetryDistribution = types.BoolValue(getBool(obj, "RetryDistribution"))
	_ = ctx
}

func (r *appRetentionCompliancePolicyResource) reconcileState(cfg, read *appRetentionCompliancePolicyModel) {
	read.AdaptiveScopeLocation = reconcile.KeepStr(cfg.AdaptiveScopeLocation, read.AdaptiveScopeLocation)
	read.AddAdaptiveScopeLocation = reconcile.KeepStr(cfg.AddAdaptiveScopeLocation, read.AddAdaptiveScopeLocation)
	read.AddExchangeLocation = reconcile.KeepStr(cfg.AddExchangeLocation, read.AddExchangeLocation)
	read.AddExchangeLocationException = reconcile.KeepStr(cfg.AddExchangeLocationException, read.AddExchangeLocationException)
	read.AddModernGroupLocation = reconcile.KeepStr(cfg.AddModernGroupLocation, read.AddModernGroupLocation)
	read.AddModernGroupLocationException = reconcile.KeepStr(cfg.AddModernGroupLocationException, read.AddModernGroupLocationException)
	read.Applications = reconcile.KeepSet(cfg.Applications, read.Applications)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.DeletedResources = reconcile.KeepStr(cfg.DeletedResources, read.DeletedResources)
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.ExchangeLocation = reconcile.KeepStr(cfg.ExchangeLocation, read.ExchangeLocation)
	read.ExchangeLocationException = reconcile.KeepStr(cfg.ExchangeLocationException, read.ExchangeLocationException)
	read.Locations = reconcile.KeepStr(cfg.Locations, read.Locations)
	read.ModernGroupLocation = reconcile.KeepStr(cfg.ModernGroupLocation, read.ModernGroupLocation)
	read.ModernGroupLocationException = reconcile.KeepStr(cfg.ModernGroupLocationException, read.ModernGroupLocationException)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.PolicyRBACScopes = reconcile.KeepStr(cfg.PolicyRBACScopes, read.PolicyRBACScopes)
	read.RemoveAdaptiveScopeLocation = reconcile.KeepStr(cfg.RemoveAdaptiveScopeLocation, read.RemoveAdaptiveScopeLocation)
	read.RemoveExchangeLocation = reconcile.KeepStr(cfg.RemoveExchangeLocation, read.RemoveExchangeLocation)
	read.RemoveExchangeLocationException = reconcile.KeepStr(cfg.RemoveExchangeLocationException, read.RemoveExchangeLocationException)
	read.RemoveModernGroupLocation = reconcile.KeepStr(cfg.RemoveModernGroupLocation, read.RemoveModernGroupLocation)
	read.RemoveModernGroupLocationException = reconcile.KeepStr(cfg.RemoveModernGroupLocationException, read.RemoveModernGroupLocationException)
	read.RestrictiveRetention = reconcile.KeepBool(cfg.RestrictiveRetention, read.RestrictiveRetention)
	read.RetryDistribution = reconcile.KeepBool(cfg.RetryDistribution, read.RetryDistribution)
}
