// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &auditConfigResource{}
	_ resource.ResourceWithConfigure   = &auditConfigResource{}
	_ resource.ResourceWithImportState = &auditConfigResource{}
)

type auditConfigResource struct{ client *clients.Client }

// NewAuditConfigResource manages the AuditConfig configuration (Get-AuditConfig / Set-AuditConfig); it adopts the existing object and is not deleted on destroy.
func NewAuditConfigResource() resource.Resource { return &auditConfigResource{} }

type auditConfigModel struct {
	ID       types.String `tfsdk:"id"`
	Identity types.String `tfsdk:"identity"`
	Workload types.String `tfsdk:"workload"`
}

func (r *auditConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_audit_config"
}

func (r *auditConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the AuditConfig configuration via Set-AuditConfig.",
		Attributes: map[string]schema.Attribute{
			"id":       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity": schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"workload": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Workload parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *auditConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *auditConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan auditConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	sp := purview.SetAuditConfigParams{}
	if v := plan.Workload.ValueString(); v != "" {
		sp.Workload = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetAuditConfig(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AuditConfig failed", err.Error())
		return
	}
	cfg := plan
	identity := ""
	r.refresh(ctx, identity, &plan, &resp.Diagnostics, nil)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *auditConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state auditConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *auditConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state auditConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetAuditConfigParams{}
	if v := plan.Workload.ValueString(); v != "" {
		sp.Workload = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetAuditConfig(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-AuditConfig failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Workload": cfg.Workload,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *auditConfigResource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("AuditConfig configuration not deleted", "This resource manages an existing AuditConfig configuration. It has been removed from Terraform state, but the configuration itself remains unchanged in the tenant.")
}

func (r *auditConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *auditConfigResource) identityOf(m auditConfigModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *auditConfigResource) refresh(ctx context.Context, identity string, m *auditConfigModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		_ = identity
		res, gerr := r.client.SCC.GetAuditConfig(ctx, purview.GetAuditConfigParams{})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-AuditConfig failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readAuditConfig(ctx, obj, m)
	return true
}

func readAuditConfig(ctx context.Context, obj map[string]any, m *auditConfigModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Workload = types.StringValue(getString(obj, "Workload"))
	_ = ctx
}

func (r *auditConfigResource) reconcileState(cfg, read *auditConfigModel) {
	read.Workload = reconcile.KeepStr(cfg.Workload, read.Workload)
}
