// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &classificationGradingPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &classificationGradingPolicyListDataSource{}
)

type classificationGradingPolicyListDataSource struct{ client *clients.Client }

// NewClassificationGradingPolicyListDataSource lists every ClassificationGradingPolicy object (Get-ClassificationGradingPolicy).
func NewClassificationGradingPolicyListDataSource() datasource.DataSource {
	return &classificationGradingPolicyListDataSource{}
}

type classificationGradingPolicyListModel struct {
	Items []classificationGradingPolicyModel `tfsdk:"classification_grading_policies"`
}

func (d *classificationGradingPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_classification_grading_policies"
}

func (d *classificationGradingPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ClassificationGradingPolicy object (Get-ClassificationGradingPolicy).",
		Attributes: map[string]schema.Attribute{
			"classification_grading_policies": schema.ListNestedAttribute{Computed: true, Description: "All ClassificationGradingPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                             schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                       schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"end_date_time":                  schema.StringAttribute{Computed: true, Description: "Maps to the -EndDateTime parameter."},
				"grader_id":                      schema.StringAttribute{Computed: true, Description: "Maps to the -GraderId parameter."},
				"name":                           schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"sensitive_information_type_ids": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -SensitiveInformationTypeIds parameter."},
				"start_date_time":                schema.StringAttribute{Computed: true, Description: "Maps to the -StartDateTime parameter."},
			}}},
		},
	}
}

func (d *classificationGradingPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *classificationGradingPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetClassificationGradingPolicy(ctx, purview.GetClassificationGradingPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ClassificationGradingPolicy failed", err.Error())
		return
	}
	var data classificationGradingPolicyListModel
	for _, obj := range res.Value {
		var e classificationGradingPolicyModel
		readClassificationGradingPolicy(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
