// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &classificationGradingPolicyResource{}
	_ resource.ResourceWithConfigure   = &classificationGradingPolicyResource{}
	_ resource.ResourceWithImportState = &classificationGradingPolicyResource{}
)

type classificationGradingPolicyResource struct{ client *clients.Client }

// NewClassificationGradingPolicyResource manages the ClassificationGradingPolicy object (New-ClassificationGradingPolicy / Get-ClassificationGradingPolicy / Set-ClassificationGradingPolicy / Remove-ClassificationGradingPolicy).
func NewClassificationGradingPolicyResource() resource.Resource {
	return &classificationGradingPolicyResource{}
}

type classificationGradingPolicyModel struct {
	ID                          types.String `tfsdk:"id"`
	Identity                    types.String `tfsdk:"identity"`
	EndDateTime                 types.String `tfsdk:"end_date_time"`
	GraderId                    types.String `tfsdk:"grader_id"`
	Name                        types.String `tfsdk:"name"`
	SensitiveInformationTypeIds types.Set    `tfsdk:"sensitive_information_type_ids"`
	StartDateTime               types.String `tfsdk:"start_date_time"`
}

func (r *classificationGradingPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_classification_grading_policy"
}

func (r *classificationGradingPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the ClassificationGradingPolicy object via New-ClassificationGradingPolicy / Get-ClassificationGradingPolicy / Set-ClassificationGradingPolicy / Remove-ClassificationGradingPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                             schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                       schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"end_date_time":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EndDateTime parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"grader_id":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -GraderId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"name":                           schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"sensitive_information_type_ids": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -SensitiveInformationTypeIds parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"start_date_time":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -StartDateTime parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *classificationGradingPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *classificationGradingPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan classificationGradingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewClassificationGradingPolicyParams{
		Name:                        plan.Name.ValueString(),
		SensitiveInformationTypeIds: toStringSlice(ctx, plan.SensitiveInformationTypeIds, &resp.Diagnostics),
	}
	if v := plan.EndDateTime.ValueString(); v != "" {
		p.EndDateTime = v
	}
	if v := plan.GraderId.ValueString(); v != "" {
		p.GraderId = v
	}
	if v := plan.StartDateTime.ValueString(); v != "" {
		p.StartDateTime = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewClassificationGradingPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-ClassificationGradingPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-ClassificationGradingPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readClassificationGradingPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *classificationGradingPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state classificationGradingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *classificationGradingPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state classificationGradingPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetClassificationGradingPolicyParams{}
	sp.Identity = id
	if v := plan.EndDateTime.ValueString(); v != "" {
		sp.EndDateTime = v
	}
	sp.SensitiveInformationTypeIds = toStringSlice(ctx, plan.SensitiveInformationTypeIds, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetClassificationGradingPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ClassificationGradingPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"EndDateTime": cfg.EndDateTime,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *classificationGradingPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state classificationGradingPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveClassificationGradingPolicy(ctx, purview.RemoveClassificationGradingPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-ClassificationGradingPolicy failed", err.Error())
		}
	}
}

func (r *classificationGradingPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *classificationGradingPolicyResource) identityOf(m classificationGradingPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *classificationGradingPolicyResource) refresh(ctx context.Context, identity string, m *classificationGradingPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetClassificationGradingPolicy(ctx, purview.GetClassificationGradingPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ClassificationGradingPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readClassificationGradingPolicy(ctx, obj, m)
	return true
}

func readClassificationGradingPolicy(ctx context.Context, obj map[string]any, m *classificationGradingPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.EndDateTime = types.StringValue(getString(obj, "EndDateTime"))
	m.GraderId = types.StringValue(getString(obj, "GraderId"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.SensitiveInformationTypeIds = stringSetValue(ctx, getStringSlice(obj, "SensitiveInformationTypeIds"))
	m.StartDateTime = types.StringValue(getString(obj, "StartDateTime"))
	_ = ctx
}

func (r *classificationGradingPolicyResource) reconcileState(cfg, read *classificationGradingPolicyModel) {
	read.EndDateTime = reconcile.KeepStr(cfg.EndDateTime, read.EndDateTime)
	read.GraderId = reconcile.KeepStr(cfg.GraderId, read.GraderId)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.SensitiveInformationTypeIds = reconcile.KeepSet(cfg.SensitiveInformationTypeIds, read.SensitiveInformationTypeIds)
	read.StartDateTime = reconcile.KeepStr(cfg.StartDateTime, read.StartDateTime)
}
