// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &complianceRetentionEventResource{}
	_ resource.ResourceWithConfigure   = &complianceRetentionEventResource{}
	_ resource.ResourceWithImportState = &complianceRetentionEventResource{}
)

type complianceRetentionEventResource struct{ client *clients.Client }

// NewComplianceRetentionEventResource manages the ComplianceRetentionEvent object (New-ComplianceRetentionEvent / Get-ComplianceRetentionEvent / Set-ComplianceRetentionEvent / Remove-ComplianceRetentionEvent).
func NewComplianceRetentionEventResource() resource.Resource {
	return &complianceRetentionEventResource{}
}

type complianceRetentionEventModel struct {
	ID                     types.String `tfsdk:"id"`
	Identity               types.String `tfsdk:"identity"`
	Action                 types.String `tfsdk:"action"`
	AssetId                types.String `tfsdk:"asset_id"`
	Comment                types.String `tfsdk:"comment"`
	EventDateTime          types.String `tfsdk:"event_date_time"`
	EventTags              types.String `tfsdk:"event_tags"`
	EventType              types.String `tfsdk:"event_type"`
	ExchangeAssetIdQuery   types.String `tfsdk:"exchange_asset_id_query"`
	Name                   types.String `tfsdk:"name"`
	PreviewOnly            types.Bool   `tfsdk:"preview_only"`
	SharePointAssetIdQuery types.String `tfsdk:"share_point_asset_id_query"`
}

func (r *complianceRetentionEventResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compliance_retention_event"
}

func (r *complianceRetentionEventResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the ComplianceRetentionEvent object via New-ComplianceRetentionEvent / Get-ComplianceRetentionEvent / Set-ComplianceRetentionEvent / Remove-ComplianceRetentionEvent.",
		Attributes: map[string]schema.Attribute{
			"id":                         schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                   schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"action":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Action parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"asset_id":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AssetId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comment":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"event_date_time":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EventDateTime parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"event_tags":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EventTags parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"event_type":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EventType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"exchange_asset_id_query":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExchangeAssetIdQuery parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":                       schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"preview_only":               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -PreviewOnly parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace(), boolplanmodifier.UseStateForUnknown()}},
			"share_point_asset_id_query": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SharePointAssetIdQuery parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *complianceRetentionEventResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *complianceRetentionEventResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan complianceRetentionEventModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewComplianceRetentionEventParams{
		AssetId:                plan.AssetId.ValueString(),
		Comment:                plan.Comment.ValueString(),
		ExchangeAssetIdQuery:   plan.ExchangeAssetIdQuery.ValueString(),
		Name:                   plan.Name.ValueString(),
		PreviewOnly:            plan.PreviewOnly.ValueBool(),
		SharePointAssetIdQuery: plan.SharePointAssetIdQuery.ValueString(),
	}
	if v := plan.EventDateTime.ValueString(); v != "" {
		p.EventDateTime = v
	}
	if v := plan.EventTags.ValueString(); v != "" {
		p.EventTags = v
	}
	if v := plan.EventType.ValueString(); v != "" {
		p.EventType = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewComplianceRetentionEvent(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-ComplianceRetentionEvent failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-ComplianceRetentionEvent returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readComplianceRetentionEvent(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *complianceRetentionEventResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state complianceRetentionEventModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *complianceRetentionEventResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state complianceRetentionEventModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetComplianceRetentionEventParams{}
	sp.Identity = id
	if v := plan.Action.ValueString(); v != "" {
		sp.Action = v
	}
	sp.AssetId = plan.AssetId.ValueString()
	sp.Comment = plan.Comment.ValueString()
	if v := plan.EventTags.ValueString(); v != "" {
		sp.EventTags = v
	}
	if v := plan.EventType.ValueString(); v != "" {
		sp.EventType = v
	}
	sp.ExchangeAssetIdQuery = plan.ExchangeAssetIdQuery.ValueString()
	sp.SharePointAssetIdQuery = plan.SharePointAssetIdQuery.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetComplianceRetentionEvent(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ComplianceRetentionEvent failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Action":                 cfg.Action,
		"AssetId":                cfg.AssetId,
		"Comment":                cfg.Comment,
		"EventTags":              cfg.EventTags,
		"EventType":              cfg.EventType,
		"ExchangeAssetIdQuery":   cfg.ExchangeAssetIdQuery,
		"SharePointAssetIdQuery": cfg.SharePointAssetIdQuery,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *complianceRetentionEventResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state complianceRetentionEventModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveComplianceRetentionEvent(ctx, purview.RemoveComplianceRetentionEventParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-ComplianceRetentionEvent failed", err.Error())
		}
	}
}

func (r *complianceRetentionEventResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *complianceRetentionEventResource) identityOf(m complianceRetentionEventModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *complianceRetentionEventResource) refresh(ctx context.Context, identity string, m *complianceRetentionEventModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetComplianceRetentionEvent(ctx, purview.GetComplianceRetentionEventParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ComplianceRetentionEvent failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readComplianceRetentionEvent(ctx, obj, m)
	return true
}

func readComplianceRetentionEvent(ctx context.Context, obj map[string]any, m *complianceRetentionEventModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Action = types.StringValue(getString(obj, "Action"))
	m.AssetId = types.StringValue(getString(obj, "AssetId"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.EventDateTime = types.StringValue(getString(obj, "EventDateTime"))
	m.EventTags = types.StringValue(getString(obj, "EventTags"))
	m.EventType = types.StringValue(getString(obj, "EventType"))
	m.ExchangeAssetIdQuery = types.StringValue(getString(obj, "ExchangeAssetIdQuery"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.PreviewOnly = types.BoolValue(getBool(obj, "PreviewOnly"))
	m.SharePointAssetIdQuery = types.StringValue(getString(obj, "SharePointAssetIdQuery"))
	_ = ctx
}

func (r *complianceRetentionEventResource) reconcileState(cfg, read *complianceRetentionEventModel) {
	read.Action = reconcile.KeepStr(cfg.Action, read.Action)
	read.AssetId = reconcile.KeepStr(cfg.AssetId, read.AssetId)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.EventDateTime = reconcile.KeepStr(cfg.EventDateTime, read.EventDateTime)
	read.EventTags = reconcile.KeepStr(cfg.EventTags, read.EventTags)
	read.EventType = reconcile.KeepStr(cfg.EventType, read.EventType)
	read.ExchangeAssetIdQuery = reconcile.KeepStr(cfg.ExchangeAssetIdQuery, read.ExchangeAssetIdQuery)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.PreviewOnly = reconcile.KeepBool(cfg.PreviewOnly, read.PreviewOnly)
	read.SharePointAssetIdQuery = reconcile.KeepStr(cfg.SharePointAssetIdQuery, read.SharePointAssetIdQuery)
}
