// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &complianceSearchResource{}
	_ resource.ResourceWithConfigure   = &complianceSearchResource{}
	_ resource.ResourceWithImportState = &complianceSearchResource{}
)

type complianceSearchResource struct{ client *clients.Client }

// NewComplianceSearchResource manages the ComplianceSearch object (New-ComplianceSearch / Get-ComplianceSearch / Set-ComplianceSearch / Remove-ComplianceSearch).
func NewComplianceSearchResource() resource.Resource { return &complianceSearchResource{} }

type complianceSearchModel struct {
	ID                                    types.String `tfsdk:"id"`
	Identity                              types.String `tfsdk:"identity"`
	AddExchangeLocation                   types.Set    `tfsdk:"add_exchange_location"`
	AddExchangeLocationExclusion          types.Set    `tfsdk:"add_exchange_location_exclusion"`
	AddOneDriveLocation                   types.Set    `tfsdk:"add_one_drive_location"`
	AddOneDriveLocationExclusion          types.Set    `tfsdk:"add_one_drive_location_exclusion"`
	AddPublicFolderLocation               types.Set    `tfsdk:"add_public_folder_location"`
	AddPublicFolderLocationExclusion      types.Set    `tfsdk:"add_public_folder_location_exclusion"`
	AddSharePointLocation                 types.Set    `tfsdk:"add_share_point_location"`
	AddSharePointLocationExclusion        types.Set    `tfsdk:"add_share_point_location_exclusion"`
	AllowNotFoundExchangeLocationsEnabled types.Bool   `tfsdk:"allow_not_found_exchange_locations_enabled"`
	Case                                  types.String `tfsdk:"case"`
	ContentMatchQuery                     types.String `tfsdk:"content_match_query"`
	Description                           types.String `tfsdk:"description"`
	ExchangeLocation                      types.Set    `tfsdk:"exchange_location"`
	ExchangeLocationExclusion             types.Set    `tfsdk:"exchange_location_exclusion"`
	HoldNames                             types.Set    `tfsdk:"hold_names"`
	IncludeOrgContent                     types.Bool   `tfsdk:"include_org_content"`
	IncludeUserAppContent                 types.Bool   `tfsdk:"include_user_app_content"`
	Language                              types.String `tfsdk:"language"`
	LogLevel                              types.String `tfsdk:"log_level"`
	Name                                  types.String `tfsdk:"name"`
	OneDriveLocation                      types.Set    `tfsdk:"one_drive_location"`
	OneDriveLocationExclusion             types.Set    `tfsdk:"one_drive_location_exclusion"`
	PublicFolderLocation                  types.Set    `tfsdk:"public_folder_location"`
	PublicFolderLocationExclusion         types.Set    `tfsdk:"public_folder_location_exclusion"`
	RefinerNames                          types.Set    `tfsdk:"refiner_names"`
	RemoveExchangeLocation                types.Set    `tfsdk:"remove_exchange_location"`
	RemoveExchangeLocationExclusion       types.Set    `tfsdk:"remove_exchange_location_exclusion"`
	RemoveOneDriveLocation                types.Set    `tfsdk:"remove_one_drive_location"`
	RemoveOneDriveLocationExclusion       types.Set    `tfsdk:"remove_one_drive_location_exclusion"`
	RemovePublicFolderLocation            types.Set    `tfsdk:"remove_public_folder_location"`
	RemovePublicFolderLocationExclusion   types.Set    `tfsdk:"remove_public_folder_location_exclusion"`
	RemoveSharePointLocation              types.Set    `tfsdk:"remove_share_point_location"`
	RemoveSharePointLocationExclusion     types.Set    `tfsdk:"remove_share_point_location_exclusion"`
	SearchNames                           types.Set    `tfsdk:"search_names"`
	SharePointLocation                    types.Set    `tfsdk:"share_point_location"`
	SharePointLocationExclusion           types.Set    `tfsdk:"share_point_location_exclusion"`
	StatusMailRecipients                  types.Set    `tfsdk:"status_mail_recipients"`
}

func (r *complianceSearchResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compliance_search"
}

func (r *complianceSearchResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the ComplianceSearch object via New-ComplianceSearch / Get-ComplianceSearch / Set-ComplianceSearch / Remove-ComplianceSearch.",
		Attributes: map[string]schema.Attribute{
			"id":                                         schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                                   schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"add_exchange_location":                      schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddExchangeLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"add_exchange_location_exclusion":            schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddExchangeLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"add_one_drive_location":                     schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddOneDriveLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"add_one_drive_location_exclusion":           schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddOneDriveLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"add_public_folder_location":                 schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddPublicFolderLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"add_public_folder_location_exclusion":       schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddPublicFolderLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"add_share_point_location":                   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddSharePointLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"add_share_point_location_exclusion":         schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddSharePointLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"allow_not_found_exchange_locations_enabled": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -AllowNotFoundExchangeLocationsEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"case":                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Case parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"content_match_query":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ContentMatchQuery parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"description":                             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"exchange_location":                       schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ExchangeLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"exchange_location_exclusion":             schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ExchangeLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"hold_names":                              schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -HoldNames parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"include_org_content":                     schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IncludeOrgContent parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"include_user_app_content":                schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IncludeUserAppContent parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"language":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Language parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"log_level":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LogLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"name":                                    schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"one_drive_location":                      schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -OneDriveLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"one_drive_location_exclusion":            schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -OneDriveLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"public_folder_location":                  schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -PublicFolderLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"public_folder_location_exclusion":        schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -PublicFolderLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"refiner_names":                           schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RefinerNames parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_exchange_location":                schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemoveExchangeLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_exchange_location_exclusion":      schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemoveExchangeLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_one_drive_location":               schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemoveOneDriveLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_one_drive_location_exclusion":     schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemoveOneDriveLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_public_folder_location":           schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemovePublicFolderLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_public_folder_location_exclusion": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemovePublicFolderLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_share_point_location":             schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemoveSharePointLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"remove_share_point_location_exclusion":   schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemoveSharePointLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"search_names":                            schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -SearchNames parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"share_point_location":                    schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -SharePointLocation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"share_point_location_exclusion":          schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -SharePointLocationExclusion parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"status_mail_recipients":                  schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -StatusMailRecipients parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.RequiresReplace(), setplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *complianceSearchResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *complianceSearchResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan complianceSearchModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewComplianceSearchParams{
		AllowNotFoundExchangeLocationsEnabled: plan.AllowNotFoundExchangeLocationsEnabled.ValueBool(),
		Case:                                  plan.Case.ValueString(),
		ContentMatchQuery:                     plan.ContentMatchQuery.ValueString(),
		Description:                           plan.Description.ValueString(),
		ExchangeLocation:                      toStringSlice(ctx, plan.ExchangeLocation, &resp.Diagnostics),
		ExchangeLocationExclusion:             toStringSlice(ctx, plan.ExchangeLocationExclusion, &resp.Diagnostics),
		HoldNames:                             toStringSlice(ctx, plan.HoldNames, &resp.Diagnostics),
		IncludeOrgContent:                     plan.IncludeOrgContent.ValueBool(),
		IncludeUserAppContent:                 plan.IncludeUserAppContent.ValueBool(),
		Name:                                  plan.Name.ValueString(),
		OneDriveLocation:                      toStringSlice(ctx, plan.OneDriveLocation, &resp.Diagnostics),
		OneDriveLocationExclusion:             toStringSlice(ctx, plan.OneDriveLocationExclusion, &resp.Diagnostics),
		PublicFolderLocation:                  toStringSlice(ctx, plan.PublicFolderLocation, &resp.Diagnostics),
		PublicFolderLocationExclusion:         toStringSlice(ctx, plan.PublicFolderLocationExclusion, &resp.Diagnostics),
		RefinerNames:                          toStringSlice(ctx, plan.RefinerNames, &resp.Diagnostics),
		SearchNames:                           toStringSlice(ctx, plan.SearchNames, &resp.Diagnostics),
		SharePointLocation:                    toStringSlice(ctx, plan.SharePointLocation, &resp.Diagnostics),
		SharePointLocationExclusion:           toStringSlice(ctx, plan.SharePointLocationExclusion, &resp.Diagnostics),
		StatusMailRecipients:                  toStringSlice(ctx, plan.StatusMailRecipients, &resp.Diagnostics),
	}
	if v := plan.Language.ValueString(); v != "" {
		p.Language = v
	}
	if v := plan.LogLevel.ValueString(); v != "" {
		p.LogLevel = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewComplianceSearch(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-ComplianceSearch failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-ComplianceSearch returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readComplianceSearch(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *complianceSearchResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state complianceSearchModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *complianceSearchResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state complianceSearchModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetComplianceSearchParams{}
	sp.Identity = id
	sp.AddExchangeLocation = toStringSlice(ctx, plan.AddExchangeLocation, &resp.Diagnostics)
	sp.AddExchangeLocationExclusion = toStringSlice(ctx, plan.AddExchangeLocationExclusion, &resp.Diagnostics)
	sp.AddOneDriveLocation = toStringSlice(ctx, plan.AddOneDriveLocation, &resp.Diagnostics)
	sp.AddOneDriveLocationExclusion = toStringSlice(ctx, plan.AddOneDriveLocationExclusion, &resp.Diagnostics)
	sp.AddPublicFolderLocation = toStringSlice(ctx, plan.AddPublicFolderLocation, &resp.Diagnostics)
	sp.AddPublicFolderLocationExclusion = toStringSlice(ctx, plan.AddPublicFolderLocationExclusion, &resp.Diagnostics)
	sp.AddSharePointLocation = toStringSlice(ctx, plan.AddSharePointLocation, &resp.Diagnostics)
	sp.AddSharePointLocationExclusion = toStringSlice(ctx, plan.AddSharePointLocationExclusion, &resp.Diagnostics)
	sp.AllowNotFoundExchangeLocationsEnabled = plan.AllowNotFoundExchangeLocationsEnabled.ValueBool()
	sp.ContentMatchQuery = plan.ContentMatchQuery.ValueString()
	sp.Description = plan.Description.ValueString()
	sp.ExchangeLocation = toStringSlice(ctx, plan.ExchangeLocation, &resp.Diagnostics)
	sp.ExchangeLocationExclusion = toStringSlice(ctx, plan.ExchangeLocationExclusion, &resp.Diagnostics)
	sp.HoldNames = toStringSlice(ctx, plan.HoldNames, &resp.Diagnostics)
	sp.IncludeOrgContent = plan.IncludeOrgContent.ValueBool()
	sp.IncludeUserAppContent = plan.IncludeUserAppContent.ValueBool()
	if v := plan.Language.ValueString(); v != "" {
		sp.Language = v
	}
	sp.OneDriveLocation = toStringSlice(ctx, plan.OneDriveLocation, &resp.Diagnostics)
	sp.OneDriveLocationExclusion = toStringSlice(ctx, plan.OneDriveLocationExclusion, &resp.Diagnostics)
	sp.PublicFolderLocation = toStringSlice(ctx, plan.PublicFolderLocation, &resp.Diagnostics)
	sp.PublicFolderLocationExclusion = toStringSlice(ctx, plan.PublicFolderLocationExclusion, &resp.Diagnostics)
	sp.RefinerNames = toStringSlice(ctx, plan.RefinerNames, &resp.Diagnostics)
	sp.RemoveExchangeLocation = toStringSlice(ctx, plan.RemoveExchangeLocation, &resp.Diagnostics)
	sp.RemoveExchangeLocationExclusion = toStringSlice(ctx, plan.RemoveExchangeLocationExclusion, &resp.Diagnostics)
	sp.RemoveOneDriveLocation = toStringSlice(ctx, plan.RemoveOneDriveLocation, &resp.Diagnostics)
	sp.RemoveOneDriveLocationExclusion = toStringSlice(ctx, plan.RemoveOneDriveLocationExclusion, &resp.Diagnostics)
	sp.RemovePublicFolderLocation = toStringSlice(ctx, plan.RemovePublicFolderLocation, &resp.Diagnostics)
	sp.RemovePublicFolderLocationExclusion = toStringSlice(ctx, plan.RemovePublicFolderLocationExclusion, &resp.Diagnostics)
	sp.RemoveSharePointLocation = toStringSlice(ctx, plan.RemoveSharePointLocation, &resp.Diagnostics)
	sp.RemoveSharePointLocationExclusion = toStringSlice(ctx, plan.RemoveSharePointLocationExclusion, &resp.Diagnostics)
	sp.SearchNames = toStringSlice(ctx, plan.SearchNames, &resp.Diagnostics)
	sp.SharePointLocation = toStringSlice(ctx, plan.SharePointLocation, &resp.Diagnostics)
	sp.SharePointLocationExclusion = toStringSlice(ctx, plan.SharePointLocationExclusion, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetComplianceSearch(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ComplianceSearch failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"ContentMatchQuery": cfg.ContentMatchQuery,
		"Description":       cfg.Description,
		"Language":          cfg.Language,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *complianceSearchResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state complianceSearchModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveComplianceSearch(ctx, purview.RemoveComplianceSearchParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-ComplianceSearch failed", err.Error())
		}
	}
}

func (r *complianceSearchResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *complianceSearchResource) identityOf(m complianceSearchModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *complianceSearchResource) refresh(ctx context.Context, identity string, m *complianceSearchModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetComplianceSearch(ctx, purview.GetComplianceSearchParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ComplianceSearch failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readComplianceSearch(ctx, obj, m)
	return true
}

func readComplianceSearch(ctx context.Context, obj map[string]any, m *complianceSearchModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AddExchangeLocation = stringSetValue(ctx, getStringSlice(obj, "AddExchangeLocation"))
	m.AddExchangeLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "AddExchangeLocationExclusion"))
	m.AddOneDriveLocation = stringSetValue(ctx, getStringSlice(obj, "AddOneDriveLocation"))
	m.AddOneDriveLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "AddOneDriveLocationExclusion"))
	m.AddPublicFolderLocation = stringSetValue(ctx, getStringSlice(obj, "AddPublicFolderLocation"))
	m.AddPublicFolderLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "AddPublicFolderLocationExclusion"))
	m.AddSharePointLocation = stringSetValue(ctx, getStringSlice(obj, "AddSharePointLocation"))
	m.AddSharePointLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "AddSharePointLocationExclusion"))
	m.AllowNotFoundExchangeLocationsEnabled = types.BoolValue(getBool(obj, "AllowNotFoundExchangeLocationsEnabled"))
	m.Case = types.StringValue(getString(obj, "Case"))
	m.ContentMatchQuery = types.StringValue(getString(obj, "ContentMatchQuery"))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.ExchangeLocation = stringSetValue(ctx, getStringSlice(obj, "ExchangeLocation"))
	m.ExchangeLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "ExchangeLocationExclusion"))
	m.HoldNames = stringSetValue(ctx, getStringSlice(obj, "HoldNames"))
	m.IncludeOrgContent = types.BoolValue(getBool(obj, "IncludeOrgContent"))
	m.IncludeUserAppContent = types.BoolValue(getBool(obj, "IncludeUserAppContent"))
	m.Language = types.StringValue(getString(obj, "Language"))
	m.LogLevel = types.StringValue(getString(obj, "LogLevel"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.OneDriveLocation = stringSetValue(ctx, getStringSlice(obj, "OneDriveLocation"))
	m.OneDriveLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "OneDriveLocationExclusion"))
	m.PublicFolderLocation = stringSetValue(ctx, getStringSlice(obj, "PublicFolderLocation"))
	m.PublicFolderLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "PublicFolderLocationExclusion"))
	m.RefinerNames = stringSetValue(ctx, getStringSlice(obj, "RefinerNames"))
	m.RemoveExchangeLocation = stringSetValue(ctx, getStringSlice(obj, "RemoveExchangeLocation"))
	m.RemoveExchangeLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "RemoveExchangeLocationExclusion"))
	m.RemoveOneDriveLocation = stringSetValue(ctx, getStringSlice(obj, "RemoveOneDriveLocation"))
	m.RemoveOneDriveLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "RemoveOneDriveLocationExclusion"))
	m.RemovePublicFolderLocation = stringSetValue(ctx, getStringSlice(obj, "RemovePublicFolderLocation"))
	m.RemovePublicFolderLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "RemovePublicFolderLocationExclusion"))
	m.RemoveSharePointLocation = stringSetValue(ctx, getStringSlice(obj, "RemoveSharePointLocation"))
	m.RemoveSharePointLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "RemoveSharePointLocationExclusion"))
	m.SearchNames = stringSetValue(ctx, getStringSlice(obj, "SearchNames"))
	m.SharePointLocation = stringSetValue(ctx, getStringSlice(obj, "SharePointLocation"))
	m.SharePointLocationExclusion = stringSetValue(ctx, getStringSlice(obj, "SharePointLocationExclusion"))
	m.StatusMailRecipients = stringSetValue(ctx, getStringSlice(obj, "StatusMailRecipients"))
	_ = ctx
}

func (r *complianceSearchResource) reconcileState(cfg, read *complianceSearchModel) {
	read.AddExchangeLocation = reconcile.KeepSet(cfg.AddExchangeLocation, read.AddExchangeLocation)
	read.AddExchangeLocationExclusion = reconcile.KeepSet(cfg.AddExchangeLocationExclusion, read.AddExchangeLocationExclusion)
	read.AddOneDriveLocation = reconcile.KeepSet(cfg.AddOneDriveLocation, read.AddOneDriveLocation)
	read.AddOneDriveLocationExclusion = reconcile.KeepSet(cfg.AddOneDriveLocationExclusion, read.AddOneDriveLocationExclusion)
	read.AddPublicFolderLocation = reconcile.KeepSet(cfg.AddPublicFolderLocation, read.AddPublicFolderLocation)
	read.AddPublicFolderLocationExclusion = reconcile.KeepSet(cfg.AddPublicFolderLocationExclusion, read.AddPublicFolderLocationExclusion)
	read.AddSharePointLocation = reconcile.KeepSet(cfg.AddSharePointLocation, read.AddSharePointLocation)
	read.AddSharePointLocationExclusion = reconcile.KeepSet(cfg.AddSharePointLocationExclusion, read.AddSharePointLocationExclusion)
	read.AllowNotFoundExchangeLocationsEnabled = reconcile.KeepBool(cfg.AllowNotFoundExchangeLocationsEnabled, read.AllowNotFoundExchangeLocationsEnabled)
	read.Case = reconcile.KeepStr(cfg.Case, read.Case)
	read.ContentMatchQuery = reconcile.KeepStr(cfg.ContentMatchQuery, read.ContentMatchQuery)
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.ExchangeLocation = reconcile.KeepSet(cfg.ExchangeLocation, read.ExchangeLocation)
	read.ExchangeLocationExclusion = reconcile.KeepSet(cfg.ExchangeLocationExclusion, read.ExchangeLocationExclusion)
	read.HoldNames = reconcile.KeepSet(cfg.HoldNames, read.HoldNames)
	read.IncludeOrgContent = reconcile.KeepBool(cfg.IncludeOrgContent, read.IncludeOrgContent)
	read.IncludeUserAppContent = reconcile.KeepBool(cfg.IncludeUserAppContent, read.IncludeUserAppContent)
	read.Language = reconcile.KeepStr(cfg.Language, read.Language)
	read.LogLevel = reconcile.KeepStr(cfg.LogLevel, read.LogLevel)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.OneDriveLocation = reconcile.KeepSet(cfg.OneDriveLocation, read.OneDriveLocation)
	read.OneDriveLocationExclusion = reconcile.KeepSet(cfg.OneDriveLocationExclusion, read.OneDriveLocationExclusion)
	read.PublicFolderLocation = reconcile.KeepSet(cfg.PublicFolderLocation, read.PublicFolderLocation)
	read.PublicFolderLocationExclusion = reconcile.KeepSet(cfg.PublicFolderLocationExclusion, read.PublicFolderLocationExclusion)
	read.RefinerNames = reconcile.KeepSet(cfg.RefinerNames, read.RefinerNames)
	read.RemoveExchangeLocation = reconcile.KeepSet(cfg.RemoveExchangeLocation, read.RemoveExchangeLocation)
	read.RemoveExchangeLocationExclusion = reconcile.KeepSet(cfg.RemoveExchangeLocationExclusion, read.RemoveExchangeLocationExclusion)
	read.RemoveOneDriveLocation = reconcile.KeepSet(cfg.RemoveOneDriveLocation, read.RemoveOneDriveLocation)
	read.RemoveOneDriveLocationExclusion = reconcile.KeepSet(cfg.RemoveOneDriveLocationExclusion, read.RemoveOneDriveLocationExclusion)
	read.RemovePublicFolderLocation = reconcile.KeepSet(cfg.RemovePublicFolderLocation, read.RemovePublicFolderLocation)
	read.RemovePublicFolderLocationExclusion = reconcile.KeepSet(cfg.RemovePublicFolderLocationExclusion, read.RemovePublicFolderLocationExclusion)
	read.RemoveSharePointLocation = reconcile.KeepSet(cfg.RemoveSharePointLocation, read.RemoveSharePointLocation)
	read.RemoveSharePointLocationExclusion = reconcile.KeepSet(cfg.RemoveSharePointLocationExclusion, read.RemoveSharePointLocationExclusion)
	read.SearchNames = reconcile.KeepSet(cfg.SearchNames, read.SearchNames)
	read.SharePointLocation = reconcile.KeepSet(cfg.SharePointLocation, read.SharePointLocation)
	read.SharePointLocationExclusion = reconcile.KeepSet(cfg.SharePointLocationExclusion, read.SharePointLocationExclusion)
	read.StatusMailRecipients = reconcile.KeepSet(cfg.StatusMailRecipients, read.StatusMailRecipients)
}
