// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &complianceNoticeResource{}
	_ resource.ResourceWithConfigure   = &complianceNoticeResource{}
	_ resource.ResourceWithImportState = &complianceNoticeResource{}
)

type complianceNoticeResource struct{ client *clients.Client }

// NewComplianceNoticeResource manages the ComplianceNotice object (New-ComplianceNotice / Get-ComplianceNotice / Set-ComplianceNotice / Remove-ComplianceNotice).
func NewComplianceNoticeResource() resource.Resource { return &complianceNoticeResource{} }

type complianceNoticeModel struct {
	ID                     types.String `tfsdk:"id"`
	Identity               types.String `tfsdk:"identity"`
	Acknowledged           types.Bool   `tfsdk:"acknowledged"`
	AcknowledgedCustodians types.Set    `tfsdk:"acknowledged_custodians"`
	AddedCustodians        types.Set    `tfsdk:"added_custodians"`
	Case                   types.String `tfsdk:"case"`
	ContentBody            types.String `tfsdk:"content_body"`
	CustodianIds           types.Set    `tfsdk:"custodian_ids"`
	From                   types.String `tfsdk:"from"`
	IsHighPriority         types.Bool   `tfsdk:"is_high_priority"`
	Name                   types.String `tfsdk:"name"`
	Subject                types.String `tfsdk:"subject"`
	Type                   types.String `tfsdk:"type"`
	UrlPattern             types.String `tfsdk:"url_pattern"`
}

func (r *complianceNoticeResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compliance_notice"
}

func (r *complianceNoticeResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the ComplianceNotice object via New-ComplianceNotice / Get-ComplianceNotice / Set-ComplianceNotice / Remove-ComplianceNotice.",
		Attributes: map[string]schema.Attribute{
			"id":                      schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"acknowledged":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Acknowledged parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"acknowledged_custodians": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AcknowledgedCustodians parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"added_custodians":        schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddedCustodians parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"case":                    schema.StringAttribute{Required: true, Description: "Maps to the -Case parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"content_body":            schema.StringAttribute{Required: true, Description: "Maps to the -ContentBody parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"custodian_ids":           schema.SetAttribute{ElementType: types.StringType, Required: true, Description: "Maps to the -CustodianIds parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.RequiresReplace()}},
			"from":                    schema.StringAttribute{Required: true, Description: "Maps to the -From parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"is_high_priority":        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsHighPriority parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"name":                    schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"subject":                 schema.StringAttribute{Required: true, Description: "Maps to the -Subject parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"type":                    schema.StringAttribute{Required: true, Description: "Maps to the -Type parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"url_pattern":             schema.StringAttribute{Required: true, Description: "Maps to the -UrlPattern parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		},
	}
}

func (r *complianceNoticeResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *complianceNoticeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan complianceNoticeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewComplianceNoticeParams{
		Case:           plan.Case.ValueString(),
		ContentBody:    plan.ContentBody.ValueString(),
		CustodianIds:   toStringSlice(ctx, plan.CustodianIds, &resp.Diagnostics),
		From:           plan.From.ValueString(),
		IsHighPriority: plan.IsHighPriority.ValueBool(),
		Name:           plan.Name.ValueString(),
		Subject:        plan.Subject.ValueString(),
		Type:           plan.Type.ValueString(),
		UrlPattern:     plan.UrlPattern.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewComplianceNotice(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-ComplianceNotice failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-ComplianceNotice returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readComplianceNotice(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *complianceNoticeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state complianceNoticeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *complianceNoticeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state complianceNoticeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetComplianceNoticeParams{}
	sp.Identity = id
	sp.Acknowledged = plan.Acknowledged.ValueBool()
	sp.AcknowledgedCustodians = toStringSlice(ctx, plan.AcknowledgedCustodians, &resp.Diagnostics)
	sp.AddedCustodians = toStringSlice(ctx, plan.AddedCustodians, &resp.Diagnostics)
	sp.IsHighPriority = plan.IsHighPriority.ValueBool()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetComplianceNotice(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-ComplianceNotice failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *complianceNoticeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state complianceNoticeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveComplianceNotice(ctx, purview.RemoveComplianceNoticeParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-ComplianceNotice failed", err.Error())
		}
	}
}

func (r *complianceNoticeResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *complianceNoticeResource) identityOf(m complianceNoticeModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *complianceNoticeResource) refresh(ctx context.Context, identity string, m *complianceNoticeModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetComplianceNotice(ctx, purview.GetComplianceNoticeParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-ComplianceNotice failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readComplianceNotice(ctx, obj, m)
	return true
}

func readComplianceNotice(ctx context.Context, obj map[string]any, m *complianceNoticeModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Acknowledged = types.BoolValue(getBool(obj, "Acknowledged"))
	m.AcknowledgedCustodians = stringSetValue(ctx, getStringSlice(obj, "AcknowledgedCustodians"))
	m.AddedCustodians = stringSetValue(ctx, getStringSlice(obj, "AddedCustodians"))
	m.Case = types.StringValue(getString(obj, "Case"))
	m.ContentBody = types.StringValue(getString(obj, "ContentBody"))
	m.CustodianIds = stringSetValue(ctx, getStringSlice(obj, "CustodianIds"))
	m.From = types.StringValue(getString(obj, "From"))
	m.IsHighPriority = types.BoolValue(getBool(obj, "IsHighPriority"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.Subject = types.StringValue(getString(obj, "Subject"))
	m.Type = types.StringValue(getString(obj, "Type"))
	m.UrlPattern = types.StringValue(getString(obj, "UrlPattern"))
	_ = ctx
}

func (r *complianceNoticeResource) reconcileState(cfg, read *complianceNoticeModel) {
	read.Acknowledged = reconcile.KeepBool(cfg.Acknowledged, read.Acknowledged)
	read.AcknowledgedCustodians = reconcile.KeepSet(cfg.AcknowledgedCustodians, read.AcknowledgedCustodians)
	read.AddedCustodians = reconcile.KeepSet(cfg.AddedCustodians, read.AddedCustodians)
	read.Case = reconcile.KeepStr(cfg.Case, read.Case)
	read.ContentBody = reconcile.KeepStr(cfg.ContentBody, read.ContentBody)
	read.CustodianIds = reconcile.KeepSet(cfg.CustodianIds, read.CustodianIds)
	read.From = reconcile.KeepStr(cfg.From, read.From)
	read.IsHighPriority = reconcile.KeepBool(cfg.IsHighPriority, read.IsHighPriority)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.Subject = reconcile.KeepStr(cfg.Subject, read.Subject)
	read.Type = reconcile.KeepStr(cfg.Type, read.Type)
	read.UrlPattern = reconcile.KeepStr(cfg.UrlPattern, read.UrlPattern)
}
