// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &complianceBoundaryListDataSource{}
	_ datasource.DataSourceWithConfigure = &complianceBoundaryListDataSource{}
)

type complianceBoundaryListDataSource struct{ client *clients.Client }

// NewComplianceBoundaryListDataSource lists every ComplianceBoundary object (Get-ComplianceBoundary).
func NewComplianceBoundaryListDataSource() datasource.DataSource {
	return &complianceBoundaryListDataSource{}
}

type complianceBoundaryListModel struct {
	Items []complianceBoundaryModel `tfsdk:"compliance_boundaries"`
}

func (d *complianceBoundaryListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compliance_boundaries"
}

func (d *complianceBoundaryListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ComplianceBoundary object (Get-ComplianceBoundary).",
		Attributes: map[string]schema.Attribute{
			"compliance_boundaries": schema.ListNestedAttribute{Computed: true, Description: "All ComplianceBoundary objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                      schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"comment":                 schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"custom_recipient_filter": schema.StringAttribute{Computed: true, Description: "Maps to the -CustomRecipientFilter parameter."},
				"name":                    schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
			}}},
		},
	}
}

func (d *complianceBoundaryListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *complianceBoundaryListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetComplianceBoundary(ctx, purview.GetComplianceBoundaryParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ComplianceBoundary failed", err.Error())
		return
	}
	var data complianceBoundaryListModel
	for _, obj := range res.Value {
		var e complianceBoundaryModel
		readComplianceBoundary(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
