// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &complianceNoticeListDataSource{}
	_ datasource.DataSourceWithConfigure = &complianceNoticeListDataSource{}
)

type complianceNoticeListDataSource struct{ client *clients.Client }

// NewComplianceNoticeListDataSource lists every ComplianceNotice object (Get-ComplianceNotice).
func NewComplianceNoticeListDataSource() datasource.DataSource {
	return &complianceNoticeListDataSource{}
}

type complianceNoticeListModel struct {
	Items []complianceNoticeModel `tfsdk:"compliance_notices"`
}

func (d *complianceNoticeListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compliance_notices"
}

func (d *complianceNoticeListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ComplianceNotice object (Get-ComplianceNotice).",
		Attributes: map[string]schema.Attribute{
			"compliance_notices": schema.ListNestedAttribute{Computed: true, Description: "All ComplianceNotice objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                      schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"acknowledged":            schema.BoolAttribute{Computed: true, Description: "Maps to the -Acknowledged parameter."},
				"acknowledged_custodians": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AcknowledgedCustodians parameter."},
				"added_custodians":        schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddedCustodians parameter."},
				"case":                    schema.StringAttribute{Computed: true, Description: "Maps to the -Case parameter."},
				"content_body":            schema.StringAttribute{Computed: true, Description: "Maps to the -ContentBody parameter."},
				"custodian_ids":           schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -CustodianIds parameter."},
				"from":                    schema.StringAttribute{Computed: true, Description: "Maps to the -From parameter."},
				"is_high_priority":        schema.BoolAttribute{Computed: true, Description: "Maps to the -IsHighPriority parameter."},
				"name":                    schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"subject":                 schema.StringAttribute{Computed: true, Description: "Maps to the -Subject parameter."},
				"type":                    schema.StringAttribute{Computed: true, Description: "Maps to the -Type parameter."},
				"url_pattern":             schema.StringAttribute{Computed: true, Description: "Maps to the -UrlPattern parameter."},
			}}},
		},
	}
}

func (d *complianceNoticeListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *complianceNoticeListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetComplianceNotice(ctx, purview.GetComplianceNoticeParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ComplianceNotice failed", err.Error())
		return
	}
	var data complianceNoticeListModel
	for _, obj := range res.Value {
		var e complianceNoticeModel
		readComplianceNotice(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
