// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &complianceSearchListDataSource{}
	_ datasource.DataSourceWithConfigure = &complianceSearchListDataSource{}
)

type complianceSearchListDataSource struct{ client *clients.Client }

// NewComplianceSearchListDataSource lists every ComplianceSearch object (Get-ComplianceSearch).
func NewComplianceSearchListDataSource() datasource.DataSource {
	return &complianceSearchListDataSource{}
}

type complianceSearchListModel struct {
	Items []complianceSearchModel `tfsdk:"compliance_searches"`
}

func (d *complianceSearchListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compliance_searches"
}

func (d *complianceSearchListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ComplianceSearch object (Get-ComplianceSearch).",
		Attributes: map[string]schema.Attribute{
			"compliance_searches": schema.ListNestedAttribute{Computed: true, Description: "All ComplianceSearch objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                                         schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                                   schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"add_exchange_location":                      schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddExchangeLocation parameter."},
				"add_exchange_location_exclusion":            schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddExchangeLocationExclusion parameter."},
				"add_one_drive_location":                     schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddOneDriveLocation parameter."},
				"add_one_drive_location_exclusion":           schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddOneDriveLocationExclusion parameter."},
				"add_public_folder_location":                 schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddPublicFolderLocation parameter."},
				"add_public_folder_location_exclusion":       schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddPublicFolderLocationExclusion parameter."},
				"add_share_point_location":                   schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddSharePointLocation parameter."},
				"add_share_point_location_exclusion":         schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddSharePointLocationExclusion parameter."},
				"allow_not_found_exchange_locations_enabled": schema.BoolAttribute{Computed: true, Description: "Maps to the -AllowNotFoundExchangeLocationsEnabled parameter."},
				"case":                                    schema.StringAttribute{Computed: true, Description: "Maps to the -Case parameter."},
				"content_match_query":                     schema.StringAttribute{Computed: true, Description: "Maps to the -ContentMatchQuery parameter."},
				"description":                             schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
				"exchange_location":                       schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ExchangeLocation parameter."},
				"exchange_location_exclusion":             schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ExchangeLocationExclusion parameter."},
				"hold_names":                              schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -HoldNames parameter."},
				"include_org_content":                     schema.BoolAttribute{Computed: true, Description: "Maps to the -IncludeOrgContent parameter."},
				"include_user_app_content":                schema.BoolAttribute{Computed: true, Description: "Maps to the -IncludeUserAppContent parameter."},
				"language":                                schema.StringAttribute{Computed: true, Description: "Maps to the -Language parameter."},
				"log_level":                               schema.StringAttribute{Computed: true, Description: "Maps to the -LogLevel parameter."},
				"name":                                    schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"one_drive_location":                      schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -OneDriveLocation parameter."},
				"one_drive_location_exclusion":            schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -OneDriveLocationExclusion parameter."},
				"public_folder_location":                  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -PublicFolderLocation parameter."},
				"public_folder_location_exclusion":        schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -PublicFolderLocationExclusion parameter."},
				"refiner_names":                           schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RefinerNames parameter."},
				"remove_exchange_location":                schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemoveExchangeLocation parameter."},
				"remove_exchange_location_exclusion":      schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemoveExchangeLocationExclusion parameter."},
				"remove_one_drive_location":               schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemoveOneDriveLocation parameter."},
				"remove_one_drive_location_exclusion":     schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemoveOneDriveLocationExclusion parameter."},
				"remove_public_folder_location":           schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemovePublicFolderLocation parameter."},
				"remove_public_folder_location_exclusion": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemovePublicFolderLocationExclusion parameter."},
				"remove_share_point_location":             schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemoveSharePointLocation parameter."},
				"remove_share_point_location_exclusion":   schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemoveSharePointLocationExclusion parameter."},
				"search_names":                            schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -SearchNames parameter."},
				"share_point_location":                    schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -SharePointLocation parameter."},
				"share_point_location_exclusion":          schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -SharePointLocationExclusion parameter."},
				"status_mail_recipients":                  schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -StatusMailRecipients parameter."},
			}}},
		},
	}
}

func (d *complianceSearchListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *complianceSearchListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetComplianceSearch(ctx, purview.GetComplianceSearchParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ComplianceSearch failed", err.Error())
		return
	}
	var data complianceSearchListModel
	for _, obj := range res.Value {
		var e complianceSearchModel
		readComplianceSearch(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
