// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &deviceConfigurationPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &deviceConfigurationPolicyListDataSource{}
)

type deviceConfigurationPolicyListDataSource struct{ client *clients.Client }

// NewDeviceConfigurationPolicyListDataSource lists every DeviceConfigurationPolicy object (Get-DeviceConfigurationPolicy).
func NewDeviceConfigurationPolicyListDataSource() datasource.DataSource {
	return &deviceConfigurationPolicyListDataSource{}
}

type deviceConfigurationPolicyListModel struct {
	Items []deviceConfigurationPolicyModel `tfsdk:"device_configuration_policies"`
}

func (d *deviceConfigurationPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_device_configuration_policies"
}

func (d *deviceConfigurationPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every DeviceConfigurationPolicy object (Get-DeviceConfigurationPolicy).",
		Attributes: map[string]schema.Attribute{
			"device_configuration_policies": schema.ListNestedAttribute{Computed: true, Description: "All DeviceConfigurationPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":           schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"comment":            schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"enabled":            schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
				"name":               schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"retry_distribution": schema.BoolAttribute{Computed: true, Description: "Maps to the -RetryDistribution parameter."},
			}}},
		},
	}
}

func (d *deviceConfigurationPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *deviceConfigurationPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetDeviceConfigurationPolicy(ctx, purview.GetDeviceConfigurationPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-DeviceConfigurationPolicy failed", err.Error())
		return
	}
	var data deviceConfigurationPolicyListModel
	for _, obj := range res.Value {
		var e deviceConfigurationPolicyModel
		readDeviceConfigurationPolicy(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
