// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &deviceTenantPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &deviceTenantPolicyListDataSource{}
)

type deviceTenantPolicyListDataSource struct{ client *clients.Client }

// NewDeviceTenantPolicyListDataSource lists every DeviceTenantPolicy object (Get-DeviceTenantPolicy).
func NewDeviceTenantPolicyListDataSource() datasource.DataSource {
	return &deviceTenantPolicyListDataSource{}
}

type deviceTenantPolicyListModel struct {
	Items []deviceTenantPolicyModel `tfsdk:"device_tenant_policies"`
}

func (d *deviceTenantPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_device_tenant_policies"
}

func (d *deviceTenantPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every DeviceTenantPolicy object (Get-DeviceTenantPolicy).",
		Attributes: map[string]schema.Attribute{
			"device_tenant_policies": schema.ListNestedAttribute{Computed: true, Description: "All DeviceTenantPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":           schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"comment":            schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"enabled":            schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
				"retry_distribution": schema.BoolAttribute{Computed: true, Description: "Maps to the -RetryDistribution parameter."},
			}}},
		},
	}
}

func (d *deviceTenantPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *deviceTenantPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetDeviceTenantPolicy(ctx, purview.GetDeviceTenantPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-DeviceTenantPolicy failed", err.Error())
		return
	}
	var data deviceTenantPolicyListModel
	for _, obj := range res.Value {
		var e deviceTenantPolicyModel
		readDeviceTenantPolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
