// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &deviceConfigurationPolicyResource{}
	_ resource.ResourceWithConfigure   = &deviceConfigurationPolicyResource{}
	_ resource.ResourceWithImportState = &deviceConfigurationPolicyResource{}
)

type deviceConfigurationPolicyResource struct{ client *clients.Client }

// NewDeviceConfigurationPolicyResource manages the DeviceConfigurationPolicy object (New-DeviceConfigurationPolicy / Get-DeviceConfigurationPolicy / Set-DeviceConfigurationPolicy / Remove-DeviceConfigurationPolicy).
func NewDeviceConfigurationPolicyResource() resource.Resource {
	return &deviceConfigurationPolicyResource{}
}

type deviceConfigurationPolicyModel struct {
	ID                types.String `tfsdk:"id"`
	Identity          types.String `tfsdk:"identity"`
	Comment           types.String `tfsdk:"comment"`
	Enabled           types.Bool   `tfsdk:"enabled"`
	Name              types.String `tfsdk:"name"`
	RetryDistribution types.Bool   `tfsdk:"retry_distribution"`
}

func (r *deviceConfigurationPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_device_configuration_policy"
}

func (r *deviceConfigurationPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the DeviceConfigurationPolicy object via New-DeviceConfigurationPolicy / Get-DeviceConfigurationPolicy / Set-DeviceConfigurationPolicy / Remove-DeviceConfigurationPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":           schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"comment":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":            schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"name":               schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"retry_distribution": schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RetryDistribution parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *deviceConfigurationPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *deviceConfigurationPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan deviceConfigurationPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewDeviceConfigurationPolicyParams{
		Comment: plan.Comment.ValueString(),
		Enabled: plan.Enabled.ValueBool(),
		Name:    plan.Name.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewDeviceConfigurationPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-DeviceConfigurationPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-DeviceConfigurationPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readDeviceConfigurationPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *deviceConfigurationPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state deviceConfigurationPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *deviceConfigurationPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state deviceConfigurationPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetDeviceConfigurationPolicyParams{}
	sp.Identity = id
	sp.Comment = plan.Comment.ValueString()
	sp.Enabled = plan.Enabled.ValueBool()
	sp.RetryDistribution = plan.RetryDistribution.ValueBool()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetDeviceConfigurationPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-DeviceConfigurationPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Comment": cfg.Comment,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *deviceConfigurationPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state deviceConfigurationPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveDeviceConfigurationPolicy(ctx, purview.RemoveDeviceConfigurationPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-DeviceConfigurationPolicy failed", err.Error())
		}
	}
}

func (r *deviceConfigurationPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *deviceConfigurationPolicyResource) identityOf(m deviceConfigurationPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *deviceConfigurationPolicyResource) refresh(ctx context.Context, identity string, m *deviceConfigurationPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetDeviceConfigurationPolicy(ctx, purview.GetDeviceConfigurationPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-DeviceConfigurationPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readDeviceConfigurationPolicy(ctx, obj, m)
	return true
}

func readDeviceConfigurationPolicy(ctx context.Context, obj map[string]any, m *deviceConfigurationPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.RetryDistribution = types.BoolValue(getBool(obj, "RetryDistribution"))
	_ = ctx
}

func (r *deviceConfigurationPolicyResource) reconcileState(cfg, read *deviceConfigurationPolicyModel) {
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.RetryDistribution = reconcile.KeepBool(cfg.RetryDistribution, read.RetryDistribution)
}
