// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &deviceTenantRuleDataSource{}
	_ datasource.DataSourceWithConfigure = &deviceTenantRuleDataSource{}
)

type deviceTenantRuleDataSource struct{ client *clients.Client }

// NewDeviceTenantRuleDataSource looks up a DeviceTenantRule object (Get-DeviceTenantRule).
func NewDeviceTenantRuleDataSource() datasource.DataSource { return &deviceTenantRuleDataSource{} }

func (d *deviceTenantRuleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_device_tenant_rule"
}

func (d *deviceTenantRuleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing DeviceTenantRule object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                        schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"apply_policy_to":           schema.StringAttribute{Computed: true, Description: "Maps to the -ApplyPolicyTo parameter."},
			"block_unsupported_devices": schema.StringAttribute{Computed: true, Description: "Maps to the -BlockUnsupportedDevices parameter."},
			"exclusion_list":            schema.StringAttribute{Computed: true, Description: "Maps to the -ExclusionList parameter."},
		},
	}
}

func (d *deviceTenantRuleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *deviceTenantRuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data deviceTenantRuleModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetDeviceTenantRule(ctx, purview.GetDeviceTenantRuleParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-DeviceTenantRule failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("DeviceTenantRule not found", "no DeviceTenantRule object for identity "+identity)
		return
	}
	readDeviceTenantRule(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
