// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &dlpSensitiveInformationTypeDataSource{}
	_ datasource.DataSourceWithConfigure = &dlpSensitiveInformationTypeDataSource{}
)

type dlpSensitiveInformationTypeDataSource struct{ client *clients.Client }

// NewDlpSensitiveInformationTypeDataSource looks up a DlpSensitiveInformationType object (Get-DlpSensitiveInformationType).
func NewDlpSensitiveInformationTypeDataSource() datasource.DataSource {
	return &dlpSensitiveInformationTypeDataSource{}
}

func (d *dlpSensitiveInformationTypeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dlp_sensitive_information_type"
}

func (d *dlpSensitiveInformationTypeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing DlpSensitiveInformationType object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":               schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":         schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"description":      schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"file_data":        schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -FileData parameter."},
			"fingerprints":     schema.StringAttribute{Computed: true, Description: "Maps to the -Fingerprints parameter."},
			"is_exact":         schema.BoolAttribute{Computed: true, Description: "Maps to the -IsExact parameter."},
			"locale":           schema.StringAttribute{Computed: true, Description: "Maps to the -Locale parameter."},
			"name":             schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"threshold":        schema.StringAttribute{Computed: true, Description: "Maps to the -Threshold parameter."},
			"threshold_config": schema.StringAttribute{Computed: true, Description: "Maps to the -ThresholdConfig parameter."},
		},
	}
}

func (d *dlpSensitiveInformationTypeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *dlpSensitiveInformationTypeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data dlpSensitiveInformationTypeModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetDlpSensitiveInformationType(ctx, purview.GetDlpSensitiveInformationTypeParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-DlpSensitiveInformationType failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("DlpSensitiveInformationType not found", "no DlpSensitiveInformationType object for identity "+identity)
		return
	}
	readDlpSensitiveInformationType(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
