// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &dlpSensitiveInformationTypeRulePackageResource{}
	_ resource.ResourceWithConfigure   = &dlpSensitiveInformationTypeRulePackageResource{}
	_ resource.ResourceWithImportState = &dlpSensitiveInformationTypeRulePackageResource{}
)

type dlpSensitiveInformationTypeRulePackageResource struct{ client *clients.Client }

// NewDlpSensitiveInformationTypeRulePackageResource manages the DlpSensitiveInformationTypeRulePackage object (New-DlpSensitiveInformationTypeRulePackage / Get-DlpSensitiveInformationTypeRulePackage / Set-DlpSensitiveInformationTypeRulePackage / Remove-DlpSensitiveInformationTypeRulePackage).
func NewDlpSensitiveInformationTypeRulePackageResource() resource.Resource {
	return &dlpSensitiveInformationTypeRulePackageResource{}
}

type dlpSensitiveInformationTypeRulePackageModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	FileData    types.Set    `tfsdk:"file_data"`
	MigrationId types.String `tfsdk:"migration_id"`
}

func (r *dlpSensitiveInformationTypeRulePackageResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dlp_sensitive_information_type_rule_package"
}

func (r *dlpSensitiveInformationTypeRulePackageResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the DlpSensitiveInformationTypeRulePackage object via New-DlpSensitiveInformationTypeRulePackage / Get-DlpSensitiveInformationTypeRulePackage / Set-DlpSensitiveInformationTypeRulePackage / Remove-DlpSensitiveInformationTypeRulePackage.",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"file_data":    schema.SetAttribute{ElementType: types.StringType, Required: true, Description: "Maps to the -FileData parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.RequiresReplace()}},
			"migration_id": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MigrationId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *dlpSensitiveInformationTypeRulePackageResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *dlpSensitiveInformationTypeRulePackageResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dlpSensitiveInformationTypeRulePackageModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewDlpSensitiveInformationTypeRulePackageParams{
		FileData:    toStringSlice(ctx, plan.FileData, &resp.Diagnostics),
		MigrationId: plan.MigrationId.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewDlpSensitiveInformationTypeRulePackage(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-DlpSensitiveInformationTypeRulePackage failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-DlpSensitiveInformationTypeRulePackage returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readDlpSensitiveInformationTypeRulePackage(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dlpSensitiveInformationTypeRulePackageResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dlpSensitiveInformationTypeRulePackageModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dlpSensitiveInformationTypeRulePackageResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dlpSensitiveInformationTypeRulePackageModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetDlpSensitiveInformationTypeRulePackageParams{}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetDlpSensitiveInformationTypeRulePackage(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-DlpSensitiveInformationTypeRulePackage failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dlpSensitiveInformationTypeRulePackageResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state dlpSensitiveInformationTypeRulePackageModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveDlpSensitiveInformationTypeRulePackage(ctx, purview.RemoveDlpSensitiveInformationTypeRulePackageParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-DlpSensitiveInformationTypeRulePackage failed", err.Error())
		}
	}
}

func (r *dlpSensitiveInformationTypeRulePackageResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *dlpSensitiveInformationTypeRulePackageResource) identityOf(m dlpSensitiveInformationTypeRulePackageModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return ""
}

func (r *dlpSensitiveInformationTypeRulePackageResource) refresh(ctx context.Context, identity string, m *dlpSensitiveInformationTypeRulePackageModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetDlpSensitiveInformationTypeRulePackage(ctx, purview.GetDlpSensitiveInformationTypeRulePackageParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-DlpSensitiveInformationTypeRulePackage failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readDlpSensitiveInformationTypeRulePackage(ctx, obj, m)
	return true
}

func readDlpSensitiveInformationTypeRulePackage(ctx context.Context, obj map[string]any, m *dlpSensitiveInformationTypeRulePackageModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.FileData = stringSetValue(ctx, getStringSlice(obj, "FileData"))
	m.MigrationId = types.StringValue(getString(obj, "MigrationId"))
	_ = ctx
}

func (r *dlpSensitiveInformationTypeRulePackageResource) reconcileState(cfg, read *dlpSensitiveInformationTypeRulePackageModel) {
	read.FileData = reconcile.KeepSet(cfg.FileData, read.FileData)
	read.MigrationId = reconcile.KeepStr(cfg.MigrationId, read.MigrationId)
}
