// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &dspmPolicyResource{}
	_ resource.ResourceWithConfigure   = &dspmPolicyResource{}
	_ resource.ResourceWithImportState = &dspmPolicyResource{}
)

type dspmPolicyResource struct{ client *clients.Client }

// NewDspmPolicyResource manages the DspmPolicy object (New-DspmPolicy / Get-DspmPolicy / Set-DspmPolicy / Remove-DspmPolicy).
func NewDspmPolicyResource() resource.Resource { return &dspmPolicyResource{} }

type dspmPolicyModel struct {
	ID            types.String `tfsdk:"id"`
	Identity      types.String `tfsdk:"identity"`
	Enabled       types.Bool   `tfsdk:"enabled"`
	Name          types.String `tfsdk:"name"`
	TenantSetting types.String `tfsdk:"tenant_setting"`
}

func (r *dspmPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dspm_policy"
}

func (r *dspmPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the DspmPolicy object via New-DspmPolicy / Get-DspmPolicy / Set-DspmPolicy / Remove-DspmPolicy.",
		Attributes: map[string]schema.Attribute{
			"id":             schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":       schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"enabled":        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"name":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"tenant_setting": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TenantSetting parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *dspmPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *dspmPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dspmPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewDspmPolicyParams{
		Enabled:       plan.Enabled.ValueBool(),
		Name:          plan.Name.ValueString(),
		TenantSetting: plan.TenantSetting.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewDspmPolicy(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-DspmPolicy failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-DspmPolicy returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readDspmPolicy(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dspmPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dspmPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dspmPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dspmPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetDspmPolicyParams{}
	sp.Identity = id
	sp.Enabled = plan.Enabled.ValueBool()
	sp.TenantSetting = plan.TenantSetting.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetDspmPolicy(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-DspmPolicy failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"TenantSetting": cfg.TenantSetting,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dspmPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state dspmPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveDspmPolicy(ctx, purview.RemoveDspmPolicyParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-DspmPolicy failed", err.Error())
		}
	}
}

func (r *dspmPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *dspmPolicyResource) identityOf(m dspmPolicyModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *dspmPolicyResource) refresh(ctx context.Context, identity string, m *dspmPolicyModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetDspmPolicy(ctx, purview.GetDspmPolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-DspmPolicy failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readDspmPolicy(ctx, obj, m)
	return true
}

func readDspmPolicy(ctx context.Context, obj map[string]any, m *dspmPolicyModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.TenantSetting = types.StringValue(getString(obj, "TenantSetting"))
	_ = ctx
}

func (r *dspmPolicyResource) reconcileState(cfg, read *dspmPolicyModel) {
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.TenantSetting = reconcile.KeepStr(cfg.TenantSetting, read.TenantSetting)
}
