// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &featureConfigurationDataSource{}
	_ datasource.DataSourceWithConfigure = &featureConfigurationDataSource{}
)

type featureConfigurationDataSource struct{ client *clients.Client }

// NewFeatureConfigurationDataSource looks up a FeatureConfiguration object (Get-FeatureConfiguration).
func NewFeatureConfigurationDataSource() datasource.DataSource {
	return &featureConfigurationDataSource{}
}

func (d *featureConfigurationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_feature_configuration"
}

func (d *featureConfigurationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing FeatureConfiguration object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":           schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"comment":            schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"feature_scenario":   schema.StringAttribute{Computed: true, Description: "Maps to the -FeatureScenario parameter."},
			"locations":          schema.StringAttribute{Computed: true, Description: "Maps to the -Locations parameter."},
			"mode":               schema.StringAttribute{Computed: true, Description: "Maps to the -Mode parameter."},
			"name":               schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"policy_rbac_scopes": schema.StringAttribute{Computed: true, Description: "Maps to the -PolicyRBACScopes parameter."},
			"scenario_config":    schema.StringAttribute{Computed: true, Description: "Maps to the -ScenarioConfig parameter."},
		},
	}
}

func (d *featureConfigurationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *featureConfigurationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data featureConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetFeatureConfiguration(ctx, purview.GetFeatureConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-FeatureConfiguration failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("FeatureConfiguration not found", "no FeatureConfiguration object for identity "+identity)
		return
	}
	readFeatureConfiguration(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
