// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &featureConfigurationResource{}
	_ resource.ResourceWithConfigure   = &featureConfigurationResource{}
	_ resource.ResourceWithImportState = &featureConfigurationResource{}
)

type featureConfigurationResource struct{ client *clients.Client }

// NewFeatureConfigurationResource manages the FeatureConfiguration object (New-FeatureConfiguration / Get-FeatureConfiguration / Set-FeatureConfiguration / Remove-FeatureConfiguration).
func NewFeatureConfigurationResource() resource.Resource { return &featureConfigurationResource{} }

type featureConfigurationModel struct {
	ID               types.String `tfsdk:"id"`
	Identity         types.String `tfsdk:"identity"`
	Comment          types.String `tfsdk:"comment"`
	FeatureScenario  types.String `tfsdk:"feature_scenario"`
	Locations        types.String `tfsdk:"locations"`
	Mode             types.String `tfsdk:"mode"`
	Name             types.String `tfsdk:"name"`
	PolicyRBACScopes types.String `tfsdk:"policy_rbac_scopes"`
	ScenarioConfig   types.String `tfsdk:"scenario_config"`
}

func (r *featureConfigurationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_feature_configuration"
}

func (r *featureConfigurationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the FeatureConfiguration object via New-FeatureConfiguration / Get-FeatureConfiguration / Set-FeatureConfiguration / Remove-FeatureConfiguration.",
		Attributes: map[string]schema.Attribute{
			"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":           schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"comment":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"feature_scenario":   schema.StringAttribute{Required: true, Description: "Maps to the -FeatureScenario parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"locations":          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Locations parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"mode":               schema.StringAttribute{Required: true, Description: "Maps to the -Mode parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"name":               schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"policy_rbac_scopes": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PolicyRBACScopes parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"scenario_config":    schema.StringAttribute{Required: true, Description: "Maps to the -ScenarioConfig parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		},
	}
}

func (r *featureConfigurationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *featureConfigurationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan featureConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewFeatureConfigurationParams{
		Comment:        plan.Comment.ValueString(),
		Locations:      plan.Locations.ValueString(),
		Name:           plan.Name.ValueString(),
		ScenarioConfig: plan.ScenarioConfig.ValueString(),
	}
	if v := plan.FeatureScenario.ValueString(); v != "" {
		p.FeatureScenario = v
	}
	if v := plan.Mode.ValueString(); v != "" {
		p.Mode = v
	}
	if v := plan.PolicyRBACScopes.ValueString(); v != "" {
		p.PolicyRBACScopes = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewFeatureConfiguration(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-FeatureConfiguration failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-FeatureConfiguration returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readFeatureConfiguration(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *featureConfigurationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state featureConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *featureConfigurationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state featureConfigurationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetFeatureConfigurationParams{}
	sp.Identity = id
	sp.Comment = plan.Comment.ValueString()
	sp.Locations = plan.Locations.ValueString()
	if v := plan.PolicyRBACScopes.ValueString(); v != "" {
		sp.PolicyRBACScopes = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetFeatureConfiguration(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-FeatureConfiguration failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Comment":          cfg.Comment,
		"Locations":        cfg.Locations,
		"PolicyRBACScopes": cfg.PolicyRBACScopes,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *featureConfigurationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state featureConfigurationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveFeatureConfiguration(ctx, purview.RemoveFeatureConfigurationParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-FeatureConfiguration failed", err.Error())
		}
	}
}

func (r *featureConfigurationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *featureConfigurationResource) identityOf(m featureConfigurationModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *featureConfigurationResource) refresh(ctx context.Context, identity string, m *featureConfigurationModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetFeatureConfiguration(ctx, purview.GetFeatureConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-FeatureConfiguration failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readFeatureConfiguration(ctx, obj, m)
	return true
}

func readFeatureConfiguration(ctx context.Context, obj map[string]any, m *featureConfigurationModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.FeatureScenario = types.StringValue(getString(obj, "FeatureScenario"))
	m.Locations = types.StringValue(getString(obj, "Locations"))
	m.Mode = types.StringValue(getString(obj, "Mode"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.PolicyRBACScopes = types.StringValue(getString(obj, "PolicyRBACScopes"))
	m.ScenarioConfig = types.StringValue(getString(obj, "ScenarioConfig"))
	_ = ctx
}

func (r *featureConfigurationResource) reconcileState(cfg, read *featureConfigurationModel) {
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.FeatureScenario = reconcile.KeepStr(cfg.FeatureScenario, read.FeatureScenario)
	read.Locations = reconcile.KeepStr(cfg.Locations, read.Locations)
	read.Mode = reconcile.KeepStr(cfg.Mode, read.Mode)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.PolicyRBACScopes = reconcile.KeepStr(cfg.PolicyRBACScopes, read.PolicyRBACScopes)
	read.ScenarioConfig = reconcile.KeepStr(cfg.ScenarioConfig, read.ScenarioConfig)
}
