// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &filePlanPropertyDepartmentResource{}
	_ resource.ResourceWithConfigure   = &filePlanPropertyDepartmentResource{}
	_ resource.ResourceWithImportState = &filePlanPropertyDepartmentResource{}
)

type filePlanPropertyDepartmentResource struct{ client *clients.Client }

// NewFilePlanPropertyDepartmentResource manages the FilePlanPropertyDepartment object (New-FilePlanPropertyDepartment / Get-FilePlanPropertyDepartment / Set-FilePlanPropertyDepartment / Remove-FilePlanPropertyDepartment).
func NewFilePlanPropertyDepartmentResource() resource.Resource {
	return &filePlanPropertyDepartmentResource{}
}

type filePlanPropertyDepartmentModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	DisplayName types.String `tfsdk:"display_name"`
	Name        types.String `tfsdk:"name"`
}

func (r *filePlanPropertyDepartmentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_file_plan_property_department"
}

func (r *filePlanPropertyDepartmentResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the FilePlanPropertyDepartment object via New-FilePlanPropertyDepartment / Get-FilePlanPropertyDepartment / Set-FilePlanPropertyDepartment / Remove-FilePlanPropertyDepartment.",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"display_name": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DisplayName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":         schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		},
	}
}

func (r *filePlanPropertyDepartmentResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *filePlanPropertyDepartmentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan filePlanPropertyDepartmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewFilePlanPropertyDepartmentParams{
		Name: plan.Name.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewFilePlanPropertyDepartment(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-FilePlanPropertyDepartment failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-FilePlanPropertyDepartment returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readFilePlanPropertyDepartment(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *filePlanPropertyDepartmentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state filePlanPropertyDepartmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *filePlanPropertyDepartmentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state filePlanPropertyDepartmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetFilePlanPropertyDepartmentParams{}
	sp.Identity = id
	sp.DisplayName = plan.DisplayName.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetFilePlanPropertyDepartment(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-FilePlanPropertyDepartment failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"DisplayName": cfg.DisplayName,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *filePlanPropertyDepartmentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state filePlanPropertyDepartmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveFilePlanPropertyDepartment(ctx, purview.RemoveFilePlanPropertyDepartmentParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-FilePlanPropertyDepartment failed", err.Error())
		}
	}
}

func (r *filePlanPropertyDepartmentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *filePlanPropertyDepartmentResource) identityOf(m filePlanPropertyDepartmentModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *filePlanPropertyDepartmentResource) refresh(ctx context.Context, identity string, m *filePlanPropertyDepartmentModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetFilePlanPropertyDepartment(ctx, purview.GetFilePlanPropertyDepartmentParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-FilePlanPropertyDepartment failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readFilePlanPropertyDepartment(ctx, obj, m)
	return true
}

func readFilePlanPropertyDepartment(ctx context.Context, obj map[string]any, m *filePlanPropertyDepartmentModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.DisplayName = types.StringValue(getString(obj, "DisplayName"))
	m.Name = types.StringValue(getString(obj, "Name"))
	_ = ctx
}

func (r *filePlanPropertyDepartmentResource) reconcileState(cfg, read *filePlanPropertyDepartmentModel) {
	read.DisplayName = reconcile.KeepStr(cfg.DisplayName, read.DisplayName)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
}
