// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &filePlanPropertyDepartmentListDataSource{}
	_ datasource.DataSourceWithConfigure = &filePlanPropertyDepartmentListDataSource{}
)

type filePlanPropertyDepartmentListDataSource struct{ client *clients.Client }

// NewFilePlanPropertyDepartmentListDataSource lists every FilePlanPropertyDepartment object (Get-FilePlanPropertyDepartment).
func NewFilePlanPropertyDepartmentListDataSource() datasource.DataSource {
	return &filePlanPropertyDepartmentListDataSource{}
}

type filePlanPropertyDepartmentListModel struct {
	Items []filePlanPropertyDepartmentModel `tfsdk:"file_plan_property_departments"`
}

func (d *filePlanPropertyDepartmentListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_file_plan_property_departments"
}

func (d *filePlanPropertyDepartmentListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every FilePlanPropertyDepartment object (Get-FilePlanPropertyDepartment).",
		Attributes: map[string]schema.Attribute{
			"file_plan_property_departments": schema.ListNestedAttribute{Computed: true, Description: "All FilePlanPropertyDepartment objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"display_name": schema.StringAttribute{Computed: true, Description: "Maps to the -DisplayName parameter."},
				"name":         schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
			}}},
		},
	}
}

func (d *filePlanPropertyDepartmentListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *filePlanPropertyDepartmentListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetFilePlanPropertyDepartment(ctx, purview.GetFilePlanPropertyDepartmentParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-FilePlanPropertyDepartment failed", err.Error())
		return
	}
	var data filePlanPropertyDepartmentListModel
	for _, obj := range res.Value {
		var e filePlanPropertyDepartmentModel
		readFilePlanPropertyDepartment(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
