// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &filePlanPropertyCategoryResource{}
	_ resource.ResourceWithConfigure   = &filePlanPropertyCategoryResource{}
	_ resource.ResourceWithImportState = &filePlanPropertyCategoryResource{}
)

type filePlanPropertyCategoryResource struct{ client *clients.Client }

// NewFilePlanPropertyCategoryResource manages the FilePlanPropertyCategory object (New-FilePlanPropertyCategory / Get-FilePlanPropertyCategory / Set-FilePlanPropertyCategory / Remove-FilePlanPropertyCategory).
func NewFilePlanPropertyCategoryResource() resource.Resource {
	return &filePlanPropertyCategoryResource{}
}

type filePlanPropertyCategoryModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	DisplayName types.String `tfsdk:"display_name"`
	Name        types.String `tfsdk:"name"`
}

func (r *filePlanPropertyCategoryResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_file_plan_property_category"
}

func (r *filePlanPropertyCategoryResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the FilePlanPropertyCategory object via New-FilePlanPropertyCategory / Get-FilePlanPropertyCategory / Set-FilePlanPropertyCategory / Remove-FilePlanPropertyCategory.",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"display_name": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DisplayName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":         schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		},
	}
}

func (r *filePlanPropertyCategoryResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *filePlanPropertyCategoryResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan filePlanPropertyCategoryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewFilePlanPropertyCategoryParams{
		Name: plan.Name.ValueString(),
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewFilePlanPropertyCategory(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-FilePlanPropertyCategory failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-FilePlanPropertyCategory returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readFilePlanPropertyCategory(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *filePlanPropertyCategoryResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state filePlanPropertyCategoryModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *filePlanPropertyCategoryResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state filePlanPropertyCategoryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetFilePlanPropertyCategoryParams{}
	sp.Identity = id
	sp.DisplayName = plan.DisplayName.ValueString()
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetFilePlanPropertyCategory(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-FilePlanPropertyCategory failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"DisplayName": cfg.DisplayName,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *filePlanPropertyCategoryResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state filePlanPropertyCategoryModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveFilePlanPropertyCategory(ctx, purview.RemoveFilePlanPropertyCategoryParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-FilePlanPropertyCategory failed", err.Error())
		}
	}
}

func (r *filePlanPropertyCategoryResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *filePlanPropertyCategoryResource) identityOf(m filePlanPropertyCategoryModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *filePlanPropertyCategoryResource) refresh(ctx context.Context, identity string, m *filePlanPropertyCategoryModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetFilePlanPropertyCategory(ctx, purview.GetFilePlanPropertyCategoryParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-FilePlanPropertyCategory failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readFilePlanPropertyCategory(ctx, obj, m)
	return true
}

func readFilePlanPropertyCategory(ctx context.Context, obj map[string]any, m *filePlanPropertyCategoryModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.DisplayName = types.StringValue(getString(obj, "DisplayName"))
	m.Name = types.StringValue(getString(obj, "Name"))
	_ = ctx
}

func (r *filePlanPropertyCategoryResource) reconcileState(cfg, read *filePlanPropertyCategoryModel) {
	read.DisplayName = reconcile.KeepStr(cfg.DisplayName, read.DisplayName)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
}
