// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &globalListResource{}
	_ resource.ResourceWithConfigure   = &globalListResource{}
	_ resource.ResourceWithImportState = &globalListResource{}
)

type globalListResource struct{ client *clients.Client }

// NewGlobalListResource manages the GlobalList object (New-GlobalList / Get-GlobalList / Set-GlobalList / Remove-GlobalList).
func NewGlobalListResource() resource.Resource { return &globalListResource{} }

type globalListModel struct {
	ID              types.String `tfsdk:"id"`
	Identity        types.String `tfsdk:"identity"`
	AddItems        types.String `tfsdk:"add_items"`
	Comment         types.String `tfsdk:"comment"`
	GlobalListType  types.String `tfsdk:"global_list_type"`
	GlobalListValue types.String `tfsdk:"global_list_value"`
	Name            types.String `tfsdk:"name"`
	Organization    types.String `tfsdk:"organization"`
	RemoveItems     types.String `tfsdk:"remove_items"`
}

func (r *globalListResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_global_list"
}

func (r *globalListResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the GlobalList object via New-GlobalList / Get-GlobalList / Set-GlobalList / Remove-GlobalList.",
		Attributes: map[string]schema.Attribute{
			"id":                schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":          schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"add_items":         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AddItems parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comment":           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"global_list_type":  schema.StringAttribute{Required: true, Description: "Maps to the -GlobalListType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"global_list_value": schema.StringAttribute{Required: true, Description: "Maps to the -GlobalListValue parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"name":              schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"organization":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Organization parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"remove_items":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveItems parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *globalListResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *globalListResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan globalListModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewGlobalListParams{
		Comment: plan.Comment.ValueString(),
		Name:    plan.Name.ValueString(),
	}
	if v := plan.GlobalListType.ValueString(); v != "" {
		p.GlobalListType = v
	}
	if v := plan.GlobalListValue.ValueString(); v != "" {
		p.GlobalListValue = v
	}
	if v := plan.Organization.ValueString(); v != "" {
		p.Organization = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewGlobalList(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-GlobalList failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-GlobalList returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readGlobalList(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *globalListResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state globalListModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *globalListResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state globalListModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetGlobalListParams{}
	sp.Identity = id
	if v := plan.AddItems.ValueString(); v != "" {
		sp.AddItems = v
	}
	sp.Comment = plan.Comment.ValueString()
	if v := plan.RemoveItems.ValueString(); v != "" {
		sp.RemoveItems = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetGlobalList(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-GlobalList failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AddItems":    cfg.AddItems,
		"Comment":     cfg.Comment,
		"RemoveItems": cfg.RemoveItems,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *globalListResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state globalListModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveGlobalList(ctx, purview.RemoveGlobalListParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-GlobalList failed", err.Error())
		}
	}
}

func (r *globalListResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *globalListResource) identityOf(m globalListModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *globalListResource) refresh(ctx context.Context, identity string, m *globalListModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetGlobalList(ctx, purview.GetGlobalListParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-GlobalList failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readGlobalList(ctx, obj, m)
	return true
}

func readGlobalList(ctx context.Context, obj map[string]any, m *globalListModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AddItems = types.StringValue(getString(obj, "AddItems"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.GlobalListType = types.StringValue(getString(obj, "GlobalListType"))
	m.GlobalListValue = types.StringValue(getString(obj, "GlobalListValue"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.Organization = types.StringValue(getString(obj, "Organization"))
	m.RemoveItems = types.StringValue(getString(obj, "RemoveItems"))
	_ = ctx
}

func (r *globalListResource) reconcileState(cfg, read *globalListModel) {
	read.AddItems = reconcile.KeepStr(cfg.AddItems, read.AddItems)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.GlobalListType = reconcile.KeepStr(cfg.GlobalListType, read.GlobalListType)
	read.GlobalListValue = reconcile.KeepStr(cfg.GlobalListValue, read.GlobalListValue)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.Organization = reconcile.KeepStr(cfg.Organization, read.Organization)
	read.RemoveItems = reconcile.KeepStr(cfg.RemoveItems, read.RemoveItems)
}
