// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &globalListListDataSource{}
	_ datasource.DataSourceWithConfigure = &globalListListDataSource{}
)

type globalListListDataSource struct{ client *clients.Client }

// NewGlobalListListDataSource lists every GlobalList object (Get-GlobalList).
func NewGlobalListListDataSource() datasource.DataSource { return &globalListListDataSource{} }

type globalListListModel struct {
	Items []globalListModel `tfsdk:"global_lists"`
}

func (d *globalListListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_global_lists"
}

func (d *globalListListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every GlobalList object (Get-GlobalList).",
		Attributes: map[string]schema.Attribute{
			"global_lists": schema.ListNestedAttribute{Computed: true, Description: "All GlobalList objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":          schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"add_items":         schema.StringAttribute{Computed: true, Description: "Maps to the -AddItems parameter."},
				"comment":           schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"global_list_type":  schema.StringAttribute{Computed: true, Description: "Maps to the -GlobalListType parameter."},
				"global_list_value": schema.StringAttribute{Computed: true, Description: "Maps to the -GlobalListValue parameter."},
				"name":              schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"organization":      schema.StringAttribute{Computed: true, Description: "Maps to the -Organization parameter."},
				"remove_items":      schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveItems parameter."},
			}}},
		},
	}
}

func (d *globalListListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *globalListListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetGlobalList(ctx, purview.GetGlobalListParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-GlobalList failed", err.Error())
		return
	}
	var data globalListListModel
	for _, obj := range res.Value {
		var e globalListModel
		readGlobalList(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
