// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &holdCompliancePolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &holdCompliancePolicyListDataSource{}
)

type holdCompliancePolicyListDataSource struct{ client *clients.Client }

// NewHoldCompliancePolicyListDataSource lists every HoldCompliancePolicy object (Get-HoldCompliancePolicy).
func NewHoldCompliancePolicyListDataSource() datasource.DataSource {
	return &holdCompliancePolicyListDataSource{}
}

type holdCompliancePolicyListModel struct {
	Items []holdCompliancePolicyModel `tfsdk:"hold_compliance_policies"`
}

func (d *holdCompliancePolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_hold_compliance_policies"
}

func (d *holdCompliancePolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every HoldCompliancePolicy object (Get-HoldCompliancePolicy).",
		Attributes: map[string]schema.Attribute{
			"hold_compliance_policies": schema.ListNestedAttribute{Computed: true, Description: "All HoldCompliancePolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                            schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                      schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"add_exchange_location":         schema.StringAttribute{Computed: true, Description: "Maps to the -AddExchangeLocation parameter."},
				"add_public_folder_location":    schema.StringAttribute{Computed: true, Description: "Maps to the -AddPublicFolderLocation parameter."},
				"add_share_point_location":      schema.StringAttribute{Computed: true, Description: "Maps to the -AddSharePointLocation parameter."},
				"comment":                       schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"enabled":                       schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
				"exchange_location":             schema.StringAttribute{Computed: true, Description: "Maps to the -ExchangeLocation parameter."},
				"name":                          schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"public_folder_location":        schema.StringAttribute{Computed: true, Description: "Maps to the -PublicFolderLocation parameter."},
				"remove_exchange_location":      schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveExchangeLocation parameter."},
				"remove_public_folder_location": schema.StringAttribute{Computed: true, Description: "Maps to the -RemovePublicFolderLocation parameter."},
				"remove_share_point_location":   schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveSharePointLocation parameter."},
				"retry_distribution":            schema.BoolAttribute{Computed: true, Description: "Maps to the -RetryDistribution parameter."},
				"share_point_location":          schema.StringAttribute{Computed: true, Description: "Maps to the -SharePointLocation parameter."},
			}}},
		},
	}
}

func (d *holdCompliancePolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *holdCompliancePolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetHoldCompliancePolicy(ctx, purview.GetHoldCompliancePolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-HoldCompliancePolicy failed", err.Error())
		return
	}
	var data holdCompliancePolicyListModel
	for _, obj := range res.Value {
		var e holdCompliancePolicyModel
		readHoldCompliancePolicy(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
