// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &holdCompliancePolicyDataSource{}
	_ datasource.DataSourceWithConfigure = &holdCompliancePolicyDataSource{}
)

type holdCompliancePolicyDataSource struct{ client *clients.Client }

// NewHoldCompliancePolicyDataSource looks up a HoldCompliancePolicy object (Get-HoldCompliancePolicy).
func NewHoldCompliancePolicyDataSource() datasource.DataSource {
	return &holdCompliancePolicyDataSource{}
}

func (d *holdCompliancePolicyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_hold_compliance_policy"
}

func (d *holdCompliancePolicyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing HoldCompliancePolicy object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                            schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"add_exchange_location":         schema.StringAttribute{Computed: true, Description: "Maps to the -AddExchangeLocation parameter."},
			"add_public_folder_location":    schema.StringAttribute{Computed: true, Description: "Maps to the -AddPublicFolderLocation parameter."},
			"add_share_point_location":      schema.StringAttribute{Computed: true, Description: "Maps to the -AddSharePointLocation parameter."},
			"comment":                       schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"enabled":                       schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
			"exchange_location":             schema.StringAttribute{Computed: true, Description: "Maps to the -ExchangeLocation parameter."},
			"name":                          schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"public_folder_location":        schema.StringAttribute{Computed: true, Description: "Maps to the -PublicFolderLocation parameter."},
			"remove_exchange_location":      schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveExchangeLocation parameter."},
			"remove_public_folder_location": schema.StringAttribute{Computed: true, Description: "Maps to the -RemovePublicFolderLocation parameter."},
			"remove_share_point_location":   schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveSharePointLocation parameter."},
			"retry_distribution":            schema.BoolAttribute{Computed: true, Description: "Maps to the -RetryDistribution parameter."},
			"share_point_location":          schema.StringAttribute{Computed: true, Description: "Maps to the -SharePointLocation parameter."},
		},
	}
}

func (d *holdCompliancePolicyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *holdCompliancePolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data holdCompliancePolicyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetHoldCompliancePolicy(ctx, purview.GetHoldCompliancePolicyParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-HoldCompliancePolicy failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("HoldCompliancePolicy not found", "no HoldCompliancePolicy object for identity "+identity)
		return
	}
	readHoldCompliancePolicy(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
