// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &informationBarrierPolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &informationBarrierPolicyListDataSource{}
)

type informationBarrierPolicyListDataSource struct{ client *clients.Client }

// NewInformationBarrierPolicyListDataSource lists every InformationBarrierPolicy object (Get-InformationBarrierPolicy).
func NewInformationBarrierPolicyListDataSource() datasource.DataSource {
	return &informationBarrierPolicyListDataSource{}
}

type informationBarrierPolicyListModel struct {
	Items []informationBarrierPolicyModel `tfsdk:"information_barrier_policies"`
}

func (d *informationBarrierPolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_information_barrier_policies"
}

func (d *informationBarrierPolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every InformationBarrierPolicy object (Get-InformationBarrierPolicy).",
		Attributes: map[string]schema.Attribute{
			"information_barrier_policies": schema.ListNestedAttribute{Computed: true, Description: "All InformationBarrierPolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":               schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"assigned_segment":       schema.StringAttribute{Computed: true, Description: "Maps to the -AssignedSegment parameter."},
				"comment":                schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"moderation_allowed":     schema.BoolAttribute{Computed: true, Description: "Maps to the -ModerationAllowed parameter."},
				"name":                   schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"segment_allowed_filter": schema.StringAttribute{Computed: true, Description: "Maps to the -SegmentAllowedFilter parameter."},
				"segments_allowed":       schema.StringAttribute{Computed: true, Description: "Maps to the -SegmentsAllowed parameter."},
				"segments_blocked":       schema.StringAttribute{Computed: true, Description: "Maps to the -SegmentsBlocked parameter."},
				"state":                  schema.StringAttribute{Computed: true, Description: "Maps to the -State parameter."},
			}}},
		},
	}
}

func (d *informationBarrierPolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *informationBarrierPolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetInformationBarrierPolicy(ctx, purview.GetInformationBarrierPolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-InformationBarrierPolicy failed", err.Error())
		return
	}
	var data informationBarrierPolicyListModel
	for _, obj := range res.Value {
		var e informationBarrierPolicyModel
		readInformationBarrierPolicy(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
