// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &jitConfigurationDataSource{}
	_ datasource.DataSourceWithConfigure = &jitConfigurationDataSource{}
)

type jitConfigurationDataSource struct{ client *clients.Client }

// NewJitConfigurationDataSource looks up a JitConfiguration object (Get-JitConfiguration).
func NewJitConfigurationDataSource() datasource.DataSource { return &jitConfigurationDataSource{} }

func (d *jitConfigurationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_jit_configuration"
}

func (d *jitConfigurationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing JitConfiguration object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                      schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"add_endpoint_dlp_location":               schema.StringAttribute{Computed: true, Description: "Maps to the -AddEndpointDlpLocation parameter."},
			"add_endpoint_dlp_location_exception":     schema.StringAttribute{Computed: true, Description: "Maps to the -AddEndpointDlpLocationException parameter."},
			"add_one_drive_location":                  schema.StringAttribute{Computed: true, Description: "Maps to the -AddOneDriveLocation parameter."},
			"add_one_drive_location_exception":        schema.StringAttribute{Computed: true, Description: "Maps to the -AddOneDriveLocationException parameter."},
			"add_share_point_location":                schema.StringAttribute{Computed: true, Description: "Maps to the -AddSharePointLocation parameter."},
			"add_share_point_location_exception":      schema.StringAttribute{Computed: true, Description: "Maps to the -AddSharePointLocationException parameter."},
			"comment":                                 schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"endpoint_config":                         schema.StringAttribute{Computed: true, Description: "Maps to the -EndpointConfig parameter."},
			"endpoint_dlp_location":                   schema.StringAttribute{Computed: true, Description: "Maps to the -EndpointDlpLocation parameter."},
			"endpoint_dlp_location_exception":         schema.StringAttribute{Computed: true, Description: "Maps to the -EndpointDlpLocationException parameter."},
			"except_if_one_drive_shared_by":           schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ExceptIfOneDriveSharedBy parameter."},
			"except_if_one_drive_shared_by_member_of": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ExceptIfOneDriveSharedByMemberOf parameter."},
			"mode":                                   schema.StringAttribute{Computed: true, Description: "Maps to the -Mode parameter."},
			"name":                                   schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"one_drive_location":                     schema.StringAttribute{Computed: true, Description: "Maps to the -OneDriveLocation parameter."},
			"one_drive_location_exception":           schema.StringAttribute{Computed: true, Description: "Maps to the -OneDriveLocationException parameter."},
			"one_drive_shared_by":                    schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -OneDriveSharedBy parameter."},
			"one_drive_shared_by_member_of":          schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -OneDriveSharedByMemberOf parameter."},
			"organization":                           schema.StringAttribute{Computed: true, Description: "Maps to the -Organization parameter."},
			"remove_endpoint_dlp_location":           schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveEndpointDlpLocation parameter."},
			"remove_endpoint_dlp_location_exception": schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveEndpointDlpLocationException parameter."},
			"remove_one_drive_location":              schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveOneDriveLocation parameter."},
			"remove_one_drive_location_exception":    schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveOneDriveLocationException parameter."},
			"remove_share_point_location":            schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveSharePointLocation parameter."},
			"remove_share_point_location_exception":  schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveSharePointLocationException parameter."},
			"share_point_location":                   schema.StringAttribute{Computed: true, Description: "Maps to the -SharePointLocation parameter."},
			"share_point_location_exception":         schema.StringAttribute{Computed: true, Description: "Maps to the -SharePointLocationException parameter."},
		},
	}
}

func (d *jitConfigurationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *jitConfigurationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data jitConfigurationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetJitConfiguration(ctx, purview.GetJitConfigurationParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-JitConfiguration failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("JitConfiguration not found", "no JitConfiguration object for identity "+identity)
		return
	}
	readJitConfiguration(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
