// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &labelResource{}
	_ resource.ResourceWithConfigure   = &labelResource{}
	_ resource.ResourceWithImportState = &labelResource{}
)

type labelResource struct{ client *clients.Client }

// NewLabelResource manages the Label object (New-Label / Get-Label / Set-Label / Remove-Label).
func NewLabelResource() resource.Resource { return &labelResource{} }

type labelModel struct {
	ID                                                    types.String `tfsdk:"id"`
	Identity                                              types.String `tfsdk:"identity"`
	AbacEnabled                                           types.String `tfsdk:"abac_enabled"`
	AdvancedSettings                                      types.String `tfsdk:"advanced_settings"`
	ApplyContentMarkingFooterAlignment                    types.String `tfsdk:"apply_content_marking_footer_alignment"`
	ApplyContentMarkingFooterEnabled                      types.String `tfsdk:"apply_content_marking_footer_enabled"`
	ApplyContentMarkingFooterFontColor                    types.String `tfsdk:"apply_content_marking_footer_font_color"`
	ApplyContentMarkingFooterFontName                     types.String `tfsdk:"apply_content_marking_footer_font_name"`
	ApplyContentMarkingFooterFontSize                     types.String `tfsdk:"apply_content_marking_footer_font_size"`
	ApplyContentMarkingFooterMargin                       types.String `tfsdk:"apply_content_marking_footer_margin"`
	ApplyContentMarkingFooterText                         types.String `tfsdk:"apply_content_marking_footer_text"`
	ApplyContentMarkingHeaderAlignment                    types.String `tfsdk:"apply_content_marking_header_alignment"`
	ApplyContentMarkingHeaderEnabled                      types.String `tfsdk:"apply_content_marking_header_enabled"`
	ApplyContentMarkingHeaderFontColor                    types.String `tfsdk:"apply_content_marking_header_font_color"`
	ApplyContentMarkingHeaderFontName                     types.String `tfsdk:"apply_content_marking_header_font_name"`
	ApplyContentMarkingHeaderFontSize                     types.String `tfsdk:"apply_content_marking_header_font_size"`
	ApplyContentMarkingHeaderMargin                       types.String `tfsdk:"apply_content_marking_header_margin"`
	ApplyContentMarkingHeaderText                         types.String `tfsdk:"apply_content_marking_header_text"`
	ApplyDynamicWatermarkingEnabled                       types.String `tfsdk:"apply_dynamic_watermarking_enabled"`
	ApplyMessageMetaData                                  types.String `tfsdk:"apply_message_meta_data"`
	ApplyMessageMetaDataEnabled                           types.String `tfsdk:"apply_message_meta_data_enabled"`
	ApplyWaterMarkingEnabled                              types.String `tfsdk:"apply_water_marking_enabled"`
	ApplyWaterMarkingFontColor                            types.String `tfsdk:"apply_water_marking_font_color"`
	ApplyWaterMarkingFontName                             types.String `tfsdk:"apply_water_marking_font_name"`
	ApplyWaterMarkingFontSize                             types.String `tfsdk:"apply_water_marking_font_size"`
	ApplyWaterMarkingLayout                               types.String `tfsdk:"apply_water_marking_layout"`
	ApplyWaterMarkingText                                 types.String `tfsdk:"apply_water_marking_text"`
	ColumnAssetCondition                                  types.String `tfsdk:"column_asset_condition"`
	Comment                                               types.String `tfsdk:"comment"`
	ConditionalAccessAuthContext                          types.String `tfsdk:"conditional_access_auth_context"`
	Conditions                                            types.String `tfsdk:"conditions"`
	ContentType                                           types.String `tfsdk:"content_type"`
	DefaultContentLabel                                   types.String `tfsdk:"default_content_label"`
	DenyAccessEnabled                                     types.String `tfsdk:"deny_access_enabled"`
	DenyAccessExcludedPrincipals                          types.String `tfsdk:"deny_access_excluded_principals"`
	DenyAccessIncludedPrincipals                          types.String `tfsdk:"deny_access_included_principals"`
	DenyAccessRights                                      types.String `tfsdk:"deny_access_rights"`
	DenyAccessWorkload                                    types.String `tfsdk:"deny_access_workload"`
	DisplayName                                           types.String `tfsdk:"display_name"`
	DynamicWatermarkDisplay                               types.String `tfsdk:"dynamic_watermark_display"`
	EncryptionAipTemplateScopes                           types.String `tfsdk:"encryption_aip_template_scopes"`
	EncryptionContentExpiredOnDateInDaysOrNever           types.String `tfsdk:"encryption_content_expired_on_date_in_days_or_never"`
	EncryptionDisableAutomaticOwnerRights                 types.String `tfsdk:"encryption_disable_automatic_owner_rights"`
	EncryptionDoNotForward                                types.String `tfsdk:"encryption_do_not_forward"`
	EncryptionDoubleKeyEncryptionUrl                      types.String `tfsdk:"encryption_double_key_encryption_url"`
	EncryptionEnabled                                     types.String `tfsdk:"encryption_enabled"`
	EncryptionEncryptOnly                                 types.String `tfsdk:"encryption_encrypt_only"`
	EncryptionLinkedTemplateId                            types.String `tfsdk:"encryption_linked_template_id"`
	EncryptionOfflineAccessDays                           types.String `tfsdk:"encryption_offline_access_days"`
	EncryptionPromptUser                                  types.String `tfsdk:"encryption_prompt_user"`
	EncryptionProtectionType                              types.String `tfsdk:"encryption_protection_type"`
	EncryptionRightsDefinitions                           types.String `tfsdk:"encryption_rights_definitions"`
	EncryptionRightsUrl                                   types.String `tfsdk:"encryption_rights_url"`
	EncryptionTemplateId                                  types.String `tfsdk:"encryption_template_id"`
	InformationProtectionAttributeRequired                types.String `tfsdk:"information_protection_attribute_required"`
	InheritToChildItems                                   types.String `tfsdk:"inherit_to_child_items"`
	IsLabelGroup                                          types.Bool   `tfsdk:"is_label_group"`
	LabelActions                                          types.String `tfsdk:"label_actions"`
	LocaleSettings                                        types.String `tfsdk:"locale_settings"`
	MigrationId                                           types.String `tfsdk:"migration_id"`
	Name                                                  types.String `tfsdk:"name"`
	NextLabel                                             types.String `tfsdk:"next_label"`
	ParentId                                              types.String `tfsdk:"parent_id"`
	PreviousLabel                                         types.String `tfsdk:"previous_label"`
	Priority                                              types.String `tfsdk:"priority"`
	RemoveParentLink                                      types.Bool   `tfsdk:"remove_parent_link"`
	RuleBlob                                              types.String `tfsdk:"rule_blob"`
	SchematizedDataCondition                              types.String `tfsdk:"schematized_data_condition"`
	Setting                                               types.String `tfsdk:"setting"`
	Settings                                              types.String `tfsdk:"settings"`
	SiteAndGroupProtectionAllowAccessToGuestUsers         types.String `tfsdk:"site_and_group_protection_allow_access_to_guest_users"`
	SiteAndGroupProtectionAllowEmailFromGuestUsers        types.String `tfsdk:"site_and_group_protection_allow_email_from_guest_users"`
	SiteAndGroupProtectionAllowFullAccess                 types.String `tfsdk:"site_and_group_protection_allow_full_access"`
	SiteAndGroupProtectionAllowLimitedAccess              types.String `tfsdk:"site_and_group_protection_allow_limited_access"`
	SiteAndGroupProtectionBlockAccess                     types.String `tfsdk:"site_and_group_protection_block_access"`
	SiteAndGroupProtectionEnabled                         types.String `tfsdk:"site_and_group_protection_enabled"`
	SiteAndGroupProtectionLevel                           types.String `tfsdk:"site_and_group_protection_level"`
	SiteAndGroupProtectionPrivacy                         types.String `tfsdk:"site_and_group_protection_privacy"`
	SiteExternalSharingControlType                        types.String `tfsdk:"site_external_sharing_control_type"`
	TeamsAllowMeetingChat                                 types.String `tfsdk:"teams_allow_meeting_chat"`
	TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch     types.String `tfsdk:"teams_allow_private_teams_to_be_discoverable_using_search"`
	TeamsAllowedPresenters                                types.String `tfsdk:"teams_allowed_presenters"`
	TeamsBypassLobbyForDialInUsers                        types.String `tfsdk:"teams_bypass_lobby_for_dial_in_users"`
	TeamsChannelProtectionEnabled                         types.String `tfsdk:"teams_channel_protection_enabled"`
	TeamsChannelSharedWithExternalTenants                 types.String `tfsdk:"teams_channel_shared_with_external_tenants"`
	TeamsChannelSharedWithPrivateTeamsOnly                types.String `tfsdk:"teams_channel_shared_with_private_teams_only"`
	TeamsChannelSharedWithSameLabelOnly                   types.String `tfsdk:"teams_channel_shared_with_same_label_only"`
	TeamsCopyRestrictionEnforced                          types.String `tfsdk:"teams_copy_restriction_enforced"`
	TeamsDetectSensitiveContentDuringScreenSharingEnabled types.String `tfsdk:"teams_detect_sensitive_content_during_screen_sharing_enabled"`
	TeamsDisableLobby                                     types.String `tfsdk:"teams_disable_lobby"`
	TeamsEndToEndEncryptionEnabled                        types.String `tfsdk:"teams_end_to_end_encryption_enabled"`
	TeamsLobbyBypassScope                                 types.String `tfsdk:"teams_lobby_bypass_scope"`
	TeamsLobbyRestrictionEnforced                         types.String `tfsdk:"teams_lobby_restriction_enforced"`
	TeamsPresentersRestrictionEnforced                    types.String `tfsdk:"teams_presenters_restriction_enforced"`
	TeamsProtectionEnabled                                types.String `tfsdk:"teams_protection_enabled"`
	TeamsRecordAutomatically                              types.String `tfsdk:"teams_record_automatically"`
	TeamsVideoWatermark                                   types.String `tfsdk:"teams_video_watermark"`
	TeamsWhoCanRecord                                     types.String `tfsdk:"teams_who_can_record"`
	Tooltip                                               types.String `tfsdk:"tooltip"`
}

func (r *labelResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_label"
}

func (r *labelResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the Label object via New-Label / Get-Label / Set-Label / Remove-Label.",
		Attributes: map[string]schema.Attribute{
			"id":                                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                               schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"abac_enabled":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AbacEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"advanced_settings":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -AdvancedSettings parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_footer_alignment": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingFooterAlignment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_footer_enabled":   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingFooterEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_footer_font_color":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingFooterFontColor parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_footer_font_name":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingFooterFontName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_footer_font_size":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingFooterFontSize parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_footer_margin":                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingFooterMargin parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_footer_text":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingFooterText parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_header_alignment":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingHeaderAlignment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_header_enabled":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingHeaderEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_header_font_color":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingHeaderFontColor parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_header_font_name":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingHeaderFontName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_header_font_size":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingHeaderFontSize parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_header_margin":                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingHeaderMargin parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_content_marking_header_text":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyContentMarkingHeaderText parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_dynamic_watermarking_enabled":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyDynamicWatermarkingEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_message_meta_data":                                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyMessageMetaData parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_message_meta_data_enabled":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyMessageMetaDataEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_water_marking_enabled":                                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyWaterMarkingEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_water_marking_font_color":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyWaterMarkingFontColor parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_water_marking_font_name":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyWaterMarkingFontName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_water_marking_font_size":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyWaterMarkingFontSize parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_water_marking_layout":                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyWaterMarkingLayout parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"apply_water_marking_text":                                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ApplyWaterMarkingText parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"column_asset_condition":                                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ColumnAssetCondition parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comment":                                                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"conditional_access_auth_context":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ConditionalAccessAuthContext parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"conditions":                                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Conditions parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"content_type":                                                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ContentType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"default_content_label":                                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DefaultContentLabel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deny_access_enabled":                                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DenyAccessEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deny_access_excluded_principals":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DenyAccessExcludedPrincipals parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deny_access_included_principals":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DenyAccessIncludedPrincipals parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deny_access_rights":                                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DenyAccessRights parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"deny_access_workload":                                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DenyAccessWorkload parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"display_name":                                                 schema.StringAttribute{Required: true, Description: "Maps to the -DisplayName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"dynamic_watermark_display":                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DynamicWatermarkDisplay parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_aip_template_scopes":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionAipTemplateScopes parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"encryption_content_expired_on_date_in_days_or_never":          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionContentExpiredOnDateInDaysOrNever parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_disable_automatic_owner_rights":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionDisableAutomaticOwnerRights parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_do_not_forward":                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionDoNotForward parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_double_key_encryption_url":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionDoubleKeyEncryptionUrl parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_enabled":                                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_encrypt_only":                                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionEncryptOnly parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_linked_template_id":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionLinkedTemplateId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"encryption_offline_access_days":                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionOfflineAccessDays parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_prompt_user":                                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionPromptUser parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_protection_type":                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionProtectionType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_rights_definitions":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionRightsDefinitions parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_rights_url":                                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionRightsUrl parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"encryption_template_id":                                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -EncryptionTemplateId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"information_protection_attribute_required":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -InformationProtectionAttributeRequired parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"inherit_to_child_items":                                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -InheritToChildItems parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"is_label_group":                                               schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -IsLabelGroup parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.RequiresReplace(), boolplanmodifier.UseStateForUnknown()}},
			"label_actions":                                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LabelActions parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"locale_settings":                                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -LocaleSettings parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"migration_id":                                                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MigrationId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":                                                         schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"next_label":                                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -NextLabel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"parent_id":                                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ParentId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"previous_label":                                               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PreviousLabel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"priority":                                                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Priority parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"remove_parent_link":                                           schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -RemoveParentLink parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"rule_blob":                                                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RuleBlob parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"schematized_data_condition":                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SchematizedDataCondition parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"setting":                                                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Setting parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"settings":                                                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Settings parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_allow_access_to_guest_users":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionAllowAccessToGuestUsers parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_allow_email_from_guest_users":       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionAllowEmailFromGuestUsers parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_allow_full_access":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionAllowFullAccess parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_allow_limited_access":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionAllowLimitedAccess parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_block_access":                       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionBlockAccess parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_enabled":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_level":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionLevel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_and_group_protection_privacy":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteAndGroupProtectionPrivacy parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"site_external_sharing_control_type":                           schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -SiteExternalSharingControlType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_allow_meeting_chat":                                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsAllowMeetingChat parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_allow_private_teams_to_be_discoverable_using_search":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_allowed_presenters":                                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsAllowedPresenters parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_bypass_lobby_for_dial_in_users":                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsBypassLobbyForDialInUsers parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_channel_protection_enabled":                             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsChannelProtectionEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_channel_shared_with_external_tenants":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsChannelSharedWithExternalTenants parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_channel_shared_with_private_teams_only":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsChannelSharedWithPrivateTeamsOnly parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_channel_shared_with_same_label_only":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsChannelSharedWithSameLabelOnly parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_copy_restriction_enforced":                              schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsCopyRestrictionEnforced parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_detect_sensitive_content_during_screen_sharing_enabled": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsDetectSensitiveContentDuringScreenSharingEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_disable_lobby":                                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsDisableLobby parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_end_to_end_encryption_enabled":                          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsEndToEndEncryptionEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_lobby_bypass_scope":                                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsLobbyBypassScope parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_lobby_restriction_enforced":                             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsLobbyRestrictionEnforced parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_presenters_restriction_enforced":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsPresentersRestrictionEnforced parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_protection_enabled":                                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsProtectionEnabled parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_record_automatically":                                   schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsRecordAutomatically parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_video_watermark":                                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsVideoWatermark parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"teams_who_can_record":                                         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TeamsWhoCanRecord parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"tooltip":                                                      schema.StringAttribute{Required: true, Description: "Maps to the -Tooltip parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
		},
	}
}

func (r *labelResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *labelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan labelModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewLabelParams{
		ApplyContentMarkingFooterFontColor:          plan.ApplyContentMarkingFooterFontColor.ValueString(),
		ApplyContentMarkingFooterFontName:           plan.ApplyContentMarkingFooterFontName.ValueString(),
		ApplyContentMarkingFooterText:               plan.ApplyContentMarkingFooterText.ValueString(),
		ApplyContentMarkingHeaderFontColor:          plan.ApplyContentMarkingHeaderFontColor.ValueString(),
		ApplyContentMarkingHeaderFontName:           plan.ApplyContentMarkingHeaderFontName.ValueString(),
		ApplyContentMarkingHeaderText:               plan.ApplyContentMarkingHeaderText.ValueString(),
		ApplyWaterMarkingFontColor:                  plan.ApplyWaterMarkingFontColor.ValueString(),
		ApplyWaterMarkingFontName:                   plan.ApplyWaterMarkingFontName.ValueString(),
		ApplyWaterMarkingText:                       plan.ApplyWaterMarkingText.ValueString(),
		ColumnAssetCondition:                        plan.ColumnAssetCondition.ValueString(),
		Comment:                                     plan.Comment.ValueString(),
		ConditionalAccessAuthContext:                plan.ConditionalAccessAuthContext.ValueString(),
		DefaultContentLabel:                         plan.DefaultContentLabel.ValueString(),
		DenyAccessExcludedPrincipals:                plan.DenyAccessExcludedPrincipals.ValueString(),
		DenyAccessIncludedPrincipals:                plan.DenyAccessIncludedPrincipals.ValueString(),
		DenyAccessRights:                            plan.DenyAccessRights.ValueString(),
		DenyAccessWorkload:                          plan.DenyAccessWorkload.ValueString(),
		DisplayName:                                 plan.DisplayName.ValueString(),
		DynamicWatermarkDisplay:                     plan.DynamicWatermarkDisplay.ValueString(),
		EncryptionAipTemplateScopes:                 plan.EncryptionAipTemplateScopes.ValueString(),
		EncryptionContentExpiredOnDateInDaysOrNever: plan.EncryptionContentExpiredOnDateInDaysOrNever.ValueString(),
		EncryptionDoubleKeyEncryptionUrl:            plan.EncryptionDoubleKeyEncryptionUrl.ValueString(),
		EncryptionLinkedTemplateId:                  plan.EncryptionLinkedTemplateId.ValueString(),
		EncryptionRightsUrl:                         plan.EncryptionRightsUrl.ValueString(),
		EncryptionTemplateId:                        plan.EncryptionTemplateId.ValueString(),
		IsLabelGroup:                                plan.IsLabelGroup.ValueBool(),
		MigrationId:                                 plan.MigrationId.ValueString(),
		Name:                                        plan.Name.ValueString(),
		RuleBlob:                                    plan.RuleBlob.ValueString(),
		SchematizedDataCondition:                    plan.SchematizedDataCondition.ValueString(),
		Tooltip:                                     plan.Tooltip.ValueString(),
	}
	if v := plan.AbacEnabled.ValueString(); v != "" {
		p.AbacEnabled = v
	}
	if v := plan.AdvancedSettings.ValueString(); v != "" {
		p.AdvancedSettings = v
	}
	if v := plan.ApplyContentMarkingFooterAlignment.ValueString(); v != "" {
		p.ApplyContentMarkingFooterAlignment = v
	}
	if v := plan.ApplyContentMarkingFooterEnabled.ValueString(); v != "" {
		p.ApplyContentMarkingFooterEnabled = v
	}
	if v := plan.ApplyContentMarkingFooterFontSize.ValueString(); v != "" {
		p.ApplyContentMarkingFooterFontSize = v
	}
	if v := plan.ApplyContentMarkingFooterMargin.ValueString(); v != "" {
		p.ApplyContentMarkingFooterMargin = v
	}
	if v := plan.ApplyContentMarkingHeaderAlignment.ValueString(); v != "" {
		p.ApplyContentMarkingHeaderAlignment = v
	}
	if v := plan.ApplyContentMarkingHeaderEnabled.ValueString(); v != "" {
		p.ApplyContentMarkingHeaderEnabled = v
	}
	if v := plan.ApplyContentMarkingHeaderFontSize.ValueString(); v != "" {
		p.ApplyContentMarkingHeaderFontSize = v
	}
	if v := plan.ApplyContentMarkingHeaderMargin.ValueString(); v != "" {
		p.ApplyContentMarkingHeaderMargin = v
	}
	if v := plan.ApplyDynamicWatermarkingEnabled.ValueString(); v != "" {
		p.ApplyDynamicWatermarkingEnabled = v
	}
	if v := plan.ApplyMessageMetaData.ValueString(); v != "" {
		p.ApplyMessageMetaData = v
	}
	if v := plan.ApplyMessageMetaDataEnabled.ValueString(); v != "" {
		p.ApplyMessageMetaDataEnabled = v
	}
	if v := plan.ApplyWaterMarkingEnabled.ValueString(); v != "" {
		p.ApplyWaterMarkingEnabled = v
	}
	if v := plan.ApplyWaterMarkingFontSize.ValueString(); v != "" {
		p.ApplyWaterMarkingFontSize = v
	}
	if v := plan.ApplyWaterMarkingLayout.ValueString(); v != "" {
		p.ApplyWaterMarkingLayout = v
	}
	if v := plan.Conditions.ValueString(); v != "" {
		p.Conditions = v
	}
	if v := plan.ContentType.ValueString(); v != "" {
		p.ContentType = v
	}
	if v := plan.DenyAccessEnabled.ValueString(); v != "" {
		p.DenyAccessEnabled = v
	}
	if v := plan.EncryptionDisableAutomaticOwnerRights.ValueString(); v != "" {
		p.EncryptionDisableAutomaticOwnerRights = v
	}
	if v := plan.EncryptionDoNotForward.ValueString(); v != "" {
		p.EncryptionDoNotForward = v
	}
	if v := plan.EncryptionEnabled.ValueString(); v != "" {
		p.EncryptionEnabled = v
	}
	if v := plan.EncryptionEncryptOnly.ValueString(); v != "" {
		p.EncryptionEncryptOnly = v
	}
	if v := plan.EncryptionOfflineAccessDays.ValueString(); v != "" {
		p.EncryptionOfflineAccessDays = v
	}
	if v := plan.EncryptionPromptUser.ValueString(); v != "" {
		p.EncryptionPromptUser = v
	}
	if v := plan.EncryptionProtectionType.ValueString(); v != "" {
		p.EncryptionProtectionType = v
	}
	if v := plan.EncryptionRightsDefinitions.ValueString(); v != "" {
		p.EncryptionRightsDefinitions = v
	}
	if v := plan.InformationProtectionAttributeRequired.ValueString(); v != "" {
		p.InformationProtectionAttributeRequired = v
	}
	if v := plan.InheritToChildItems.ValueString(); v != "" {
		p.InheritToChildItems = v
	}
	if v := plan.LabelActions.ValueString(); v != "" {
		p.LabelActions = v
	}
	if v := plan.LocaleSettings.ValueString(); v != "" {
		p.LocaleSettings = v
	}
	if v := plan.ParentId.ValueString(); v != "" {
		p.ParentId = v
	}
	if v := plan.Setting.ValueString(); v != "" {
		p.Setting = v
	}
	if v := plan.Settings.ValueString(); v != "" {
		p.Settings = v
	}
	if v := plan.SiteAndGroupProtectionAllowAccessToGuestUsers.ValueString(); v != "" {
		p.SiteAndGroupProtectionAllowAccessToGuestUsers = v
	}
	if v := plan.SiteAndGroupProtectionAllowEmailFromGuestUsers.ValueString(); v != "" {
		p.SiteAndGroupProtectionAllowEmailFromGuestUsers = v
	}
	if v := plan.SiteAndGroupProtectionAllowFullAccess.ValueString(); v != "" {
		p.SiteAndGroupProtectionAllowFullAccess = v
	}
	if v := plan.SiteAndGroupProtectionAllowLimitedAccess.ValueString(); v != "" {
		p.SiteAndGroupProtectionAllowLimitedAccess = v
	}
	if v := plan.SiteAndGroupProtectionBlockAccess.ValueString(); v != "" {
		p.SiteAndGroupProtectionBlockAccess = v
	}
	if v := plan.SiteAndGroupProtectionEnabled.ValueString(); v != "" {
		p.SiteAndGroupProtectionEnabled = v
	}
	if v := plan.SiteAndGroupProtectionLevel.ValueString(); v != "" {
		p.SiteAndGroupProtectionLevel = v
	}
	if v := plan.SiteAndGroupProtectionPrivacy.ValueString(); v != "" {
		p.SiteAndGroupProtectionPrivacy = v
	}
	if v := plan.SiteExternalSharingControlType.ValueString(); v != "" {
		p.SiteExternalSharingControlType = v
	}
	if v := plan.TeamsAllowMeetingChat.ValueString(); v != "" {
		p.TeamsAllowMeetingChat = v
	}
	if v := plan.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch.ValueString(); v != "" {
		p.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch = v
	}
	if v := plan.TeamsAllowedPresenters.ValueString(); v != "" {
		p.TeamsAllowedPresenters = v
	}
	if v := plan.TeamsBypassLobbyForDialInUsers.ValueString(); v != "" {
		p.TeamsBypassLobbyForDialInUsers = v
	}
	if v := plan.TeamsChannelProtectionEnabled.ValueString(); v != "" {
		p.TeamsChannelProtectionEnabled = v
	}
	if v := plan.TeamsChannelSharedWithExternalTenants.ValueString(); v != "" {
		p.TeamsChannelSharedWithExternalTenants = v
	}
	if v := plan.TeamsChannelSharedWithPrivateTeamsOnly.ValueString(); v != "" {
		p.TeamsChannelSharedWithPrivateTeamsOnly = v
	}
	if v := plan.TeamsChannelSharedWithSameLabelOnly.ValueString(); v != "" {
		p.TeamsChannelSharedWithSameLabelOnly = v
	}
	if v := plan.TeamsCopyRestrictionEnforced.ValueString(); v != "" {
		p.TeamsCopyRestrictionEnforced = v
	}
	if v := plan.TeamsDetectSensitiveContentDuringScreenSharingEnabled.ValueString(); v != "" {
		p.TeamsDetectSensitiveContentDuringScreenSharingEnabled = v
	}
	if v := plan.TeamsDisableLobby.ValueString(); v != "" {
		p.TeamsDisableLobby = v
	}
	if v := plan.TeamsEndToEndEncryptionEnabled.ValueString(); v != "" {
		p.TeamsEndToEndEncryptionEnabled = v
	}
	if v := plan.TeamsLobbyBypassScope.ValueString(); v != "" {
		p.TeamsLobbyBypassScope = v
	}
	if v := plan.TeamsLobbyRestrictionEnforced.ValueString(); v != "" {
		p.TeamsLobbyRestrictionEnforced = v
	}
	if v := plan.TeamsPresentersRestrictionEnforced.ValueString(); v != "" {
		p.TeamsPresentersRestrictionEnforced = v
	}
	if v := plan.TeamsProtectionEnabled.ValueString(); v != "" {
		p.TeamsProtectionEnabled = v
	}
	if v := plan.TeamsRecordAutomatically.ValueString(); v != "" {
		p.TeamsRecordAutomatically = v
	}
	if v := plan.TeamsVideoWatermark.ValueString(); v != "" {
		p.TeamsVideoWatermark = v
	}
	if v := plan.TeamsWhoCanRecord.ValueString(); v != "" {
		p.TeamsWhoCanRecord = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewLabel(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-Label failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-Label returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readLabel(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *labelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state labelModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *labelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state labelModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetLabelParams{}
	sp.Identity = id
	if v := plan.AbacEnabled.ValueString(); v != "" {
		sp.AbacEnabled = v
	}
	if v := plan.AdvancedSettings.ValueString(); v != "" {
		sp.AdvancedSettings = v
	}
	if v := plan.ApplyContentMarkingFooterAlignment.ValueString(); v != "" {
		sp.ApplyContentMarkingFooterAlignment = v
	}
	if v := plan.ApplyContentMarkingFooterEnabled.ValueString(); v != "" {
		sp.ApplyContentMarkingFooterEnabled = v
	}
	sp.ApplyContentMarkingFooterFontColor = plan.ApplyContentMarkingFooterFontColor.ValueString()
	sp.ApplyContentMarkingFooterFontName = plan.ApplyContentMarkingFooterFontName.ValueString()
	if v := plan.ApplyContentMarkingFooterFontSize.ValueString(); v != "" {
		sp.ApplyContentMarkingFooterFontSize = v
	}
	if v := plan.ApplyContentMarkingFooterMargin.ValueString(); v != "" {
		sp.ApplyContentMarkingFooterMargin = v
	}
	sp.ApplyContentMarkingFooterText = plan.ApplyContentMarkingFooterText.ValueString()
	if v := plan.ApplyContentMarkingHeaderAlignment.ValueString(); v != "" {
		sp.ApplyContentMarkingHeaderAlignment = v
	}
	if v := plan.ApplyContentMarkingHeaderEnabled.ValueString(); v != "" {
		sp.ApplyContentMarkingHeaderEnabled = v
	}
	sp.ApplyContentMarkingHeaderFontColor = plan.ApplyContentMarkingHeaderFontColor.ValueString()
	sp.ApplyContentMarkingHeaderFontName = plan.ApplyContentMarkingHeaderFontName.ValueString()
	if v := plan.ApplyContentMarkingHeaderFontSize.ValueString(); v != "" {
		sp.ApplyContentMarkingHeaderFontSize = v
	}
	if v := plan.ApplyContentMarkingHeaderMargin.ValueString(); v != "" {
		sp.ApplyContentMarkingHeaderMargin = v
	}
	sp.ApplyContentMarkingHeaderText = plan.ApplyContentMarkingHeaderText.ValueString()
	if v := plan.ApplyDynamicWatermarkingEnabled.ValueString(); v != "" {
		sp.ApplyDynamicWatermarkingEnabled = v
	}
	if v := plan.ApplyMessageMetaData.ValueString(); v != "" {
		sp.ApplyMessageMetaData = v
	}
	if v := plan.ApplyMessageMetaDataEnabled.ValueString(); v != "" {
		sp.ApplyMessageMetaDataEnabled = v
	}
	if v := plan.ApplyWaterMarkingEnabled.ValueString(); v != "" {
		sp.ApplyWaterMarkingEnabled = v
	}
	sp.ApplyWaterMarkingFontColor = plan.ApplyWaterMarkingFontColor.ValueString()
	sp.ApplyWaterMarkingFontName = plan.ApplyWaterMarkingFontName.ValueString()
	if v := plan.ApplyWaterMarkingFontSize.ValueString(); v != "" {
		sp.ApplyWaterMarkingFontSize = v
	}
	if v := plan.ApplyWaterMarkingLayout.ValueString(); v != "" {
		sp.ApplyWaterMarkingLayout = v
	}
	sp.ApplyWaterMarkingText = plan.ApplyWaterMarkingText.ValueString()
	sp.ColumnAssetCondition = plan.ColumnAssetCondition.ValueString()
	sp.Comment = plan.Comment.ValueString()
	sp.ConditionalAccessAuthContext = plan.ConditionalAccessAuthContext.ValueString()
	if v := plan.Conditions.ValueString(); v != "" {
		sp.Conditions = v
	}
	if v := plan.ContentType.ValueString(); v != "" {
		sp.ContentType = v
	}
	sp.DefaultContentLabel = plan.DefaultContentLabel.ValueString()
	if v := plan.DenyAccessEnabled.ValueString(); v != "" {
		sp.DenyAccessEnabled = v
	}
	sp.DenyAccessExcludedPrincipals = plan.DenyAccessExcludedPrincipals.ValueString()
	sp.DenyAccessIncludedPrincipals = plan.DenyAccessIncludedPrincipals.ValueString()
	sp.DenyAccessRights = plan.DenyAccessRights.ValueString()
	sp.DenyAccessWorkload = plan.DenyAccessWorkload.ValueString()
	sp.DynamicWatermarkDisplay = plan.DynamicWatermarkDisplay.ValueString()
	sp.EncryptionContentExpiredOnDateInDaysOrNever = plan.EncryptionContentExpiredOnDateInDaysOrNever.ValueString()
	if v := plan.EncryptionDisableAutomaticOwnerRights.ValueString(); v != "" {
		sp.EncryptionDisableAutomaticOwnerRights = v
	}
	if v := plan.EncryptionDoNotForward.ValueString(); v != "" {
		sp.EncryptionDoNotForward = v
	}
	sp.EncryptionDoubleKeyEncryptionUrl = plan.EncryptionDoubleKeyEncryptionUrl.ValueString()
	if v := plan.EncryptionEnabled.ValueString(); v != "" {
		sp.EncryptionEnabled = v
	}
	if v := plan.EncryptionEncryptOnly.ValueString(); v != "" {
		sp.EncryptionEncryptOnly = v
	}
	if v := plan.EncryptionOfflineAccessDays.ValueString(); v != "" {
		sp.EncryptionOfflineAccessDays = v
	}
	if v := plan.EncryptionPromptUser.ValueString(); v != "" {
		sp.EncryptionPromptUser = v
	}
	if v := plan.EncryptionProtectionType.ValueString(); v != "" {
		sp.EncryptionProtectionType = v
	}
	if v := plan.EncryptionRightsDefinitions.ValueString(); v != "" {
		sp.EncryptionRightsDefinitions = v
	}
	sp.EncryptionRightsUrl = plan.EncryptionRightsUrl.ValueString()
	if v := plan.InformationProtectionAttributeRequired.ValueString(); v != "" {
		sp.InformationProtectionAttributeRequired = v
	}
	if v := plan.InheritToChildItems.ValueString(); v != "" {
		sp.InheritToChildItems = v
	}
	if v := plan.LabelActions.ValueString(); v != "" {
		sp.LabelActions = v
	}
	if v := plan.LocaleSettings.ValueString(); v != "" {
		sp.LocaleSettings = v
	}
	sp.MigrationId = plan.MigrationId.ValueString()
	if v := plan.NextLabel.ValueString(); v != "" {
		sp.NextLabel = v
	}
	if v := plan.ParentId.ValueString(); v != "" {
		sp.ParentId = v
	}
	if v := plan.PreviousLabel.ValueString(); v != "" {
		sp.PreviousLabel = v
	}
	if v := plan.Priority.ValueString(); v != "" {
		sp.Priority = v
	}
	sp.RemoveParentLink = plan.RemoveParentLink.ValueBool()
	sp.RuleBlob = plan.RuleBlob.ValueString()
	sp.SchematizedDataCondition = plan.SchematizedDataCondition.ValueString()
	if v := plan.Setting.ValueString(); v != "" {
		sp.Setting = v
	}
	if v := plan.Settings.ValueString(); v != "" {
		sp.Settings = v
	}
	if v := plan.SiteAndGroupProtectionAllowAccessToGuestUsers.ValueString(); v != "" {
		sp.SiteAndGroupProtectionAllowAccessToGuestUsers = v
	}
	if v := plan.SiteAndGroupProtectionAllowEmailFromGuestUsers.ValueString(); v != "" {
		sp.SiteAndGroupProtectionAllowEmailFromGuestUsers = v
	}
	if v := plan.SiteAndGroupProtectionAllowFullAccess.ValueString(); v != "" {
		sp.SiteAndGroupProtectionAllowFullAccess = v
	}
	if v := plan.SiteAndGroupProtectionAllowLimitedAccess.ValueString(); v != "" {
		sp.SiteAndGroupProtectionAllowLimitedAccess = v
	}
	if v := plan.SiteAndGroupProtectionBlockAccess.ValueString(); v != "" {
		sp.SiteAndGroupProtectionBlockAccess = v
	}
	if v := plan.SiteAndGroupProtectionEnabled.ValueString(); v != "" {
		sp.SiteAndGroupProtectionEnabled = v
	}
	if v := plan.SiteAndGroupProtectionLevel.ValueString(); v != "" {
		sp.SiteAndGroupProtectionLevel = v
	}
	if v := plan.SiteAndGroupProtectionPrivacy.ValueString(); v != "" {
		sp.SiteAndGroupProtectionPrivacy = v
	}
	if v := plan.SiteExternalSharingControlType.ValueString(); v != "" {
		sp.SiteExternalSharingControlType = v
	}
	if v := plan.TeamsAllowMeetingChat.ValueString(); v != "" {
		sp.TeamsAllowMeetingChat = v
	}
	if v := plan.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch.ValueString(); v != "" {
		sp.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch = v
	}
	if v := plan.TeamsAllowedPresenters.ValueString(); v != "" {
		sp.TeamsAllowedPresenters = v
	}
	if v := plan.TeamsBypassLobbyForDialInUsers.ValueString(); v != "" {
		sp.TeamsBypassLobbyForDialInUsers = v
	}
	if v := plan.TeamsChannelProtectionEnabled.ValueString(); v != "" {
		sp.TeamsChannelProtectionEnabled = v
	}
	if v := plan.TeamsChannelSharedWithExternalTenants.ValueString(); v != "" {
		sp.TeamsChannelSharedWithExternalTenants = v
	}
	if v := plan.TeamsChannelSharedWithPrivateTeamsOnly.ValueString(); v != "" {
		sp.TeamsChannelSharedWithPrivateTeamsOnly = v
	}
	if v := plan.TeamsChannelSharedWithSameLabelOnly.ValueString(); v != "" {
		sp.TeamsChannelSharedWithSameLabelOnly = v
	}
	if v := plan.TeamsCopyRestrictionEnforced.ValueString(); v != "" {
		sp.TeamsCopyRestrictionEnforced = v
	}
	if v := plan.TeamsDetectSensitiveContentDuringScreenSharingEnabled.ValueString(); v != "" {
		sp.TeamsDetectSensitiveContentDuringScreenSharingEnabled = v
	}
	if v := plan.TeamsDisableLobby.ValueString(); v != "" {
		sp.TeamsDisableLobby = v
	}
	if v := plan.TeamsEndToEndEncryptionEnabled.ValueString(); v != "" {
		sp.TeamsEndToEndEncryptionEnabled = v
	}
	if v := plan.TeamsLobbyBypassScope.ValueString(); v != "" {
		sp.TeamsLobbyBypassScope = v
	}
	if v := plan.TeamsLobbyRestrictionEnforced.ValueString(); v != "" {
		sp.TeamsLobbyRestrictionEnforced = v
	}
	if v := plan.TeamsPresentersRestrictionEnforced.ValueString(); v != "" {
		sp.TeamsPresentersRestrictionEnforced = v
	}
	if v := plan.TeamsProtectionEnabled.ValueString(); v != "" {
		sp.TeamsProtectionEnabled = v
	}
	if v := plan.TeamsRecordAutomatically.ValueString(); v != "" {
		sp.TeamsRecordAutomatically = v
	}
	if v := plan.TeamsVideoWatermark.ValueString(); v != "" {
		sp.TeamsVideoWatermark = v
	}
	if v := plan.TeamsWhoCanRecord.ValueString(); v != "" {
		sp.TeamsWhoCanRecord = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetLabel(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-Label failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"AbacEnabled":                                           cfg.AbacEnabled,
		"AdvancedSettings":                                      cfg.AdvancedSettings,
		"ApplyContentMarkingFooterAlignment":                    cfg.ApplyContentMarkingFooterAlignment,
		"ApplyContentMarkingFooterEnabled":                      cfg.ApplyContentMarkingFooterEnabled,
		"ApplyContentMarkingFooterFontColor":                    cfg.ApplyContentMarkingFooterFontColor,
		"ApplyContentMarkingFooterFontName":                     cfg.ApplyContentMarkingFooterFontName,
		"ApplyContentMarkingFooterFontSize":                     cfg.ApplyContentMarkingFooterFontSize,
		"ApplyContentMarkingFooterMargin":                       cfg.ApplyContentMarkingFooterMargin,
		"ApplyContentMarkingFooterText":                         cfg.ApplyContentMarkingFooterText,
		"ApplyContentMarkingHeaderAlignment":                    cfg.ApplyContentMarkingHeaderAlignment,
		"ApplyContentMarkingHeaderEnabled":                      cfg.ApplyContentMarkingHeaderEnabled,
		"ApplyContentMarkingHeaderFontColor":                    cfg.ApplyContentMarkingHeaderFontColor,
		"ApplyContentMarkingHeaderFontName":                     cfg.ApplyContentMarkingHeaderFontName,
		"ApplyContentMarkingHeaderFontSize":                     cfg.ApplyContentMarkingHeaderFontSize,
		"ApplyContentMarkingHeaderMargin":                       cfg.ApplyContentMarkingHeaderMargin,
		"ApplyContentMarkingHeaderText":                         cfg.ApplyContentMarkingHeaderText,
		"ApplyDynamicWatermarkingEnabled":                       cfg.ApplyDynamicWatermarkingEnabled,
		"ApplyMessageMetaData":                                  cfg.ApplyMessageMetaData,
		"ApplyMessageMetaDataEnabled":                           cfg.ApplyMessageMetaDataEnabled,
		"ApplyWaterMarkingEnabled":                              cfg.ApplyWaterMarkingEnabled,
		"ApplyWaterMarkingFontColor":                            cfg.ApplyWaterMarkingFontColor,
		"ApplyWaterMarkingFontName":                             cfg.ApplyWaterMarkingFontName,
		"ApplyWaterMarkingFontSize":                             cfg.ApplyWaterMarkingFontSize,
		"ApplyWaterMarkingLayout":                               cfg.ApplyWaterMarkingLayout,
		"ApplyWaterMarkingText":                                 cfg.ApplyWaterMarkingText,
		"ColumnAssetCondition":                                  cfg.ColumnAssetCondition,
		"Comment":                                               cfg.Comment,
		"ConditionalAccessAuthContext":                          cfg.ConditionalAccessAuthContext,
		"Conditions":                                            cfg.Conditions,
		"ContentType":                                           cfg.ContentType,
		"DefaultContentLabel":                                   cfg.DefaultContentLabel,
		"DenyAccessEnabled":                                     cfg.DenyAccessEnabled,
		"DenyAccessExcludedPrincipals":                          cfg.DenyAccessExcludedPrincipals,
		"DenyAccessIncludedPrincipals":                          cfg.DenyAccessIncludedPrincipals,
		"DenyAccessRights":                                      cfg.DenyAccessRights,
		"DenyAccessWorkload":                                    cfg.DenyAccessWorkload,
		"DynamicWatermarkDisplay":                               cfg.DynamicWatermarkDisplay,
		"EncryptionContentExpiredOnDateInDaysOrNever":           cfg.EncryptionContentExpiredOnDateInDaysOrNever,
		"EncryptionDisableAutomaticOwnerRights":                 cfg.EncryptionDisableAutomaticOwnerRights,
		"EncryptionDoNotForward":                                cfg.EncryptionDoNotForward,
		"EncryptionDoubleKeyEncryptionUrl":                      cfg.EncryptionDoubleKeyEncryptionUrl,
		"EncryptionEnabled":                                     cfg.EncryptionEnabled,
		"EncryptionEncryptOnly":                                 cfg.EncryptionEncryptOnly,
		"EncryptionOfflineAccessDays":                           cfg.EncryptionOfflineAccessDays,
		"EncryptionPromptUser":                                  cfg.EncryptionPromptUser,
		"EncryptionProtectionType":                              cfg.EncryptionProtectionType,
		"EncryptionRightsDefinitions":                           cfg.EncryptionRightsDefinitions,
		"EncryptionRightsUrl":                                   cfg.EncryptionRightsUrl,
		"InformationProtectionAttributeRequired":                cfg.InformationProtectionAttributeRequired,
		"InheritToChildItems":                                   cfg.InheritToChildItems,
		"LabelActions":                                          cfg.LabelActions,
		"LocaleSettings":                                        cfg.LocaleSettings,
		"MigrationId":                                           cfg.MigrationId,
		"NextLabel":                                             cfg.NextLabel,
		"ParentId":                                              cfg.ParentId,
		"PreviousLabel":                                         cfg.PreviousLabel,
		"Priority":                                              cfg.Priority,
		"RuleBlob":                                              cfg.RuleBlob,
		"SchematizedDataCondition":                              cfg.SchematizedDataCondition,
		"Setting":                                               cfg.Setting,
		"Settings":                                              cfg.Settings,
		"SiteAndGroupProtectionAllowAccessToGuestUsers":         cfg.SiteAndGroupProtectionAllowAccessToGuestUsers,
		"SiteAndGroupProtectionAllowEmailFromGuestUsers":        cfg.SiteAndGroupProtectionAllowEmailFromGuestUsers,
		"SiteAndGroupProtectionAllowFullAccess":                 cfg.SiteAndGroupProtectionAllowFullAccess,
		"SiteAndGroupProtectionAllowLimitedAccess":              cfg.SiteAndGroupProtectionAllowLimitedAccess,
		"SiteAndGroupProtectionBlockAccess":                     cfg.SiteAndGroupProtectionBlockAccess,
		"SiteAndGroupProtectionEnabled":                         cfg.SiteAndGroupProtectionEnabled,
		"SiteAndGroupProtectionLevel":                           cfg.SiteAndGroupProtectionLevel,
		"SiteAndGroupProtectionPrivacy":                         cfg.SiteAndGroupProtectionPrivacy,
		"SiteExternalSharingControlType":                        cfg.SiteExternalSharingControlType,
		"TeamsAllowMeetingChat":                                 cfg.TeamsAllowMeetingChat,
		"TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch":     cfg.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch,
		"TeamsAllowedPresenters":                                cfg.TeamsAllowedPresenters,
		"TeamsBypassLobbyForDialInUsers":                        cfg.TeamsBypassLobbyForDialInUsers,
		"TeamsChannelProtectionEnabled":                         cfg.TeamsChannelProtectionEnabled,
		"TeamsChannelSharedWithExternalTenants":                 cfg.TeamsChannelSharedWithExternalTenants,
		"TeamsChannelSharedWithPrivateTeamsOnly":                cfg.TeamsChannelSharedWithPrivateTeamsOnly,
		"TeamsChannelSharedWithSameLabelOnly":                   cfg.TeamsChannelSharedWithSameLabelOnly,
		"TeamsCopyRestrictionEnforced":                          cfg.TeamsCopyRestrictionEnforced,
		"TeamsDetectSensitiveContentDuringScreenSharingEnabled": cfg.TeamsDetectSensitiveContentDuringScreenSharingEnabled,
		"TeamsDisableLobby":                                     cfg.TeamsDisableLobby,
		"TeamsEndToEndEncryptionEnabled":                        cfg.TeamsEndToEndEncryptionEnabled,
		"TeamsLobbyBypassScope":                                 cfg.TeamsLobbyBypassScope,
		"TeamsLobbyRestrictionEnforced":                         cfg.TeamsLobbyRestrictionEnforced,
		"TeamsPresentersRestrictionEnforced":                    cfg.TeamsPresentersRestrictionEnforced,
		"TeamsProtectionEnabled":                                cfg.TeamsProtectionEnabled,
		"TeamsRecordAutomatically":                              cfg.TeamsRecordAutomatically,
		"TeamsVideoWatermark":                                   cfg.TeamsVideoWatermark,
		"TeamsWhoCanRecord":                                     cfg.TeamsWhoCanRecord,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *labelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state labelModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveLabel(ctx, purview.RemoveLabelParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-Label failed", err.Error())
		}
	}
}

func (r *labelResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *labelResource) identityOf(m labelModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *labelResource) refresh(ctx context.Context, identity string, m *labelModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetLabel(ctx, purview.GetLabelParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-Label failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readLabel(ctx, obj, m)
	return true
}

func readLabel(ctx context.Context, obj map[string]any, m *labelModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AbacEnabled = types.StringValue(getString(obj, "AbacEnabled"))
	m.AdvancedSettings = types.StringValue(getString(obj, "AdvancedSettings"))
	m.ApplyContentMarkingFooterAlignment = types.StringValue(getString(obj, "ApplyContentMarkingFooterAlignment"))
	m.ApplyContentMarkingFooterEnabled = types.StringValue(getString(obj, "ApplyContentMarkingFooterEnabled"))
	m.ApplyContentMarkingFooterFontColor = types.StringValue(getString(obj, "ApplyContentMarkingFooterFontColor"))
	m.ApplyContentMarkingFooterFontName = types.StringValue(getString(obj, "ApplyContentMarkingFooterFontName"))
	m.ApplyContentMarkingFooterFontSize = types.StringValue(getString(obj, "ApplyContentMarkingFooterFontSize"))
	m.ApplyContentMarkingFooterMargin = types.StringValue(getString(obj, "ApplyContentMarkingFooterMargin"))
	m.ApplyContentMarkingFooterText = types.StringValue(getString(obj, "ApplyContentMarkingFooterText"))
	m.ApplyContentMarkingHeaderAlignment = types.StringValue(getString(obj, "ApplyContentMarkingHeaderAlignment"))
	m.ApplyContentMarkingHeaderEnabled = types.StringValue(getString(obj, "ApplyContentMarkingHeaderEnabled"))
	m.ApplyContentMarkingHeaderFontColor = types.StringValue(getString(obj, "ApplyContentMarkingHeaderFontColor"))
	m.ApplyContentMarkingHeaderFontName = types.StringValue(getString(obj, "ApplyContentMarkingHeaderFontName"))
	m.ApplyContentMarkingHeaderFontSize = types.StringValue(getString(obj, "ApplyContentMarkingHeaderFontSize"))
	m.ApplyContentMarkingHeaderMargin = types.StringValue(getString(obj, "ApplyContentMarkingHeaderMargin"))
	m.ApplyContentMarkingHeaderText = types.StringValue(getString(obj, "ApplyContentMarkingHeaderText"))
	m.ApplyDynamicWatermarkingEnabled = types.StringValue(getString(obj, "ApplyDynamicWatermarkingEnabled"))
	m.ApplyMessageMetaData = types.StringValue(getString(obj, "ApplyMessageMetaData"))
	m.ApplyMessageMetaDataEnabled = types.StringValue(getString(obj, "ApplyMessageMetaDataEnabled"))
	m.ApplyWaterMarkingEnabled = types.StringValue(getString(obj, "ApplyWaterMarkingEnabled"))
	m.ApplyWaterMarkingFontColor = types.StringValue(getString(obj, "ApplyWaterMarkingFontColor"))
	m.ApplyWaterMarkingFontName = types.StringValue(getString(obj, "ApplyWaterMarkingFontName"))
	m.ApplyWaterMarkingFontSize = types.StringValue(getString(obj, "ApplyWaterMarkingFontSize"))
	m.ApplyWaterMarkingLayout = types.StringValue(getString(obj, "ApplyWaterMarkingLayout"))
	m.ApplyWaterMarkingText = types.StringValue(getString(obj, "ApplyWaterMarkingText"))
	m.ColumnAssetCondition = types.StringValue(getString(obj, "ColumnAssetCondition"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.ConditionalAccessAuthContext = types.StringValue(getString(obj, "ConditionalAccessAuthContext"))
	m.Conditions = types.StringValue(getString(obj, "Conditions"))
	m.ContentType = types.StringValue(getString(obj, "ContentType"))
	m.DefaultContentLabel = types.StringValue(getString(obj, "DefaultContentLabel"))
	m.DenyAccessEnabled = types.StringValue(getString(obj, "DenyAccessEnabled"))
	m.DenyAccessExcludedPrincipals = types.StringValue(getString(obj, "DenyAccessExcludedPrincipals"))
	m.DenyAccessIncludedPrincipals = types.StringValue(getString(obj, "DenyAccessIncludedPrincipals"))
	m.DenyAccessRights = types.StringValue(getString(obj, "DenyAccessRights"))
	m.DenyAccessWorkload = types.StringValue(getString(obj, "DenyAccessWorkload"))
	m.DisplayName = types.StringValue(getString(obj, "DisplayName"))
	m.DynamicWatermarkDisplay = types.StringValue(getString(obj, "DynamicWatermarkDisplay"))
	m.EncryptionAipTemplateScopes = types.StringValue(getString(obj, "EncryptionAipTemplateScopes"))
	m.EncryptionContentExpiredOnDateInDaysOrNever = types.StringValue(getString(obj, "EncryptionContentExpiredOnDateInDaysOrNever"))
	m.EncryptionDisableAutomaticOwnerRights = types.StringValue(getString(obj, "EncryptionDisableAutomaticOwnerRights"))
	m.EncryptionDoNotForward = types.StringValue(getString(obj, "EncryptionDoNotForward"))
	m.EncryptionDoubleKeyEncryptionUrl = types.StringValue(getString(obj, "EncryptionDoubleKeyEncryptionUrl"))
	m.EncryptionEnabled = types.StringValue(getString(obj, "EncryptionEnabled"))
	m.EncryptionEncryptOnly = types.StringValue(getString(obj, "EncryptionEncryptOnly"))
	m.EncryptionLinkedTemplateId = types.StringValue(getString(obj, "EncryptionLinkedTemplateId"))
	m.EncryptionOfflineAccessDays = types.StringValue(getString(obj, "EncryptionOfflineAccessDays"))
	m.EncryptionPromptUser = types.StringValue(getString(obj, "EncryptionPromptUser"))
	m.EncryptionProtectionType = types.StringValue(getString(obj, "EncryptionProtectionType"))
	m.EncryptionRightsDefinitions = types.StringValue(getString(obj, "EncryptionRightsDefinitions"))
	m.EncryptionRightsUrl = types.StringValue(getString(obj, "EncryptionRightsUrl"))
	m.EncryptionTemplateId = types.StringValue(getString(obj, "EncryptionTemplateId"))
	m.InformationProtectionAttributeRequired = types.StringValue(getString(obj, "InformationProtectionAttributeRequired"))
	m.InheritToChildItems = types.StringValue(getString(obj, "InheritToChildItems"))
	m.IsLabelGroup = types.BoolValue(getBool(obj, "IsLabelGroup"))
	m.LabelActions = types.StringValue(getString(obj, "LabelActions"))
	m.LocaleSettings = types.StringValue(getString(obj, "LocaleSettings"))
	m.MigrationId = types.StringValue(getString(obj, "MigrationId"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.NextLabel = types.StringValue(getString(obj, "NextLabel"))
	m.ParentId = types.StringValue(getString(obj, "ParentId"))
	m.PreviousLabel = types.StringValue(getString(obj, "PreviousLabel"))
	m.Priority = types.StringValue(getString(obj, "Priority"))
	m.RemoveParentLink = types.BoolValue(getBool(obj, "RemoveParentLink"))
	m.RuleBlob = types.StringValue(getString(obj, "RuleBlob"))
	m.SchematizedDataCondition = types.StringValue(getString(obj, "SchematizedDataCondition"))
	m.Setting = types.StringValue(getString(obj, "Setting"))
	m.Settings = types.StringValue(getString(obj, "Settings"))
	m.SiteAndGroupProtectionAllowAccessToGuestUsers = types.StringValue(getString(obj, "SiteAndGroupProtectionAllowAccessToGuestUsers"))
	m.SiteAndGroupProtectionAllowEmailFromGuestUsers = types.StringValue(getString(obj, "SiteAndGroupProtectionAllowEmailFromGuestUsers"))
	m.SiteAndGroupProtectionAllowFullAccess = types.StringValue(getString(obj, "SiteAndGroupProtectionAllowFullAccess"))
	m.SiteAndGroupProtectionAllowLimitedAccess = types.StringValue(getString(obj, "SiteAndGroupProtectionAllowLimitedAccess"))
	m.SiteAndGroupProtectionBlockAccess = types.StringValue(getString(obj, "SiteAndGroupProtectionBlockAccess"))
	m.SiteAndGroupProtectionEnabled = types.StringValue(getString(obj, "SiteAndGroupProtectionEnabled"))
	m.SiteAndGroupProtectionLevel = types.StringValue(getString(obj, "SiteAndGroupProtectionLevel"))
	m.SiteAndGroupProtectionPrivacy = types.StringValue(getString(obj, "SiteAndGroupProtectionPrivacy"))
	m.SiteExternalSharingControlType = types.StringValue(getString(obj, "SiteExternalSharingControlType"))
	m.TeamsAllowMeetingChat = types.StringValue(getString(obj, "TeamsAllowMeetingChat"))
	m.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch = types.StringValue(getString(obj, "TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch"))
	m.TeamsAllowedPresenters = types.StringValue(getString(obj, "TeamsAllowedPresenters"))
	m.TeamsBypassLobbyForDialInUsers = types.StringValue(getString(obj, "TeamsBypassLobbyForDialInUsers"))
	m.TeamsChannelProtectionEnabled = types.StringValue(getString(obj, "TeamsChannelProtectionEnabled"))
	m.TeamsChannelSharedWithExternalTenants = types.StringValue(getString(obj, "TeamsChannelSharedWithExternalTenants"))
	m.TeamsChannelSharedWithPrivateTeamsOnly = types.StringValue(getString(obj, "TeamsChannelSharedWithPrivateTeamsOnly"))
	m.TeamsChannelSharedWithSameLabelOnly = types.StringValue(getString(obj, "TeamsChannelSharedWithSameLabelOnly"))
	m.TeamsCopyRestrictionEnforced = types.StringValue(getString(obj, "TeamsCopyRestrictionEnforced"))
	m.TeamsDetectSensitiveContentDuringScreenSharingEnabled = types.StringValue(getString(obj, "TeamsDetectSensitiveContentDuringScreenSharingEnabled"))
	m.TeamsDisableLobby = types.StringValue(getString(obj, "TeamsDisableLobby"))
	m.TeamsEndToEndEncryptionEnabled = types.StringValue(getString(obj, "TeamsEndToEndEncryptionEnabled"))
	m.TeamsLobbyBypassScope = types.StringValue(getString(obj, "TeamsLobbyBypassScope"))
	m.TeamsLobbyRestrictionEnforced = types.StringValue(getString(obj, "TeamsLobbyRestrictionEnforced"))
	m.TeamsPresentersRestrictionEnforced = types.StringValue(getString(obj, "TeamsPresentersRestrictionEnforced"))
	m.TeamsProtectionEnabled = types.StringValue(getString(obj, "TeamsProtectionEnabled"))
	m.TeamsRecordAutomatically = types.StringValue(getString(obj, "TeamsRecordAutomatically"))
	m.TeamsVideoWatermark = types.StringValue(getString(obj, "TeamsVideoWatermark"))
	m.TeamsWhoCanRecord = types.StringValue(getString(obj, "TeamsWhoCanRecord"))
	m.Tooltip = types.StringValue(getString(obj, "Tooltip"))
	_ = ctx
}

func (r *labelResource) reconcileState(cfg, read *labelModel) {
	read.AbacEnabled = reconcile.KeepStr(cfg.AbacEnabled, read.AbacEnabled)
	read.AdvancedSettings = reconcile.KeepStr(cfg.AdvancedSettings, read.AdvancedSettings)
	read.ApplyContentMarkingFooterAlignment = reconcile.KeepStr(cfg.ApplyContentMarkingFooterAlignment, read.ApplyContentMarkingFooterAlignment)
	read.ApplyContentMarkingFooterEnabled = reconcile.KeepStr(cfg.ApplyContentMarkingFooterEnabled, read.ApplyContentMarkingFooterEnabled)
	read.ApplyContentMarkingFooterFontColor = reconcile.KeepStr(cfg.ApplyContentMarkingFooterFontColor, read.ApplyContentMarkingFooterFontColor)
	read.ApplyContentMarkingFooterFontName = reconcile.KeepStr(cfg.ApplyContentMarkingFooterFontName, read.ApplyContentMarkingFooterFontName)
	read.ApplyContentMarkingFooterFontSize = reconcile.KeepStr(cfg.ApplyContentMarkingFooterFontSize, read.ApplyContentMarkingFooterFontSize)
	read.ApplyContentMarkingFooterMargin = reconcile.KeepStr(cfg.ApplyContentMarkingFooterMargin, read.ApplyContentMarkingFooterMargin)
	read.ApplyContentMarkingFooterText = reconcile.KeepStr(cfg.ApplyContentMarkingFooterText, read.ApplyContentMarkingFooterText)
	read.ApplyContentMarkingHeaderAlignment = reconcile.KeepStr(cfg.ApplyContentMarkingHeaderAlignment, read.ApplyContentMarkingHeaderAlignment)
	read.ApplyContentMarkingHeaderEnabled = reconcile.KeepStr(cfg.ApplyContentMarkingHeaderEnabled, read.ApplyContentMarkingHeaderEnabled)
	read.ApplyContentMarkingHeaderFontColor = reconcile.KeepStr(cfg.ApplyContentMarkingHeaderFontColor, read.ApplyContentMarkingHeaderFontColor)
	read.ApplyContentMarkingHeaderFontName = reconcile.KeepStr(cfg.ApplyContentMarkingHeaderFontName, read.ApplyContentMarkingHeaderFontName)
	read.ApplyContentMarkingHeaderFontSize = reconcile.KeepStr(cfg.ApplyContentMarkingHeaderFontSize, read.ApplyContentMarkingHeaderFontSize)
	read.ApplyContentMarkingHeaderMargin = reconcile.KeepStr(cfg.ApplyContentMarkingHeaderMargin, read.ApplyContentMarkingHeaderMargin)
	read.ApplyContentMarkingHeaderText = reconcile.KeepStr(cfg.ApplyContentMarkingHeaderText, read.ApplyContentMarkingHeaderText)
	read.ApplyDynamicWatermarkingEnabled = reconcile.KeepStr(cfg.ApplyDynamicWatermarkingEnabled, read.ApplyDynamicWatermarkingEnabled)
	read.ApplyMessageMetaData = reconcile.KeepStr(cfg.ApplyMessageMetaData, read.ApplyMessageMetaData)
	read.ApplyMessageMetaDataEnabled = reconcile.KeepStr(cfg.ApplyMessageMetaDataEnabled, read.ApplyMessageMetaDataEnabled)
	read.ApplyWaterMarkingEnabled = reconcile.KeepStr(cfg.ApplyWaterMarkingEnabled, read.ApplyWaterMarkingEnabled)
	read.ApplyWaterMarkingFontColor = reconcile.KeepStr(cfg.ApplyWaterMarkingFontColor, read.ApplyWaterMarkingFontColor)
	read.ApplyWaterMarkingFontName = reconcile.KeepStr(cfg.ApplyWaterMarkingFontName, read.ApplyWaterMarkingFontName)
	read.ApplyWaterMarkingFontSize = reconcile.KeepStr(cfg.ApplyWaterMarkingFontSize, read.ApplyWaterMarkingFontSize)
	read.ApplyWaterMarkingLayout = reconcile.KeepStr(cfg.ApplyWaterMarkingLayout, read.ApplyWaterMarkingLayout)
	read.ApplyWaterMarkingText = reconcile.KeepStr(cfg.ApplyWaterMarkingText, read.ApplyWaterMarkingText)
	read.ColumnAssetCondition = reconcile.KeepStr(cfg.ColumnAssetCondition, read.ColumnAssetCondition)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.ConditionalAccessAuthContext = reconcile.KeepStr(cfg.ConditionalAccessAuthContext, read.ConditionalAccessAuthContext)
	read.Conditions = reconcile.KeepStr(cfg.Conditions, read.Conditions)
	read.ContentType = reconcile.KeepStr(cfg.ContentType, read.ContentType)
	read.DefaultContentLabel = reconcile.KeepStr(cfg.DefaultContentLabel, read.DefaultContentLabel)
	read.DenyAccessEnabled = reconcile.KeepStr(cfg.DenyAccessEnabled, read.DenyAccessEnabled)
	read.DenyAccessExcludedPrincipals = reconcile.KeepStr(cfg.DenyAccessExcludedPrincipals, read.DenyAccessExcludedPrincipals)
	read.DenyAccessIncludedPrincipals = reconcile.KeepStr(cfg.DenyAccessIncludedPrincipals, read.DenyAccessIncludedPrincipals)
	read.DenyAccessRights = reconcile.KeepStr(cfg.DenyAccessRights, read.DenyAccessRights)
	read.DenyAccessWorkload = reconcile.KeepStr(cfg.DenyAccessWorkload, read.DenyAccessWorkload)
	read.DisplayName = reconcile.KeepStr(cfg.DisplayName, read.DisplayName)
	read.DynamicWatermarkDisplay = reconcile.KeepStr(cfg.DynamicWatermarkDisplay, read.DynamicWatermarkDisplay)
	read.EncryptionAipTemplateScopes = reconcile.KeepStr(cfg.EncryptionAipTemplateScopes, read.EncryptionAipTemplateScopes)
	read.EncryptionContentExpiredOnDateInDaysOrNever = reconcile.KeepStr(cfg.EncryptionContentExpiredOnDateInDaysOrNever, read.EncryptionContentExpiredOnDateInDaysOrNever)
	read.EncryptionDisableAutomaticOwnerRights = reconcile.KeepStr(cfg.EncryptionDisableAutomaticOwnerRights, read.EncryptionDisableAutomaticOwnerRights)
	read.EncryptionDoNotForward = reconcile.KeepStr(cfg.EncryptionDoNotForward, read.EncryptionDoNotForward)
	read.EncryptionDoubleKeyEncryptionUrl = reconcile.KeepStr(cfg.EncryptionDoubleKeyEncryptionUrl, read.EncryptionDoubleKeyEncryptionUrl)
	read.EncryptionEnabled = reconcile.KeepStr(cfg.EncryptionEnabled, read.EncryptionEnabled)
	read.EncryptionEncryptOnly = reconcile.KeepStr(cfg.EncryptionEncryptOnly, read.EncryptionEncryptOnly)
	read.EncryptionLinkedTemplateId = reconcile.KeepStr(cfg.EncryptionLinkedTemplateId, read.EncryptionLinkedTemplateId)
	read.EncryptionOfflineAccessDays = reconcile.KeepStr(cfg.EncryptionOfflineAccessDays, read.EncryptionOfflineAccessDays)
	read.EncryptionPromptUser = reconcile.KeepStr(cfg.EncryptionPromptUser, read.EncryptionPromptUser)
	read.EncryptionProtectionType = reconcile.KeepStr(cfg.EncryptionProtectionType, read.EncryptionProtectionType)
	read.EncryptionRightsDefinitions = reconcile.KeepStr(cfg.EncryptionRightsDefinitions, read.EncryptionRightsDefinitions)
	read.EncryptionRightsUrl = reconcile.KeepStr(cfg.EncryptionRightsUrl, read.EncryptionRightsUrl)
	read.EncryptionTemplateId = reconcile.KeepStr(cfg.EncryptionTemplateId, read.EncryptionTemplateId)
	read.InformationProtectionAttributeRequired = reconcile.KeepStr(cfg.InformationProtectionAttributeRequired, read.InformationProtectionAttributeRequired)
	read.InheritToChildItems = reconcile.KeepStr(cfg.InheritToChildItems, read.InheritToChildItems)
	read.IsLabelGroup = reconcile.KeepBool(cfg.IsLabelGroup, read.IsLabelGroup)
	read.LabelActions = reconcile.KeepStr(cfg.LabelActions, read.LabelActions)
	read.LocaleSettings = reconcile.KeepStr(cfg.LocaleSettings, read.LocaleSettings)
	read.MigrationId = reconcile.KeepStr(cfg.MigrationId, read.MigrationId)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.NextLabel = reconcile.KeepStr(cfg.NextLabel, read.NextLabel)
	read.ParentId = reconcile.KeepStr(cfg.ParentId, read.ParentId)
	read.PreviousLabel = reconcile.KeepStr(cfg.PreviousLabel, read.PreviousLabel)
	read.Priority = reconcile.KeepStr(cfg.Priority, read.Priority)
	read.RemoveParentLink = reconcile.KeepBool(cfg.RemoveParentLink, read.RemoveParentLink)
	read.RuleBlob = reconcile.KeepStr(cfg.RuleBlob, read.RuleBlob)
	read.SchematizedDataCondition = reconcile.KeepStr(cfg.SchematizedDataCondition, read.SchematizedDataCondition)
	read.Setting = reconcile.KeepStr(cfg.Setting, read.Setting)
	read.Settings = reconcile.KeepStr(cfg.Settings, read.Settings)
	read.SiteAndGroupProtectionAllowAccessToGuestUsers = reconcile.KeepStr(cfg.SiteAndGroupProtectionAllowAccessToGuestUsers, read.SiteAndGroupProtectionAllowAccessToGuestUsers)
	read.SiteAndGroupProtectionAllowEmailFromGuestUsers = reconcile.KeepStr(cfg.SiteAndGroupProtectionAllowEmailFromGuestUsers, read.SiteAndGroupProtectionAllowEmailFromGuestUsers)
	read.SiteAndGroupProtectionAllowFullAccess = reconcile.KeepStr(cfg.SiteAndGroupProtectionAllowFullAccess, read.SiteAndGroupProtectionAllowFullAccess)
	read.SiteAndGroupProtectionAllowLimitedAccess = reconcile.KeepStr(cfg.SiteAndGroupProtectionAllowLimitedAccess, read.SiteAndGroupProtectionAllowLimitedAccess)
	read.SiteAndGroupProtectionBlockAccess = reconcile.KeepStr(cfg.SiteAndGroupProtectionBlockAccess, read.SiteAndGroupProtectionBlockAccess)
	read.SiteAndGroupProtectionEnabled = reconcile.KeepStr(cfg.SiteAndGroupProtectionEnabled, read.SiteAndGroupProtectionEnabled)
	read.SiteAndGroupProtectionLevel = reconcile.KeepStr(cfg.SiteAndGroupProtectionLevel, read.SiteAndGroupProtectionLevel)
	read.SiteAndGroupProtectionPrivacy = reconcile.KeepStr(cfg.SiteAndGroupProtectionPrivacy, read.SiteAndGroupProtectionPrivacy)
	read.SiteExternalSharingControlType = reconcile.KeepStr(cfg.SiteExternalSharingControlType, read.SiteExternalSharingControlType)
	read.TeamsAllowMeetingChat = reconcile.KeepStr(cfg.TeamsAllowMeetingChat, read.TeamsAllowMeetingChat)
	read.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch = reconcile.KeepStr(cfg.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch, read.TeamsAllowPrivateTeamsToBeDiscoverableUsingSearch)
	read.TeamsAllowedPresenters = reconcile.KeepStr(cfg.TeamsAllowedPresenters, read.TeamsAllowedPresenters)
	read.TeamsBypassLobbyForDialInUsers = reconcile.KeepStr(cfg.TeamsBypassLobbyForDialInUsers, read.TeamsBypassLobbyForDialInUsers)
	read.TeamsChannelProtectionEnabled = reconcile.KeepStr(cfg.TeamsChannelProtectionEnabled, read.TeamsChannelProtectionEnabled)
	read.TeamsChannelSharedWithExternalTenants = reconcile.KeepStr(cfg.TeamsChannelSharedWithExternalTenants, read.TeamsChannelSharedWithExternalTenants)
	read.TeamsChannelSharedWithPrivateTeamsOnly = reconcile.KeepStr(cfg.TeamsChannelSharedWithPrivateTeamsOnly, read.TeamsChannelSharedWithPrivateTeamsOnly)
	read.TeamsChannelSharedWithSameLabelOnly = reconcile.KeepStr(cfg.TeamsChannelSharedWithSameLabelOnly, read.TeamsChannelSharedWithSameLabelOnly)
	read.TeamsCopyRestrictionEnforced = reconcile.KeepStr(cfg.TeamsCopyRestrictionEnforced, read.TeamsCopyRestrictionEnforced)
	read.TeamsDetectSensitiveContentDuringScreenSharingEnabled = reconcile.KeepStr(cfg.TeamsDetectSensitiveContentDuringScreenSharingEnabled, read.TeamsDetectSensitiveContentDuringScreenSharingEnabled)
	read.TeamsDisableLobby = reconcile.KeepStr(cfg.TeamsDisableLobby, read.TeamsDisableLobby)
	read.TeamsEndToEndEncryptionEnabled = reconcile.KeepStr(cfg.TeamsEndToEndEncryptionEnabled, read.TeamsEndToEndEncryptionEnabled)
	read.TeamsLobbyBypassScope = reconcile.KeepStr(cfg.TeamsLobbyBypassScope, read.TeamsLobbyBypassScope)
	read.TeamsLobbyRestrictionEnforced = reconcile.KeepStr(cfg.TeamsLobbyRestrictionEnforced, read.TeamsLobbyRestrictionEnforced)
	read.TeamsPresentersRestrictionEnforced = reconcile.KeepStr(cfg.TeamsPresentersRestrictionEnforced, read.TeamsPresentersRestrictionEnforced)
	read.TeamsProtectionEnabled = reconcile.KeepStr(cfg.TeamsProtectionEnabled, read.TeamsProtectionEnabled)
	read.TeamsRecordAutomatically = reconcile.KeepStr(cfg.TeamsRecordAutomatically, read.TeamsRecordAutomatically)
	read.TeamsVideoWatermark = reconcile.KeepStr(cfg.TeamsVideoWatermark, read.TeamsVideoWatermark)
	read.TeamsWhoCanRecord = reconcile.KeepStr(cfg.TeamsWhoCanRecord, read.TeamsWhoCanRecord)
	read.Tooltip = reconcile.KeepStr(cfg.Tooltip, read.Tooltip)
}
