// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &machineAssistedTagResourceResource{}
	_ resource.ResourceWithConfigure   = &machineAssistedTagResourceResource{}
	_ resource.ResourceWithImportState = &machineAssistedTagResourceResource{}
)

type machineAssistedTagResourceResource struct{ client *clients.Client }

// NewMachineAssistedTagResourceResource manages the MachineAssistedTagResource object (New-MachineAssistedTagResource / Get-MachineAssistedTagResource / Set-MachineAssistedTagResource / Remove-MachineAssistedTagResource).
func NewMachineAssistedTagResourceResource() resource.Resource {
	return &machineAssistedTagResourceResource{}
}

type machineAssistedTagResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Identity        types.String `tfsdk:"identity"`
	Description     types.String `tfsdk:"description"`
	DiscardModel    types.String `tfsdk:"discard_model"`
	Feedbacks       types.String `tfsdk:"feedbacks"`
	ModelId         types.String `tfsdk:"model_id"`
	ModelIds        types.String `tfsdk:"model_ids"`
	ModelName       types.String `tfsdk:"model_name"`
	Name            types.String `tfsdk:"name"`
	Resource        types.String `tfsdk:"resource"`
	ReviewCompleted types.String `tfsdk:"review_completed"`
	TaskId          types.String `tfsdk:"task_id"`
	TaskType        types.String `tfsdk:"task_type"`
	TrainingId      types.String `tfsdk:"training_id"`
	TrainingSite    types.String `tfsdk:"training_site"`
}

func (r *machineAssistedTagResourceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_machine_assisted_tag_resource"
}

func (r *machineAssistedTagResourceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the MachineAssistedTagResource object via New-MachineAssistedTagResource / Get-MachineAssistedTagResource / Set-MachineAssistedTagResource / Remove-MachineAssistedTagResource.",
		Attributes: map[string]schema.Attribute{
			"id":               schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":         schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"description":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Description parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"discard_model":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -DiscardModel parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"feedbacks":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Feedbacks parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"model_id":         schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ModelId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"model_ids":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ModelIds parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"model_name":       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ModelName parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":             schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"resource":         schema.StringAttribute{Required: true, Description: "Maps to the -Resource parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"review_completed": schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ReviewCompleted parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"task_id":          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TaskId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"task_type":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TaskType parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"training_id":      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TrainingId parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"training_site":    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -TrainingSite parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *machineAssistedTagResourceResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *machineAssistedTagResourceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan machineAssistedTagResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewMachineAssistedTagResourceParams{
		Description:  plan.Description.ValueString(),
		Name:         plan.Name.ValueString(),
		TrainingSite: plan.TrainingSite.ValueString(),
	}
	if v := plan.ModelIds.ValueString(); v != "" {
		p.ModelIds = v
	}
	if v := plan.Resource.ValueString(); v != "" {
		p.Resource = v
	}
	if v := plan.TaskId.ValueString(); v != "" {
		p.TaskId = v
	}
	if v := plan.TaskType.ValueString(); v != "" {
		p.TaskType = v
	}
	if v := plan.TrainingId.ValueString(); v != "" {
		p.TrainingId = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewMachineAssistedTagResource(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-MachineAssistedTagResource failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-MachineAssistedTagResource returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readMachineAssistedTagResource(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *machineAssistedTagResourceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state machineAssistedTagResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *machineAssistedTagResourceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state machineAssistedTagResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetMachineAssistedTagResourceParams{}
	sp.Identity = id
	sp.DiscardModel = plan.DiscardModel.ValueString()
	sp.Feedbacks = plan.Feedbacks.ValueString()
	if v := plan.ModelId.ValueString(); v != "" {
		sp.ModelId = v
	}
	sp.ModelName = plan.ModelName.ValueString()
	sp.ReviewCompleted = plan.ReviewCompleted.ValueString()
	if v := plan.TaskId.ValueString(); v != "" {
		sp.TaskId = v
	}
	if v := plan.TrainingId.ValueString(); v != "" {
		sp.TrainingId = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetMachineAssistedTagResource(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-MachineAssistedTagResource failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"DiscardModel":    cfg.DiscardModel,
		"Feedbacks":       cfg.Feedbacks,
		"ModelId":         cfg.ModelId,
		"ModelName":       cfg.ModelName,
		"ReviewCompleted": cfg.ReviewCompleted,
		"TaskId":          cfg.TaskId,
		"TrainingId":      cfg.TrainingId,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *machineAssistedTagResourceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state machineAssistedTagResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveMachineAssistedTagResource(ctx, purview.RemoveMachineAssistedTagResourceParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-MachineAssistedTagResource failed", err.Error())
		}
	}
}

func (r *machineAssistedTagResourceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *machineAssistedTagResourceResource) identityOf(m machineAssistedTagResourceModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *machineAssistedTagResourceResource) refresh(ctx context.Context, identity string, m *machineAssistedTagResourceModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetMachineAssistedTagResource(ctx, purview.GetMachineAssistedTagResourceParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-MachineAssistedTagResource failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readMachineAssistedTagResource(ctx, obj, m)
	return true
}

func readMachineAssistedTagResource(ctx context.Context, obj map[string]any, m *machineAssistedTagResourceModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.Description = types.StringValue(getString(obj, "Description"))
	m.DiscardModel = types.StringValue(getString(obj, "DiscardModel"))
	m.Feedbacks = types.StringValue(getString(obj, "Feedbacks"))
	m.ModelId = types.StringValue(getString(obj, "ModelId"))
	m.ModelIds = types.StringValue(getString(obj, "ModelIds"))
	m.ModelName = types.StringValue(getString(obj, "ModelName"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.Resource = types.StringValue(getString(obj, "Resource"))
	m.ReviewCompleted = types.StringValue(getString(obj, "ReviewCompleted"))
	m.TaskId = types.StringValue(getString(obj, "TaskId"))
	m.TaskType = types.StringValue(getString(obj, "TaskType"))
	m.TrainingId = types.StringValue(getString(obj, "TrainingId"))
	m.TrainingSite = types.StringValue(getString(obj, "TrainingSite"))
	_ = ctx
}

func (r *machineAssistedTagResourceResource) reconcileState(cfg, read *machineAssistedTagResourceModel) {
	read.Description = reconcile.KeepStr(cfg.Description, read.Description)
	read.DiscardModel = reconcile.KeepStr(cfg.DiscardModel, read.DiscardModel)
	read.Feedbacks = reconcile.KeepStr(cfg.Feedbacks, read.Feedbacks)
	read.ModelId = reconcile.KeepStr(cfg.ModelId, read.ModelId)
	read.ModelIds = reconcile.KeepStr(cfg.ModelIds, read.ModelIds)
	read.ModelName = reconcile.KeepStr(cfg.ModelName, read.ModelName)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.Resource = reconcile.KeepStr(cfg.Resource, read.Resource)
	read.ReviewCompleted = reconcile.KeepStr(cfg.ReviewCompleted, read.ReviewCompleted)
	read.TaskId = reconcile.KeepStr(cfg.TaskId, read.TaskId)
	read.TaskType = reconcile.KeepStr(cfg.TaskType, read.TaskType)
	read.TrainingId = reconcile.KeepStr(cfg.TrainingId, read.TrainingId)
	read.TrainingSite = reconcile.KeepStr(cfg.TrainingSite, read.TrainingSite)
}
