// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &organizationSegmentListDataSource{}
	_ datasource.DataSourceWithConfigure = &organizationSegmentListDataSource{}
)

type organizationSegmentListDataSource struct{ client *clients.Client }

// NewOrganizationSegmentListDataSource lists every OrganizationSegment object (Get-OrganizationSegment).
func NewOrganizationSegmentListDataSource() datasource.DataSource {
	return &organizationSegmentListDataSource{}
}

type organizationSegmentListModel struct {
	Items []organizationSegmentModel `tfsdk:"organization_segments"`
}

func (d *organizationSegmentListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization_segments"
}

func (d *organizationSegmentListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every OrganizationSegment object (Get-OrganizationSegment).",
		Attributes: map[string]schema.Attribute{
			"organization_segments": schema.ListNestedAttribute{Computed: true, Description: "All OrganizationSegment objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":          schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"name":              schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"user_group_filter": schema.StringAttribute{Computed: true, Description: "Maps to the -UserGroupFilter parameter."},
			}}},
		},
	}
}

func (d *organizationSegmentListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *organizationSegmentListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetOrganizationSegment(ctx, purview.GetOrganizationSegmentParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-OrganizationSegment failed", err.Error())
		return
	}
	var data organizationSegmentListModel
	for _, obj := range res.Value {
		var e organizationSegmentModel
		readOrganizationSegment(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
