// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &privacyManagementComplianceTagListDataSource{}
	_ datasource.DataSourceWithConfigure = &privacyManagementComplianceTagListDataSource{}
)

type privacyManagementComplianceTagListDataSource struct{ client *clients.Client }

// NewPrivacyManagementComplianceTagListDataSource lists every PrivacyManagementComplianceTag object (Get-PrivacyManagementComplianceTag).
func NewPrivacyManagementComplianceTagListDataSource() datasource.DataSource {
	return &privacyManagementComplianceTagListDataSource{}
}

type privacyManagementComplianceTagListModel struct {
	Items []privacyManagementComplianceTagModel `tfsdk:"privacy_management_compliance_tags"`
}

func (d *privacyManagementComplianceTagListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_privacy_management_compliance_tags"
}

func (d *privacyManagementComplianceTagListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every PrivacyManagementComplianceTag object (Get-PrivacyManagementComplianceTag).",
		Attributes: map[string]schema.Attribute{
			"privacy_management_compliance_tags": schema.ListNestedAttribute{Computed: true, Description: "All PrivacyManagementComplianceTag objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":           schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"comment":            schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"name":               schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"retention_action":   schema.StringAttribute{Computed: true, Description: "Maps to the -RetentionAction parameter."},
				"retention_duration": schema.StringAttribute{Computed: true, Description: "Maps to the -RetentionDuration parameter."},
			}}},
		},
	}
}

func (d *privacyManagementComplianceTagListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *privacyManagementComplianceTagListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetPrivacyManagementComplianceTag(ctx, purview.GetPrivacyManagementComplianceTagParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-PrivacyManagementComplianceTag failed", err.Error())
		return
	}
	var data privacyManagementComplianceTagListModel
	for _, obj := range res.Value {
		var e privacyManagementComplianceTagModel
		readPrivacyManagementComplianceTag(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
