// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &protectionAlertDataSource{}
	_ datasource.DataSourceWithConfigure = &protectionAlertDataSource{}
)

type protectionAlertDataSource struct{ client *clients.Client }

// NewProtectionAlertDataSource looks up a ProtectionAlert object (Get-ProtectionAlert).
func NewProtectionAlertDataSource() datasource.DataSource { return &protectionAlertDataSource{} }

func (d *protectionAlertDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_protection_alert"
}

func (d *protectionAlertDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing ProtectionAlert object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                  schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                            schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"aggregation_type":                    schema.StringAttribute{Computed: true, Description: "Maps to the -AggregationType parameter."},
			"alert_by":                            schema.StringAttribute{Computed: true, Description: "Maps to the -AlertBy parameter."},
			"alert_for":                           schema.StringAttribute{Computed: true, Description: "Maps to the -AlertFor parameter."},
			"category":                            schema.StringAttribute{Computed: true, Description: "Maps to the -Category parameter."},
			"comment":                             schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"correlation_policy_id":               schema.StringAttribute{Computed: true, Description: "Maps to the -CorrelationPolicyId parameter."},
			"custom_properties":                   schema.StringAttribute{Computed: true, Description: "Maps to the -CustomProperties parameter."},
			"description":                         schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
			"disabled":                            schema.BoolAttribute{Computed: true, Description: "Maps to the -Disabled parameter."},
			"external_scenario_data":              schema.StringAttribute{Computed: true, Description: "Maps to the -ExternalScenarioData parameter."},
			"filter":                              schema.StringAttribute{Computed: true, Description: "Maps to the -Filter parameter."},
			"logical_operation_name":              schema.StringAttribute{Computed: true, Description: "Maps to the -LogicalOperationName parameter."},
			"name":                                schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"notification_culture":                schema.StringAttribute{Computed: true, Description: "Maps to the -NotificationCulture parameter."},
			"notification_enabled":                schema.BoolAttribute{Computed: true, Description: "Maps to the -NotificationEnabled parameter."},
			"notify_user":                         schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUser parameter."},
			"notify_user_on_filter_match":         schema.BoolAttribute{Computed: true, Description: "Maps to the -NotifyUserOnFilterMatch parameter."},
			"notify_user_suppression_expiry_date": schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUserSuppressionExpiryDate parameter."},
			"notify_user_throttle_threshold":      schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUserThrottleThreshold parameter."},
			"notify_user_throttle_window":         schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUserThrottleWindow parameter."},
			"operation":                           schema.StringAttribute{Computed: true, Description: "Maps to the -Operation parameter."},
			"privacy_management_scoped_sensitive_information_types":              schema.StringAttribute{Computed: true, Description: "Maps to the -PrivacyManagementScopedSensitiveInformationTypes parameter."},
			"privacy_management_scoped_sensitive_information_types_for_counting": schema.StringAttribute{Computed: true, Description: "Maps to the -PrivacyManagementScopedSensitiveInformationTypesForCounting parameter."},
			"privacy_management_scoped_sensitive_information_types_threshold":    schema.StringAttribute{Computed: true, Description: "Maps to the -PrivacyManagementScopedSensitiveInformationTypesThreshold parameter."},
			"severity":              schema.StringAttribute{Computed: true, Description: "Maps to the -Severity parameter."},
			"stream_type":           schema.StringAttribute{Computed: true, Description: "Maps to the -StreamType parameter."},
			"threat_type":           schema.StringAttribute{Computed: true, Description: "Maps to the -ThreatType parameter."},
			"threshold":             schema.StringAttribute{Computed: true, Description: "Maps to the -Threshold parameter."},
			"time_window":           schema.StringAttribute{Computed: true, Description: "Maps to the -TimeWindow parameter."},
			"use_created_date_time": schema.StringAttribute{Computed: true, Description: "Maps to the -UseCreatedDateTime parameter."},
			"volume_threshold":      schema.StringAttribute{Computed: true, Description: "Maps to the -VolumeThreshold parameter."},
		},
	}
}

func (d *protectionAlertDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *protectionAlertDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data protectionAlertModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetProtectionAlert(ctx, purview.GetProtectionAlertParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-ProtectionAlert failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("ProtectionAlert not found", "no ProtectionAlert object for identity "+identity)
		return
	}
	readProtectionAlert(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
