// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &protectionAlertListDataSource{}
	_ datasource.DataSourceWithConfigure = &protectionAlertListDataSource{}
)

type protectionAlertListDataSource struct{ client *clients.Client }

// NewProtectionAlertListDataSource lists every ProtectionAlert object (Get-ProtectionAlert).
func NewProtectionAlertListDataSource() datasource.DataSource {
	return &protectionAlertListDataSource{}
}

type protectionAlertListModel struct {
	Items []protectionAlertModel `tfsdk:"protection_alerts"`
}

func (d *protectionAlertListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_protection_alerts"
}

func (d *protectionAlertListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ProtectionAlert object (Get-ProtectionAlert).",
		Attributes: map[string]schema.Attribute{
			"protection_alerts": schema.ListNestedAttribute{Computed: true, Description: "All ProtectionAlert objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                                  schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                            schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"aggregation_type":                    schema.StringAttribute{Computed: true, Description: "Maps to the -AggregationType parameter."},
				"alert_by":                            schema.StringAttribute{Computed: true, Description: "Maps to the -AlertBy parameter."},
				"alert_for":                           schema.StringAttribute{Computed: true, Description: "Maps to the -AlertFor parameter."},
				"category":                            schema.StringAttribute{Computed: true, Description: "Maps to the -Category parameter."},
				"comment":                             schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"correlation_policy_id":               schema.StringAttribute{Computed: true, Description: "Maps to the -CorrelationPolicyId parameter."},
				"custom_properties":                   schema.StringAttribute{Computed: true, Description: "Maps to the -CustomProperties parameter."},
				"description":                         schema.StringAttribute{Computed: true, Description: "Maps to the -Description parameter."},
				"disabled":                            schema.BoolAttribute{Computed: true, Description: "Maps to the -Disabled parameter."},
				"external_scenario_data":              schema.StringAttribute{Computed: true, Description: "Maps to the -ExternalScenarioData parameter."},
				"filter":                              schema.StringAttribute{Computed: true, Description: "Maps to the -Filter parameter."},
				"logical_operation_name":              schema.StringAttribute{Computed: true, Description: "Maps to the -LogicalOperationName parameter."},
				"name":                                schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"notification_culture":                schema.StringAttribute{Computed: true, Description: "Maps to the -NotificationCulture parameter."},
				"notification_enabled":                schema.BoolAttribute{Computed: true, Description: "Maps to the -NotificationEnabled parameter."},
				"notify_user":                         schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUser parameter."},
				"notify_user_on_filter_match":         schema.BoolAttribute{Computed: true, Description: "Maps to the -NotifyUserOnFilterMatch parameter."},
				"notify_user_suppression_expiry_date": schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUserSuppressionExpiryDate parameter."},
				"notify_user_throttle_threshold":      schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUserThrottleThreshold parameter."},
				"notify_user_throttle_window":         schema.StringAttribute{Computed: true, Description: "Maps to the -NotifyUserThrottleWindow parameter."},
				"operation":                           schema.StringAttribute{Computed: true, Description: "Maps to the -Operation parameter."},
				"privacy_management_scoped_sensitive_information_types":              schema.StringAttribute{Computed: true, Description: "Maps to the -PrivacyManagementScopedSensitiveInformationTypes parameter."},
				"privacy_management_scoped_sensitive_information_types_for_counting": schema.StringAttribute{Computed: true, Description: "Maps to the -PrivacyManagementScopedSensitiveInformationTypesForCounting parameter."},
				"privacy_management_scoped_sensitive_information_types_threshold":    schema.StringAttribute{Computed: true, Description: "Maps to the -PrivacyManagementScopedSensitiveInformationTypesThreshold parameter."},
				"severity":              schema.StringAttribute{Computed: true, Description: "Maps to the -Severity parameter."},
				"stream_type":           schema.StringAttribute{Computed: true, Description: "Maps to the -StreamType parameter."},
				"threat_type":           schema.StringAttribute{Computed: true, Description: "Maps to the -ThreatType parameter."},
				"threshold":             schema.StringAttribute{Computed: true, Description: "Maps to the -Threshold parameter."},
				"time_window":           schema.StringAttribute{Computed: true, Description: "Maps to the -TimeWindow parameter."},
				"use_created_date_time": schema.StringAttribute{Computed: true, Description: "Maps to the -UseCreatedDateTime parameter."},
				"volume_threshold":      schema.StringAttribute{Computed: true, Description: "Maps to the -VolumeThreshold parameter."},
			}}},
		},
	}
}

func (d *protectionAlertListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *protectionAlertListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetProtectionAlert(ctx, purview.GetProtectionAlertParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ProtectionAlert failed", err.Error())
		return
	}
	var data protectionAlertListModel
	for _, obj := range res.Value {
		var e protectionAlertModel
		readProtectionAlert(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
