// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &retentionComplianceRuleResource{}
	_ resource.ResourceWithConfigure   = &retentionComplianceRuleResource{}
	_ resource.ResourceWithImportState = &retentionComplianceRuleResource{}
)

type retentionComplianceRuleResource struct{ client *clients.Client }

// NewRetentionComplianceRuleResource manages the RetentionComplianceRule object (New-RetentionComplianceRule / Get-RetentionComplianceRule / Set-RetentionComplianceRule / Remove-RetentionComplianceRule).
func NewRetentionComplianceRuleResource() resource.Resource {
	return &retentionComplianceRuleResource{}
}

type retentionComplianceRuleModel struct {
	ID                                  types.String `tfsdk:"id"`
	Identity                            types.String `tfsdk:"identity"`
	ApplyComplianceTag                  types.String `tfsdk:"apply_compliance_tag"`
	ArchiveEnabled                      types.Bool   `tfsdk:"archive_enabled"`
	ArchiveTriggerBasedOn               types.String `tfsdk:"archive_trigger_based_on"`
	ArchiveTriggerInDays                types.String `tfsdk:"archive_trigger_in_days"`
	Comment                             types.String `tfsdk:"comment"`
	ContentContainsSensitiveInformation types.Set    `tfsdk:"content_contains_sensitive_information"`
	ContentDateFrom                     types.String `tfsdk:"content_date_from"`
	ContentDateTo                       types.String `tfsdk:"content_date_to"`
	ContentMatchQuery                   types.String `tfsdk:"content_match_query"`
	ExcludedItemClasses                 types.String `tfsdk:"excluded_item_classes"`
	ExpirationDateOption                types.String `tfsdk:"expiration_date_option"`
	IRMRiskyUserProfiles                types.String `tfsdk:"irm_risky_user_profiles"`
	MachineLearningModelIDs             types.String `tfsdk:"machine_learning_model_i_ds"`
	Name                                types.String `tfsdk:"name"`
	Policy                              types.String `tfsdk:"policy"`
	PublishComplianceTag                types.String `tfsdk:"publish_compliance_tag"`
	RetentionComplianceAction           types.String `tfsdk:"retention_compliance_action"`
	RetentionDuration                   types.String `tfsdk:"retention_duration"`
	RetentionDurationDisplayHint        types.String `tfsdk:"retention_duration_display_hint"`
}

func (r *retentionComplianceRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_retention_compliance_rule"
}

func (r *retentionComplianceRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the RetentionComplianceRule object via New-RetentionComplianceRule / Get-RetentionComplianceRule / Set-RetentionComplianceRule / Remove-RetentionComplianceRule.",
		Attributes: map[string]schema.Attribute{
			"id":                                     schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                               schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"apply_compliance_tag":                   schema.StringAttribute{Required: true, Description: "Maps to the -ApplyComplianceTag parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"archive_enabled":                        schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -ArchiveEnabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"archive_trigger_based_on":               schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ArchiveTriggerBasedOn parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"archive_trigger_in_days":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ArchiveTriggerInDays parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"comment":                                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"content_contains_sensitive_information": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -ContentContainsSensitiveInformation parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"content_date_from":                      schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ContentDateFrom parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"content_date_to":                        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ContentDateTo parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"content_match_query":                    schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ContentMatchQuery parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"excluded_item_classes":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExcludedItemClasses parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"expiration_date_option":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -ExpirationDateOption parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"irm_risky_user_profiles":                schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -IRMRiskyUserProfiles parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"machine_learning_model_i_ds":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -MachineLearningModelIDs parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()}},
			"name":                                   schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"policy":                                 schema.StringAttribute{Required: true, Description: "Maps to the -Policy parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"publish_compliance_tag":                 schema.StringAttribute{Required: true, Description: "Maps to the -PublishComplianceTag parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"retention_compliance_action":            schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RetentionComplianceAction parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"retention_duration":                     schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RetentionDuration parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"retention_duration_display_hint":        schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -RetentionDurationDisplayHint parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *retentionComplianceRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *retentionComplianceRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan retentionComplianceRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewRetentionComplianceRuleParams{
		ApplyComplianceTag:                  plan.ApplyComplianceTag.ValueString(),
		ArchiveEnabled:                      plan.ArchiveEnabled.ValueBool(),
		ArchiveTriggerBasedOn:               plan.ArchiveTriggerBasedOn.ValueString(),
		Comment:                             plan.Comment.ValueString(),
		ContentContainsSensitiveInformation: toStringSlice(ctx, plan.ContentContainsSensitiveInformation, &resp.Diagnostics),
		ContentMatchQuery:                   plan.ContentMatchQuery.ValueString(),
		ExpirationDateOption:                plan.ExpirationDateOption.ValueString(),
		Name:                                plan.Name.ValueString(),
		PublishComplianceTag:                plan.PublishComplianceTag.ValueString(),
		RetentionComplianceAction:           plan.RetentionComplianceAction.ValueString(),
	}
	if v := plan.ArchiveTriggerInDays.ValueString(); v != "" {
		p.ArchiveTriggerInDays = v
	}
	if v := plan.ExcludedItemClasses.ValueString(); v != "" {
		p.ExcludedItemClasses = v
	}
	if v := plan.IRMRiskyUserProfiles.ValueString(); v != "" {
		p.IRMRiskyUserProfiles = v
	}
	if v := plan.MachineLearningModelIDs.ValueString(); v != "" {
		p.MachineLearningModelIDs = v
	}
	if v := plan.Policy.ValueString(); v != "" {
		p.Policy = v
	}
	if v := plan.RetentionDuration.ValueString(); v != "" {
		p.RetentionDuration = v
	}
	if v := plan.RetentionDurationDisplayHint.ValueString(); v != "" {
		p.RetentionDurationDisplayHint = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewRetentionComplianceRule(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-RetentionComplianceRule failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-RetentionComplianceRule returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readRetentionComplianceRule(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *retentionComplianceRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state retentionComplianceRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *retentionComplianceRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state retentionComplianceRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetRetentionComplianceRuleParams{}
	sp.Identity = id
	sp.ArchiveEnabled = plan.ArchiveEnabled.ValueBool()
	sp.ArchiveTriggerBasedOn = plan.ArchiveTriggerBasedOn.ValueString()
	if v := plan.ArchiveTriggerInDays.ValueString(); v != "" {
		sp.ArchiveTriggerInDays = v
	}
	sp.Comment = plan.Comment.ValueString()
	sp.ContentContainsSensitiveInformation = toStringSlice(ctx, plan.ContentContainsSensitiveInformation, &resp.Diagnostics)
	if v := plan.ContentDateFrom.ValueString(); v != "" {
		sp.ContentDateFrom = v
	}
	if v := plan.ContentDateTo.ValueString(); v != "" {
		sp.ContentDateTo = v
	}
	sp.ContentMatchQuery = plan.ContentMatchQuery.ValueString()
	if v := plan.ExcludedItemClasses.ValueString(); v != "" {
		sp.ExcludedItemClasses = v
	}
	sp.ExpirationDateOption = plan.ExpirationDateOption.ValueString()
	if v := plan.IRMRiskyUserProfiles.ValueString(); v != "" {
		sp.IRMRiskyUserProfiles = v
	}
	sp.RetentionComplianceAction = plan.RetentionComplianceAction.ValueString()
	if v := plan.RetentionDuration.ValueString(); v != "" {
		sp.RetentionDuration = v
	}
	if v := plan.RetentionDurationDisplayHint.ValueString(); v != "" {
		sp.RetentionDurationDisplayHint = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetRetentionComplianceRule(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-RetentionComplianceRule failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"ArchiveTriggerBasedOn":        cfg.ArchiveTriggerBasedOn,
		"ArchiveTriggerInDays":         cfg.ArchiveTriggerInDays,
		"Comment":                      cfg.Comment,
		"ContentDateFrom":              cfg.ContentDateFrom,
		"ContentDateTo":                cfg.ContentDateTo,
		"ContentMatchQuery":            cfg.ContentMatchQuery,
		"ExcludedItemClasses":          cfg.ExcludedItemClasses,
		"ExpirationDateOption":         cfg.ExpirationDateOption,
		"IRMRiskyUserProfiles":         cfg.IRMRiskyUserProfiles,
		"RetentionComplianceAction":    cfg.RetentionComplianceAction,
		"RetentionDuration":            cfg.RetentionDuration,
		"RetentionDurationDisplayHint": cfg.RetentionDurationDisplayHint,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *retentionComplianceRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state retentionComplianceRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveRetentionComplianceRule(ctx, purview.RemoveRetentionComplianceRuleParams{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-RetentionComplianceRule failed", err.Error())
		}
	}
}

func (r *retentionComplianceRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *retentionComplianceRuleResource) identityOf(m retentionComplianceRuleModel) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *retentionComplianceRuleResource) refresh(ctx context.Context, identity string, m *retentionComplianceRuleModel, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetRetentionComplianceRule(ctx, purview.GetRetentionComplianceRuleParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-RetentionComplianceRule failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readRetentionComplianceRule(ctx, obj, m)
	return true
}

func readRetentionComplianceRule(ctx context.Context, obj map[string]any, m *retentionComplianceRuleModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.ApplyComplianceTag = types.StringValue(getString(obj, "ApplyComplianceTag"))
	m.ArchiveEnabled = types.BoolValue(getBool(obj, "ArchiveEnabled"))
	m.ArchiveTriggerBasedOn = types.StringValue(getString(obj, "ArchiveTriggerBasedOn"))
	m.ArchiveTriggerInDays = types.StringValue(getString(obj, "ArchiveTriggerInDays"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.ContentContainsSensitiveInformation = stringSetValue(ctx, getStringSlice(obj, "ContentContainsSensitiveInformation"))
	m.ContentDateFrom = types.StringValue(getString(obj, "ContentDateFrom"))
	m.ContentDateTo = types.StringValue(getString(obj, "ContentDateTo"))
	m.ContentMatchQuery = types.StringValue(getString(obj, "ContentMatchQuery"))
	m.ExcludedItemClasses = types.StringValue(getString(obj, "ExcludedItemClasses"))
	m.ExpirationDateOption = types.StringValue(getString(obj, "ExpirationDateOption"))
	m.IRMRiskyUserProfiles = types.StringValue(getString(obj, "IRMRiskyUserProfiles"))
	m.MachineLearningModelIDs = types.StringValue(getString(obj, "MachineLearningModelIDs"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.Policy = types.StringValue(getString(obj, "Policy"))
	m.PublishComplianceTag = types.StringValue(getString(obj, "PublishComplianceTag"))
	m.RetentionComplianceAction = types.StringValue(getString(obj, "RetentionComplianceAction"))
	m.RetentionDuration = types.StringValue(getString(obj, "RetentionDuration"))
	m.RetentionDurationDisplayHint = types.StringValue(getString(obj, "RetentionDurationDisplayHint"))
	_ = ctx
}

func (r *retentionComplianceRuleResource) reconcileState(cfg, read *retentionComplianceRuleModel) {
	read.ApplyComplianceTag = reconcile.KeepStr(cfg.ApplyComplianceTag, read.ApplyComplianceTag)
	read.ArchiveEnabled = reconcile.KeepBool(cfg.ArchiveEnabled, read.ArchiveEnabled)
	read.ArchiveTriggerBasedOn = reconcile.KeepStr(cfg.ArchiveTriggerBasedOn, read.ArchiveTriggerBasedOn)
	read.ArchiveTriggerInDays = reconcile.KeepStr(cfg.ArchiveTriggerInDays, read.ArchiveTriggerInDays)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.ContentContainsSensitiveInformation = reconcile.KeepSet(cfg.ContentContainsSensitiveInformation, read.ContentContainsSensitiveInformation)
	read.ContentDateFrom = reconcile.KeepStr(cfg.ContentDateFrom, read.ContentDateFrom)
	read.ContentDateTo = reconcile.KeepStr(cfg.ContentDateTo, read.ContentDateTo)
	read.ContentMatchQuery = reconcile.KeepStr(cfg.ContentMatchQuery, read.ContentMatchQuery)
	read.ExcludedItemClasses = reconcile.KeepStr(cfg.ExcludedItemClasses, read.ExcludedItemClasses)
	read.ExpirationDateOption = reconcile.KeepStr(cfg.ExpirationDateOption, read.ExpirationDateOption)
	read.IRMRiskyUserProfiles = reconcile.KeepStr(cfg.IRMRiskyUserProfiles, read.IRMRiskyUserProfiles)
	read.MachineLearningModelIDs = reconcile.KeepStr(cfg.MachineLearningModelIDs, read.MachineLearningModelIDs)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.Policy = reconcile.KeepStr(cfg.Policy, read.Policy)
	read.PublishComplianceTag = reconcile.KeepStr(cfg.PublishComplianceTag, read.PublishComplianceTag)
	read.RetentionComplianceAction = reconcile.KeepStr(cfg.RetentionComplianceAction, read.RetentionComplianceAction)
	read.RetentionDuration = reconcile.KeepStr(cfg.RetentionDuration, read.RetentionDuration)
	read.RetentionDurationDisplayHint = reconcile.KeepStr(cfg.RetentionDurationDisplayHint, read.RetentionDurationDisplayHint)
}
