// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &roleGroupDataSource{}
	_ datasource.DataSourceWithConfigure = &roleGroupDataSource{}
)

type roleGroupDataSource struct{ client *clients.Client }

// NewRoleGroupDataSource looks up a RoleGroup object (Get-RoleGroup).
func NewRoleGroupDataSource() datasource.DataSource { return &roleGroupDataSource{} }

func (d *roleGroupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_role_group"
}

func (d *roleGroupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing RoleGroup object. Set identity to select it.",
		Attributes: map[string]schema.Attribute{
			"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":     schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"name":         schema.StringAttribute{Computed: true, Description: "Name of the object."},
			"display_name": schema.StringAttribute{Computed: true, Description: "Display name of the object."},
			"json":         schema.StringAttribute{Computed: true, Description: "The full object encoded as JSON; decode with jsondecode()."},
		},
	}
}

func (d *roleGroupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *roleGroupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data roleGroupModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetRoleGroup(ctx, purview.GetRoleGroupParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-RoleGroup failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("RoleGroup not found", "no RoleGroup object for identity "+identity)
		return
	}
	readRoleGroup(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type roleGroupModel struct {
	ID          types.String `tfsdk:"id"`
	Identity    types.String `tfsdk:"identity"`
	Name        types.String `tfsdk:"name"`
	DisplayName types.String `tfsdk:"display_name"`
	JSON        types.String `tfsdk:"json"`
}

func readRoleGroup(ctx context.Context, obj map[string]any, m *roleGroupModel) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Name")))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.DisplayName = types.StringValue(getString(obj, "DisplayName"))
	m.JSON = types.StringValue(toJSON(obj))
	_ = ctx
}
