// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &scopeAdminsListDataSource{}
	_ datasource.DataSourceWithConfigure = &scopeAdminsListDataSource{}
)

type scopeAdminsListDataSource struct{ client *clients.Client }

// NewScopeAdminsListDataSource lists every ScopeAdmins object (Get-ScopeAdmins).
func NewScopeAdminsListDataSource() datasource.DataSource { return &scopeAdminsListDataSource{} }

type scopeAdminsListModel struct {
	Items []scopeAdminsModel `tfsdk:"scope_adminses"`
}

func (d *scopeAdminsListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_scope_adminses"
}

func (d *scopeAdminsListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ScopeAdmins object (Get-ScopeAdmins).",
		Attributes: map[string]schema.Attribute{
			"scope_adminses": schema.ListNestedAttribute{Computed: true, Description: "All ScopeAdmins objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":           schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":     schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"name":         schema.StringAttribute{Computed: true, Description: "Name of the object."},
				"display_name": schema.StringAttribute{Computed: true, Description: "Display name of the object."},
				"json":         schema.StringAttribute{Computed: true, Description: "The full object encoded as JSON; decode with jsondecode()."},
			}}},
		},
	}
}

func (d *scopeAdminsListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *scopeAdminsListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetScopeAdmins(ctx, purview.GetScopeAdminsParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ScopeAdmins failed", err.Error())
		return
	}
	var data scopeAdminsListModel
	for _, obj := range res.Value {
		var e scopeAdminsModel
		readScopeAdmins(ctx, obj, &e)
		e.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
