// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &sensitiveInformationScanRuleDataSource{}
	_ datasource.DataSourceWithConfigure = &sensitiveInformationScanRuleDataSource{}
)

type sensitiveInformationScanRuleDataSource struct{ client *clients.Client }

// NewSensitiveInformationScanRuleDataSource looks up a SensitiveInformationScanRule object (Get-SensitiveInformationScanRule).
func NewSensitiveInformationScanRuleDataSource() datasource.DataSource {
	return &sensitiveInformationScanRuleDataSource{}
}

func (d *sensitiveInformationScanRuleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sensitive_information_scan_rule"
}

func (d *sensitiveInformationScanRuleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing SensitiveInformationScanRule object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                                                   schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                                             schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"comment":                                              schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"content_contains_sensitive_information":               schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ContentContainsSensitiveInformation parameter."},
			"content_created_or_updated_date_from":                 schema.StringAttribute{Computed: true, Description: "Maps to the -ContentCreatedOrUpdatedDateFrom parameter."},
			"content_created_or_updated_date_to":                   schema.StringAttribute{Computed: true, Description: "Maps to the -ContentCreatedOrUpdatedDateTo parameter."},
			"content_extension_matches_words":                      schema.StringAttribute{Computed: true, Description: "Maps to the -ContentExtensionMatchesWords parameter."},
			"content_is_not_labeled":                               schema.BoolAttribute{Computed: true, Description: "Maps to the -ContentIsNotLabeled parameter."},
			"content_property_contains_words":                      schema.StringAttribute{Computed: true, Description: "Maps to the -ContentPropertyContainsWords parameter."},
			"document_size_over":                                   schema.StringAttribute{Computed: true, Description: "Maps to the -DocumentSizeOver parameter."},
			"except_if_content_contains_sensitive_information":     schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ExceptIfContentContainsSensitiveInformation parameter."},
			"except_if_content_extension_matches_words":            schema.StringAttribute{Computed: true, Description: "Maps to the -ExceptIfContentExtensionMatchesWords parameter."},
			"except_if_content_property_contains_words":            schema.StringAttribute{Computed: true, Description: "Maps to the -ExceptIfContentPropertyContainsWords parameter."},
			"except_if_document_size_over":                         schema.StringAttribute{Computed: true, Description: "Maps to the -ExceptIfDocumentSizeOver parameter."},
			"except_if_odc_content_contains_sensitive_information": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -ExceptIfOdcContentContainsSensitiveInformation parameter."},
			"name": schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"odc_content_contains_sensitive_information": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -OdcContentContainsSensitiveInformation parameter."},
			"policy":                  schema.StringAttribute{Computed: true, Description: "Maps to the -Policy parameter."},
			"start_impact_assessment": schema.BoolAttribute{Computed: true, Description: "Maps to the -StartImpactAssessment parameter."},
			"workload":                schema.StringAttribute{Computed: true, Description: "Maps to the -Workload parameter."},
		},
	}
}

func (d *sensitiveInformationScanRuleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *sensitiveInformationScanRuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data sensitiveInformationScanRuleModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetSensitiveInformationScanRule(ctx, purview.GetSensitiveInformationScanRuleParams{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-SensitiveInformationScanRule failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("SensitiveInformationScanRule not found", "no SensitiveInformationScanRule object for identity "+identity)
		return
	}
	readSensitiveInformationScanRule(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
