// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ datasource.DataSource              = &supervisoryReviewPolicyV2DataSource{}
	_ datasource.DataSourceWithConfigure = &supervisoryReviewPolicyV2DataSource{}
)

type supervisoryReviewPolicyV2DataSource struct{ client *clients.Client }

// NewSupervisoryReviewPolicyV2DataSource looks up a SupervisoryReviewPolicyV2 object (Get-SupervisoryReviewPolicyV2).
func NewSupervisoryReviewPolicyV2DataSource() datasource.DataSource {
	return &supervisoryReviewPolicyV2DataSource{}
}

func (d *supervisoryReviewPolicyV2DataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_supervisory_review_policy_v2"
}

func (d *supervisoryReviewPolicyV2DataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Look up an existing SupervisoryReviewPolicyV2 object. Set identity or name to select it.",
		Attributes: map[string]schema.Attribute{
			"id":                       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
			"identity":                 schema.StringAttribute{Optional: true, Computed: true, Description: "Identity used to look up the object."},
			"add_reviewers":            schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -AddReviewers parameter."},
			"comment":                  schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
			"enabled":                  schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
			"name":                     schema.StringAttribute{Computed: true, Optional: true, Description: "Maps to the -Name parameter."},
			"policy_rbac_scopes":       schema.StringAttribute{Computed: true, Description: "Maps to the -PolicyRBACScopes parameter."},
			"policy_template":          schema.StringAttribute{Computed: true, Description: "Maps to the -PolicyTemplate parameter."},
			"remove_reviewers":         schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -RemoveReviewers parameter."},
			"reviewers":                schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -Reviewers parameter."},
			"user_reporting_workloads": schema.SetAttribute{ElementType: types.StringType, Computed: true, Description: "Maps to the -UserReportingWorkloads parameter."},
		},
	}
}

func (d *supervisoryReviewPolicyV2DataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *supervisoryReviewPolicyV2DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data supervisoryReviewPolicyV2Model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	identity := firstNonEmptyStr(data.Identity.ValueString(), data.Name.ValueString(), data.ID.ValueString())
	if identity == "" {
		resp.Diagnostics.AddError("Missing lookup key", "set identity or name to select the object")
		return
	}
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := d.client.SCC.GetSupervisoryReviewPolicyV2(ctx, purview.GetSupervisoryReviewPolicyV2Params{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, nil)
	if err != nil {
		resp.Diagnostics.AddError("Get-SupervisoryReviewPolicyV2 failed", err.Error())
		return
	}
	if !present {
		resp.Diagnostics.AddError("SupervisoryReviewPolicyV2 not found", "no SupervisoryReviewPolicyV2 object for identity "+identity)
		return
	}
	readSupervisoryReviewPolicyV2(ctx, obj, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
