// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/go-msadmin/consistency"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
	"github.com/terraprovider/tf-msadmin/reconcile"
	"github.com/terraprovider/tf-msadmin/resourcex"
)

var (
	_ resource.Resource                = &supervisoryReviewPolicyV2Resource{}
	_ resource.ResourceWithConfigure   = &supervisoryReviewPolicyV2Resource{}
	_ resource.ResourceWithImportState = &supervisoryReviewPolicyV2Resource{}
)

type supervisoryReviewPolicyV2Resource struct{ client *clients.Client }

// NewSupervisoryReviewPolicyV2Resource manages the SupervisoryReviewPolicyV2 object (New-SupervisoryReviewPolicyV2 / Get-SupervisoryReviewPolicyV2 / Set-SupervisoryReviewPolicyV2 / Remove-SupervisoryReviewPolicyV2).
func NewSupervisoryReviewPolicyV2Resource() resource.Resource {
	return &supervisoryReviewPolicyV2Resource{}
}

type supervisoryReviewPolicyV2Model struct {
	ID                     types.String `tfsdk:"id"`
	Identity               types.String `tfsdk:"identity"`
	AddReviewers           types.Set    `tfsdk:"add_reviewers"`
	Comment                types.String `tfsdk:"comment"`
	Enabled                types.Bool   `tfsdk:"enabled"`
	Name                   types.String `tfsdk:"name"`
	PolicyRBACScopes       types.String `tfsdk:"policy_rbac_scopes"`
	PolicyTemplate         types.String `tfsdk:"policy_template"`
	RemoveReviewers        types.Set    `tfsdk:"remove_reviewers"`
	Reviewers              types.Set    `tfsdk:"reviewers"`
	UserReportingWorkloads types.Set    `tfsdk:"user_reporting_workloads"`
}

func (r *supervisoryReviewPolicyV2Resource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_supervisory_review_policy_v2"
}

func (r *supervisoryReviewPolicyV2Resource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the SupervisoryReviewPolicyV2 object via New-SupervisoryReviewPolicyV2 / Get-SupervisoryReviewPolicyV2 / Set-SupervisoryReviewPolicyV2 / Remove-SupervisoryReviewPolicyV2.",
		Attributes: map[string]schema.Attribute{
			"id":                       schema.StringAttribute{Computed: true, Description: "Object identifier (GUID).", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"identity":                 schema.StringAttribute{Computed: true, Description: "Identity used to target the object in cmdlets."},
			"add_reviewers":            schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -AddReviewers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"comment":                  schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -Comment parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":                  schema.BoolAttribute{Optional: true, Computed: true, Description: "Maps to the -Enabled parameter.", PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
			"name":                     schema.StringAttribute{Required: true, Description: "Maps to the -Name parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"policy_rbac_scopes":       schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PolicyRBACScopes parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"policy_template":          schema.StringAttribute{Optional: true, Computed: true, Description: "Maps to the -PolicyTemplate parameter.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"remove_reviewers":         schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -RemoveReviewers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
			"reviewers":                schema.SetAttribute{ElementType: types.StringType, Required: true, Description: "Maps to the -Reviewers parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.RequiresReplace()}},
			"user_reporting_workloads": schema.SetAttribute{ElementType: types.StringType, Optional: true, Computed: true, Description: "Maps to the -UserReportingWorkloads parameter.", PlanModifiers: []planmodifier.Set{setplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *supervisoryReviewPolicyV2Resource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*clients.Client)
}

func (r *supervisoryReviewPolicyV2Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan supervisoryReviewPolicyV2Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	p := purview.NewSupervisoryReviewPolicyV2Params{
		Comment:                plan.Comment.ValueString(),
		Enabled:                plan.Enabled.ValueBool(),
		Name:                   plan.Name.ValueString(),
		Reviewers:              toStringSlice(ctx, plan.Reviewers, &resp.Diagnostics),
		UserReportingWorkloads: toStringSlice(ctx, plan.UserReportingWorkloads, &resp.Diagnostics),
	}
	if v := plan.PolicyRBACScopes.ValueString(); v != "" {
		p.PolicyRBACScopes = v
	}
	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.SCC.NewSupervisoryReviewPolicyV2(ctx, p)
	if err != nil {
		resp.Diagnostics.AddError("New-SupervisoryReviewPolicyV2 failed", err.Error())
		return
	}
	obj := firstObject(res.Value)
	cfg := plan
	ident := firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name"))
	if !r.refresh(ctx, ident, &plan, &resp.Diagnostics, nil) {
		if resp.Diagnostics.HasError() {
			return
		}
		if obj == nil {
			resp.Diagnostics.AddError("New-SupervisoryReviewPolicyV2 returned no object", "the cmdlet did not return the created object and it could not be read back")
			return
		}
		readSupervisoryReviewPolicyV2(ctx, obj, &plan)
	}
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *supervisoryReviewPolicyV2Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state supervisoryReviewPolicyV2Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.refresh(ctx, r.identityOf(state), &state, &resp.Diagnostics, nil) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *supervisoryReviewPolicyV2Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state supervisoryReviewPolicyV2Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := r.identityOf(state)
	sp := purview.SetSupervisoryReviewPolicyV2Params{}
	sp.Identity = id
	sp.AddReviewers = toStringSlice(ctx, plan.AddReviewers, &resp.Diagnostics)
	sp.Comment = plan.Comment.ValueString()
	sp.Enabled = plan.Enabled.ValueBool()
	if v := plan.PolicyRBACScopes.ValueString(); v != "" {
		sp.PolicyRBACScopes = v
	}
	sp.PolicyTemplate = plan.PolicyTemplate.ValueString()
	sp.RemoveReviewers = toStringSlice(ctx, plan.RemoveReviewers, &resp.Diagnostics)
	sp.UserReportingWorkloads = toStringSlice(ctx, plan.UserReportingWorkloads, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.SetSupervisoryReviewPolicyV2(ctx, sp); err != nil {
		resp.Diagnostics.AddError("Set-SupervisoryReviewPolicyV2 failed", err.Error())
		return
	}
	cfg := plan
	reflected := reconcile.ReflectsFields(map[string]types.String{
		"Comment":          cfg.Comment,
		"PolicyRBACScopes": cfg.PolicyRBACScopes,
		"PolicyTemplate":   cfg.PolicyTemplate,
	}, getString)
	r.refresh(ctx, id, &plan, &resp.Diagnostics, reflected)
	r.reconcileState(&cfg, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *supervisoryReviewPolicyV2Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state supervisoryReviewPolicyV2Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.client.SCC.RemoveSupervisoryReviewPolicyV2(ctx, purview.RemoveSupervisoryReviewPolicyV2Params{Identity: r.identityOf(state)}); err != nil {
		if !isNotFound(err) {
			resp.Diagnostics.AddError("Remove-SupervisoryReviewPolicyV2 failed", err.Error())
		}
	}
}

func (r *supervisoryReviewPolicyV2Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("identity"), req.ID)...)
}

func (r *supervisoryReviewPolicyV2Resource) identityOf(m supervisoryReviewPolicyV2Model) string {
	if v := m.Identity.ValueString(); v != "" {
		return v
	}
	if v := m.ID.ValueString(); v != "" {
		return v
	}
	return m.Name.ValueString()
}

func (r *supervisoryReviewPolicyV2Resource) refresh(ctx context.Context, identity string, m *supervisoryReviewPolicyV2Model, diags *diag.Diagnostics, reflected func(map[string]any) bool) bool {
	get := func(ctx context.Context) (map[string]any, bool, error) {
		res, gerr := r.client.SCC.GetSupervisoryReviewPolicyV2(ctx, purview.GetSupervisoryReviewPolicyV2Params{Identity: identity})
		if gerr != nil {
			if isNotFound(gerr) {
				return nil, false, nil
			}
			return nil, false, gerr
		}
		o := firstObject(res.Value)
		return o, o != nil, nil
	}
	obj, present, err := resourcex.LoadUntil(ctx, consistency.Config{}, get, reflected)
	if err != nil {
		diags.AddError("Get-SupervisoryReviewPolicyV2 failed", err.Error())
		return false
	}
	if !present {
		return false
	}
	readSupervisoryReviewPolicyV2(ctx, obj, m)
	return true
}

func readSupervisoryReviewPolicyV2(ctx context.Context, obj map[string]any, m *supervisoryReviewPolicyV2Model) {
	m.ID = types.StringValue(firstNonEmptyStr(getString(obj, "Guid"), getString(obj, "Id"), getString(obj, "Identity")))
	m.Identity = types.StringValue(firstNonEmptyStr(getString(obj, "Identity"), getString(obj, "Guid"), getString(obj, "Name")))
	m.AddReviewers = stringSetValue(ctx, getStringSlice(obj, "AddReviewers"))
	m.Comment = types.StringValue(getString(obj, "Comment"))
	m.Enabled = types.BoolValue(getBool(obj, "Enabled"))
	m.Name = types.StringValue(getString(obj, "Name"))
	m.PolicyRBACScopes = types.StringValue(getString(obj, "PolicyRBACScopes"))
	m.PolicyTemplate = types.StringValue(getString(obj, "PolicyTemplate"))
	m.RemoveReviewers = stringSetValue(ctx, getStringSlice(obj, "RemoveReviewers"))
	m.Reviewers = stringSetValue(ctx, getStringSlice(obj, "Reviewers"))
	m.UserReportingWorkloads = stringSetValue(ctx, getStringSlice(obj, "UserReportingWorkloads"))
	_ = ctx
}

func (r *supervisoryReviewPolicyV2Resource) reconcileState(cfg, read *supervisoryReviewPolicyV2Model) {
	read.AddReviewers = reconcile.KeepSet(cfg.AddReviewers, read.AddReviewers)
	read.Comment = reconcile.KeepStr(cfg.Comment, read.Comment)
	read.Enabled = reconcile.KeepBool(cfg.Enabled, read.Enabled)
	read.Name = reconcile.KeepStr(cfg.Name, read.Name)
	read.PolicyRBACScopes = reconcile.KeepStr(cfg.PolicyRBACScopes, read.PolicyRBACScopes)
	read.PolicyTemplate = reconcile.KeepStr(cfg.PolicyTemplate, read.PolicyTemplate)
	read.RemoveReviewers = reconcile.KeepSet(cfg.RemoveReviewers, read.RemoveReviewers)
	read.Reviewers = reconcile.KeepSet(cfg.Reviewers, read.Reviewers)
	read.UserReportingWorkloads = reconcile.KeepSet(cfg.UserReportingWorkloads, read.UserReportingWorkloads)
}
