// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &teamsRetentionCompliancePolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &teamsRetentionCompliancePolicyListDataSource{}
)

type teamsRetentionCompliancePolicyListDataSource struct{ client *clients.Client }

// NewTeamsRetentionCompliancePolicyListDataSource lists every TeamsRetentionCompliancePolicy object (Get-TeamsRetentionCompliancePolicy).
func NewTeamsRetentionCompliancePolicyListDataSource() datasource.DataSource {
	return &teamsRetentionCompliancePolicyListDataSource{}
}

type teamsRetentionCompliancePolicyListModel struct {
	Items []teamsRetentionCompliancePolicyModel `tfsdk:"teams_retention_compliance_policies"`
}

func (d *teamsRetentionCompliancePolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_teams_retention_compliance_policies"
}

func (d *teamsRetentionCompliancePolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every TeamsRetentionCompliancePolicy object (Get-TeamsRetentionCompliancePolicy).",
		Attributes: map[string]schema.Attribute{
			"teams_retention_compliance_policies": schema.ListNestedAttribute{Computed: true, Description: "All TeamsRetentionCompliancePolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                                   schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":                             schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"add_teams_channel_location":           schema.StringAttribute{Computed: true, Description: "Maps to the -AddTeamsChannelLocation parameter."},
				"add_teams_channel_location_exception": schema.StringAttribute{Computed: true, Description: "Maps to the -AddTeamsChannelLocationException parameter."},
				"add_teams_chat_location":              schema.StringAttribute{Computed: true, Description: "Maps to the -AddTeamsChatLocation parameter."},
				"add_teams_chat_location_exception":    schema.StringAttribute{Computed: true, Description: "Maps to the -AddTeamsChatLocationException parameter."},
				"comment":                              schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"enabled":                              schema.BoolAttribute{Computed: true, Description: "Maps to the -Enabled parameter."},
				"name":                                 schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"remove_teams_channel_location":        schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveTeamsChannelLocation parameter."},
				"remove_teams_channel_location_exception": schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveTeamsChannelLocationException parameter."},
				"remove_teams_chat_location":              schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveTeamsChatLocation parameter."},
				"remove_teams_chat_location_exception":    schema.StringAttribute{Computed: true, Description: "Maps to the -RemoveTeamsChatLocationException parameter."},
				"restrictive_retention":                   schema.BoolAttribute{Computed: true, Description: "Maps to the -RestrictiveRetention parameter."},
				"retry_distribution":                      schema.BoolAttribute{Computed: true, Description: "Maps to the -RetryDistribution parameter."},
				"teams_channel_location":                  schema.StringAttribute{Computed: true, Description: "Maps to the -TeamsChannelLocation parameter."},
				"teams_channel_location_exception":        schema.StringAttribute{Computed: true, Description: "Maps to the -TeamsChannelLocationException parameter."},
				"teams_chat_location":                     schema.StringAttribute{Computed: true, Description: "Maps to the -TeamsChatLocation parameter."},
				"teams_chat_location_exception":           schema.StringAttribute{Computed: true, Description: "Maps to the -TeamsChatLocationException parameter."},
			}}},
		},
	}
}

func (d *teamsRetentionCompliancePolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *teamsRetentionCompliancePolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetTeamsRetentionCompliancePolicy(ctx, purview.GetTeamsRetentionCompliancePolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-TeamsRetentionCompliancePolicy failed", err.Error())
		return
	}
	var data teamsRetentionCompliancePolicyListModel
	for _, obj := range res.Value {
		var e teamsRetentionCompliancePolicyModel
		readTeamsRetentionCompliancePolicy(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
