// Code generated by gen-tf; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/terraprovider/go-exoscc/purview"
	"github.com/terraprovider/terraform-provider-scc/internal/clients"
)

var (
	_ datasource.DataSource              = &threatResponsePolicyListDataSource{}
	_ datasource.DataSourceWithConfigure = &threatResponsePolicyListDataSource{}
)

type threatResponsePolicyListDataSource struct{ client *clients.Client }

// NewThreatResponsePolicyListDataSource lists every ThreatResponsePolicy object (Get-ThreatResponsePolicy).
func NewThreatResponsePolicyListDataSource() datasource.DataSource {
	return &threatResponsePolicyListDataSource{}
}

type threatResponsePolicyListModel struct {
	Items []threatResponsePolicyModel `tfsdk:"threat_response_policies"`
}

func (d *threatResponsePolicyListDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_threat_response_policies"
}

func (d *threatResponsePolicyListDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "List every ThreatResponsePolicy object (Get-ThreatResponsePolicy).",
		Attributes: map[string]schema.Attribute{
			"threat_response_policies": schema.ListNestedAttribute{Computed: true, Description: "All ThreatResponsePolicy objects.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"id":                 schema.StringAttribute{Computed: true, Description: "Object identifier (GUID)."},
				"identity":           schema.StringAttribute{Computed: true, Description: "Identity used to target the object."},
				"comment":            schema.StringAttribute{Computed: true, Description: "Maps to the -Comment parameter."},
				"exchange_location":  schema.StringAttribute{Computed: true, Description: "Maps to the -ExchangeLocation parameter."},
				"mode":               schema.StringAttribute{Computed: true, Description: "Maps to the -Mode parameter."},
				"name":               schema.StringAttribute{Computed: true, Description: "Maps to the -Name parameter."},
				"new_name":           schema.StringAttribute{Computed: true, Description: "Maps to the -NewName parameter."},
				"retry_distribution": schema.BoolAttribute{Computed: true, Description: "Maps to the -RetryDistribution parameter."},
			}}},
		},
	}
}

func (d *threatResponsePolicyListDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*clients.Client)
}

func (d *threatResponsePolicyListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	res, err := d.client.SCC.GetThreatResponsePolicy(ctx, purview.GetThreatResponsePolicyParams{})
	if err != nil {
		resp.Diagnostics.AddError("Get-ThreatResponsePolicy failed", err.Error())
		return
	}
	var data threatResponsePolicyListModel
	for _, obj := range res.Value {
		var e threatResponsePolicyModel
		readThreatResponsePolicy(ctx, obj, &e)
		data.Items = append(data.Items, e)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
